src/components/dev-hub/series.js
src/templates/article.js

This PR cleans up the series component, specifically adding the following things:
- Fixes text overflow ellipsis
- Fixes border/bullet interactions
- Cleans up mobile styling
- Moves series logic in `article.js` into own component.
Since bullets are text, I used a filled in bullet behind to hide the border going through the bullet.

Cleanup for Article Series Component

---

src/utils/map-tag-type-to-url.js

Should resolve the titlecase issue.

Force lowercase on tags

---

src/pages/community/index.js

FYI @jbouzi12 just swapping these two per feedback

swap events and community link

---

src/components/dev-hub/codeblock.js

Talked with Sue and we wanted to try out not passing the language explicitly.

set language to auto

---

gatsby-node.js
src/pages/community/events.js
src/pages/index.js
src/templates/article.js

Getting pretty noisy in the build output

remove log output

---

src/components/dev-hub/event-list.js
src/components/dev-hub/events.js
src/components/dev-hub/hero-banner.js
src/pages/community/events.js
src/pages/community/index.js
src/pages/index.js

Approved copy from the meeting yesterday. Also includes a few style tweaks that were called out.

final copy

---

src/components/dev-hub/article-share-footer.js
src/templates/article.js

this PR adds the bottom area to articles with just tags for now (need to get clarity on where the share links should go).

Article Bottom Tags

---

src/components/Figure.js

Fixes the 'click to enlarge' and `double image` issue writers are seeing.

remove lightbox from figures

---

src/components/dev-hub/video-embed.js

add some bottom margin to embedded player

---

src/components/dev-hub/project-sign-up-form.js
src/hooks/use-segment-data.js

We need to add some segment data to the post call for security purposes. 
honestly not sure if this will work because we don't have segment locally (but it at least shouldn't break things)

add segment data for post call

---

src/components/dev-hub/card-list.js
src/components/dev-hub/loading.js
src/pages/learn.js

and update article cards to be `align-items: start`

add loading state for article filters

---

src/pages/community/events.js
src/templates/tag.js

Fixed links for breadcrumbs on events and tag result pages.

Fix breadcrumb links for events and tags pages

---

src/pages/404.js

https://www.gatsbyjs.org/docs/add-404-page/

add 404 page

---

gatsby-node.js
src/components/dev-hub/related-articles.js
src/pages/learn.js

This PR adds the articles to the learn page to the page context statically generated. There should be no changes on the content shown, but there should no longer be a "loading" state there.

Static render learn page content

---

gatsby-config.js
gatsby-config.prod.js
src/components/TwitterMeta.js
src/constants.js
src/hooks/use-site-metadata.js
src/pages/community/events.js
src/pages/community/index.js
src/pages/learn.js
src/templates/article.js

Updates some meta info and page titles

meta and titles

---

src/components/ComponentFactory.js

Don't want to render any warnings onto the page

just warn on a missing directive

---

gatsby-config.js
gatsby-config.prod.js
package-lock.json
package.json

This should automatically generate a site-map.

add sitemap plugin

---

src/components/ListTable.js

didn't have designs for this so let me know if you can think of a way to make this look better!

add styles to table

---

src/components/dev-hub/article-share-footer.js
src/templates/article.js

This PR adds share links to articles to allow people to copy the link, share on facebook, and share on twitter.
If they copy the link, we show a little tooltip as feedback.
(on copy)
(mobile)

Share Links on Article

---

src/components/dev-hub/global-nav.js

show active links in nav

---

src/components/Link.js
src/components/RefRole.js

Brings in some changes to link and refrole from snooty

update link and refrole

---

gatsby-node.js
src/templates/tag.js
src/utils/get-nested-text.js

This PR adds bios for authors from passed in page data.

Author Bios

---

.storybook/addons.js
.storybook/config.js
.storybook/webpack.config.js
package-lock.json
package.json
src/components/dev-hub/icons/icons.stories.mdx
src/components/dev-hub/theme.stories.js
src/welcome.stories.mdx

This PR adds a beginning MDX storybook! You can run this storybook the same way as the mitx storybook.
The MDX format changes how stories are written to something much simpler. There are `Icon` and `Color` stories here, but the `Icon` is the only one with mdx integrated.
To see the docs, click "docs" towards the top after `npm install`ing and running the storybook.
I also added a "Welcome" mdx story which can help document some storybook practices.

Add MDX Storybook

---

src/components/dev-hub/card.js
src/components/dev-hub/layout.js

This PR:
- Bumps line height default for `p` to `32px` as per request.
- Adjusts line height for description text on cards as per design

Adjust Line Heights on P, Card

---

src/components/dev-hub/card.js

remove fixed card height

---

src/components/ListTable.js

ticket - https://jira.mongodb.org/browse/DEVHUB-42

add table title

---

src/components/dev-hub/events.js
src/components/dev-hub/stories/events.stories.mdx
src/hooks/use-event-data.js
src/pages/community/events.js
src/pages/storybook.js

fixes event urls from mongodb events website.

Remove conditional url logic in event object

---

src/components/dev-hub/events.js
src/components/dev-hub/stories/events.stories.mdx
src/hooks/use-event-data.js
src/pages/community/events.js
src/pages/storybook.js

* Remove conditional url logic in event object
* remove unused imports and variables
* remove sample data
Co-authored-by: Gregg Brewster <mail@digitalpuddle.com>

Remove conditional url logic in event object (#229)

---

src/pages/index.js

Content writers updated this image and title in the article and owuld like the homepage to match.

update title and image for atlast cluster

---

src/components/TwitterMeta.js

graph tags need the full site url

use full image path for meta tags

---

src/components/TwitterMeta.js
src/templates/article.js

- Handle external image src
- handle missing src
- update meta tag closing

update tag fields

---

src/pages/index.js
src/pages/learn.js
src/utils/get-featured-card-fields.js

This PR pulls out the hardcoded articles on the home page and adds the ability to render featured articles dynamically, similar to with the learn page.

Render Dynamic Featured Articles on Home Page

---

src/components/dev-hub/chart.js

Remove iframe border from charts

---

src/components/Literal.js
src/components/Target.js
tests/unit/__snapshots__/DefinitionList.test.js.snap
tests/unit/__snapshots__/Literal.test.js.snap

Duplicates https://github.com/mongodb/snooty/pull/164.
- Update targets to handle new node structure emitted by parser
- Simplify Literal component to remove unnecessary `<span>` and align with Docs implementation

Update Target handling

---

src/pages/learn.js
src/utils/get-featured-card-fields.js

Noticed homepage images here were not being prefixed http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/9deb725/devhub/docsworker-xlarge/greggb-patch-1/

add prefix to dynamic feature articles

---

src/components/dev-hub/byline-block.js

Fixes inconsistent author types on various datasets

Add backwards compatible author parsing

---

src/components/ComponentFactory.js

The charts directive for embedding an Atlas chart is `charts`

map charts directive to chart component

---

.github/workflows/devhub-npm-test.yaml
README.md

This PR adds a simple action to run `npm test` on a PR to staging or master

Add npm test GH action

---

src/constants.js
src/hooks/use-all-media.js
src/hooks/use-event-data.js
src/hooks/use-twitch-api.js
src/utils/fetch-twitch-videos.js
src/utils/fetch-youtube-data.js

This PR creates a single hook that a component can use to query all media data.

Create a Hook for All Media Data

---

src/pages/index.js
src/utils/get-twitch-thumbnail.js

Created a separate file containing `getThumbnail()` logic in order to access it from multiple pages

Pulled getThumbnail() logic out of index.js page

---

package-lock.json

Wiped old `package-lock.json` file and generated a new one using `npm i --production`

Use updated package-lock.json

---

src/components/dev-hub/stories/tab.stories.mdx

This PR documents the `Tab` component on storybook

Storybook entry for the tab component

---

src/hooks/use-all-videos.js

This PR switches to target youtube playlist to [this one](https://www.youtube.com/playlist?list=PL4RCxklHWZ9sLmYcronGcCu6HOYCPEcAF) (given from Deepak).

Switch to MDB Youtube Playlist

---

src/components/dev-hub/project-sign-up-form.js

This PR adds type attribute and `maxLength` to validate user inputs on the homepage share ideas/projects form.

Homepage input validation

---

src/pages/academia.js

This PR adds the new `Academia` page with header. Since the images and texts are not finalized yet, it is still a work in progress.

Academia page header

---

src/components/dev-hub/academia-sign-up-form.js
src/components/dev-hub/input.js
src/components/dev-hub/project-sign-up-form.js
src/components/dev-hub/section-header.js
src/components/dev-hub/select.js
src/components/dev-hub/success-state.js
src/pages/academia.js

This PR adds the UI for the sign up form that will allow instructors to join MongoDB Academia. It does not yet include the code to communicate with a backend upon submission. 
It also includes minor modification to both the `Select` and `SectionHeader` components to allow styling.

Academia sign up form

---

src/images/1x/Academia.svg
src/pages/index.js

e95df67 Gb/academia homepage block (#440)
f280dd8 Merge pull request #438 from mongodb/js/alt-academia

Staging => Master

---

src/components/dev-hub/hero-banner.js
src/pages/code-for-good.js

This is PR adds the new `Code for Good` page for DevHub.

Code for Good page 

---

src/pages/code-for-good.js

Requested link and text updates.

Add database tools link and text

---

src/components/dev-hub/link.js
src/components/dev-hub/modal.js
src/components/dev-hub/notification.js
src/components/dev-hub/project-sign-up-form.js
src/components/dev-hub/related-articles.js
src/components/dev-hub/section-header.js
src/components/dev-hub/select.js
src/components/dev-hub/series.js
src/components/dev-hub/share-menu.js
src/components/dev-hub/slider.js
src/components/dev-hub/tab.js
src/components/dev-hub/text-area.js
src/components/dev-hub/upload-button.js
tests/unit/Heading.test.js
tests/unit/Link.test.js
tests/unit/Reference.test.js
tests/unit/__snapshots__/Heading.test.js.snap
tests/unit/__snapshots__/Link.test.js.snap
tests/unit/__snapshots__/Reference.test.js.snap

This is the last batch of components to be swapped to emotion theme (we still have to do the pages as well, but that should be short).
One note is the link snapshots had to be updated and we had to wrap our tests in the theme as well when mounting.
Like the other batches, I ran a job for this. [Here is the link to this branch built](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/c70c8c3/devhub/docsworker-xlarge/emotion-theme-lu/).

Emotion Theme for Component Batch L-U

---

src/pages/academia/educators.js
src/pages/code-for-good.js
src/pages/community/events.js
src/pages/community/index.js
src/pages/index.js
src/pages/learn.js
src/templates/tag.js

This PR is the last piece of the emotion theme conversion work, specifically for our Pages and Templates. This is pretty short, but I still wanted to run a job for it. The hosted site for this branch is [here](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/0e2dff9/devhub/docsworker-xlarge/emotion-theme-pages/).
I'll take a quick look then open this for review.

Emotion Theme for Pages and Templates

---

src/utils/setup/create-tag-page-type.js

Adding a new map entry for the MongoDB Inc. author

add mongodb inc author map

---

src/utils/setup/create-tag-page-type.js

add mongodb inc author map (#464)

---

src/utils/fetch-event-data.js

[Staging](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/3427b50/devhub/docsworker-xlarge/08-11-20/)
This PR puts out the new meta description tag for the home page on master. I verified the tag is there with the approved copy.
```
eb82987 Merge pull request #476 from mongodb/js/meta-description
```

staging --> master deploy (meta description)

---

cypress/integration/article.js
src/components/dev-hub/link.js
tests/unit/__snapshots__/Heading.test.js.snap
tests/unit/__snapshots__/Link.test.js.snap
tests/unit/__snapshots__/Reference.test.js.snap

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f612d7f7851f76f1dea5dba)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/776b8b8/devhub/docsworker-xlarge/relative-link-fix/)
```
9fb4d51 DEVHUB-220: Relative Link Fix (#508)
```

staging --> master DEVHUB-220: Relative Link Fix (#508)

---

src/components/DefinitionListItem.js
src/components/RefRole.js
src/components/Target.js
src/utils/find-key-value-pair.js

Support upcoming breaking changes in snooty-parser (to be introduced in ~v.0.6.0 next week). Introduced in this PR: https://github.com/mongodb/snooty-parser/pull/204
Equivalent change in Snooty: https://github.com/mongodb/snooty/pull/271

DOP-1409: Support new AST structure for target IDs

---

package-lock.json
package.json

Reverts mongodb/devhub#551, getting odd errors on the workerpool jobs

Revert "Bump gatsby to 2.26"

---

.github/workflows/devhub-ci-test.yaml
gatsby-config.js
gatsby-config.prod.js
package-lock.json
package.json
src/queries/projects.js

[JIRA](https://jira.mongodb.org/browse/DEVHUB-298)
This PR adds the `gatsby-source-strapi` plugin formally to the app with config and a small `projects` query. This query will be used in future work.

DEVHUB-298: Add Strapi Plugin Barebones

---

src/components/pages/home/academia-feature.js
src/components/pages/home/community-feature.js
src/components/pages/home/events-feature.js
src/components/pages/home/feature-section.js
src/components/pages/home/hero.js
src/components/pages/home/index.js
src/components/pages/home/twitch-feature.js
src/pages/index.js
src/utils/setup/find-articles-from-slugs.js
src/utils/setup/get-learn-page-filters.js
src/utils/setup/handle-create-home-page.js
src/utils/setup/handle-create-learn-page.js
src/utils/setup/handle-create-page.js
tests/utils/find-articles-from-slugs.test.js
tests/utils/get-learn-page-filters.test.js

[Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5fe2385aceb0c9c2e5ba4a3d)
[Staging](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/b4bfcb9/devhub/docsworker-xlarge/12-22-20/)
```
6ef1020 Modularize Home Page (#575)
28fa05c Refactor build time pages (#573)
```

(Merge after holidays) Refactor build time pages & home page (#573)

---

.github/workflows/devhub-ci-test.yaml
.github/workflows/devhub-npm-test.yaml
gatsby-config.js
gatsby-config.prod.js
package-lock.json
package.json

This PR copies the changes made on `student-spotlight` to add in Strapi, but just on this feature branch since we don't need Strapi in production yet.

DEVHUB-387 [Part 1]: Add Strapi Plugin

---

src/components/dev-hub/video-embed.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/lazy-load-videos/)
```
423f337 Lazy load react-player for videos (#592)
```
Small deploy to reduce unused JS from the React Player library for videos.

Lazy load react-player for videos (#592)

---

cypress.json
cypress/integration/nav.js
src/components/dev-hub/menu-toggle.js

No staging link
This PR adds a suite of cypress tests for the mobile and desktop new Nav menus checking basic functionality.

DEVHUB-431: CI testing for New Nav

---

src/components/dev-hub/global-nav.js
src/components/dev-hub/nav-item.js
src/components/dev-hub/theme.js

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/add-small-desktop/)
This PR adds a new breakpoint of 1200px for the nav. We also change padding on elements if between 1023px and 1200px as well as 1200px and 1440px.

Add Small Desktop Breakpoint for Nav

---

src/components/dev-hub/global-nav.js
src/components/dev-hub/link.js
src/components/dev-hub/nav-item.js
tests/unit/__snapshots__/Heading.test.js.snap
tests/unit/__snapshots__/Link.test.js.snap
tests/unit/__snapshots__/Reference.test.js.snap

[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/nav-colors/)
This PR updates link colors to #FBF9FA and ensures heading colors on the nav match that

Ensure nav text colors and links are #F9FBFA

---

src/components/dev-hub/icons/arrowhead-icon.js
src/components/dev-hub/theme.js
src/components/pages/project/authors.js
src/components/pages/project/index.js
src/components/pages/project/students.js
src/templates/project.js
src/utils/setup/create-project-pages.js

[Staging (single page)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-305/project/go-fifa)
This PR adds the new component for showing a student in the projects page (desktop only). We also update the logic from the POC to generate project pages by running raw data through the `transform` for projects.
It seems like we might be missing some student data on Strapi, so I will follow up with Lieke to see if this is the case

DEVHUB-305: Add Students Component to Project Page

---

src/components/pages/project/students.js
src/queries/projects.js

[Staging (project)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/student-bio-render/project/go-fifa)
This PR adds the `bio` field to our build-time GraphQL query for projects. This was missing before, however we did lay out the bio so not much additional visual work was needed.

Include Student Bio in GraphQL Query

---

src/components/dev-hub/student-spotlight/share-project-cta.js
src/components/pages/home/academia-feature.js
src/components/pages/student-submit/form.js
src/components/pages/student-submit/index.js
src/components/pages/student-submit/top-banner.js
src/pages/academia/students/submit.js

No staging link needed
This PR creates the basic blank page scaffolding for the student spotlight submit page. It also updates two links to point to the correct pages (home page should point to entry page, share button should point to the correct slug for the form)

DEVHUB-308 [Part 1] - Create submit page scaffolding, update link

---

src/components/pages/student-submit/top-banner.js

[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-308-top-banner/academia/students/submit/)
This PR adds the basic Hero content to the Student Spotlight Submission page. Aside from the actual content this is nearly identical to the banners on other student-spotlight page so our next step (cleanup) could be to refactor here into a more general banner that follows this structure.

DEVHUB-308 [Part 2] - Add basic top banner content

---

jest.config.js
package-lock.json
src/components/Reference.js
src/components/dev-hub/related-articles.js
src/pages/index.js
src/utils/make-link-internal-if-applicable.js
tests/utils/make-link-internal-if-applicable.test.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60219d66ab23346c20f31912)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/60c448c/devhub/docsworker-xlarge/feb-10-21/)
[Deploy Notes](https://wiki.corp.mongodb.com/display/DEVREL/Developer+Hub+Release+Notes)
```
d2922bf DEVHUB-423: Make Reference internal links actually internal (#629)
fabd39c DEVHUB-458: Add Structured Brand Data (#644)
```

Feb 10 2021 Deploy

---

src/components/pages/student-submit/form/image-dropzone.js
src/components/pages/student-submit/form/index.js
src/components/pages/student-submit/form/project-info.js
src/components/pages/student-submit/form/promote-yourself.js
src/components/pages/student-submit/form/share-details.js
src/hooks/use-student-spotlight-reducer.js
src/utils/student-spotlight-reducer.js

[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-313/academia/students/submit/)
This PR adds some basic state to the student spotlight submission form and allows the file inputs to be properly validated. State is managed by a simple, naive reducer since it scales nicely for the form.
For validating file inputs, since we are using custom buttons to open the file modal using `display: none` would also prevent the browser from properly populating the validation message if incorrect. The solution here is to use the background to our advantage and just give a low z-index while we position absolutely.

DEVHUB-313: Track From State & Validate

---

src/components/pages/student-submit/form/condensed-student-entry.js
src/components/pages/student-submit/form/index.js
src/components/pages/student-submit/form/new-student-fieldset.js
src/components/pages/student-submit/form/promote-yourself.js
src/components/pages/student-submit/form/submit-form-fieldset.js
src/hooks/use-student-spotlight-reducer.js
src/utils/student-spotlight-reducer.js

[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-312-multiple-authors/academia/students/submit/)
This PR adds the ability to have multiple students when submitting a project via the Student Spotlight submission form. Note this is not validated yet and not hooked to Realm, but the state management is present.
The goal was to update our reducer in a way that scales for many students and supports basic operations such as add/remove easily. One nuance was adding a `key` field to allow React to manage state properly (especially on removal).

DEVHUB-312 [Part 1] - Multiple Authors (No Form Validation)

---

src/components/dev-hub/global-nav.js

This needs some more testing to reduce re-renders and such

Revert CLS Change

---

src/components/pages/student-submit/form/image-dropzone.js
src/components/pages/student-submit/form/index.js
src/components/pages/student-submit/form/new-student-fieldset.js
src/components/pages/student-submit/form/project-info.js
src/utils/devhub-api-stitch.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-310/academia/students/submit/)
This PR adds the needed plumbing to submit the student spotlight form. There are a couple nuances here:
1. Most of the logic routes through Realm
2. Image uploads are done directly to Strapi. This is because Realm doesn't have the best way of handling images aside from sending through a base64 encoding which seems more troublesome than just using Strapi's provided `upload` route.
3. We had to get a wonky callback to let the student image work. This is also still having a bug so I just put it on the UAT sheet and will come back to it.
4. Success and loading states are WIP

DEVHUB-310: Submit the Student Spotlight Form

---

src/components/dev-hub/student-spotlight/share-project-cta.js

[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-479/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-479)
This PR swaps copy on various buttons to match the desired text of "Show Off Your Project" everywhere.

DEVHUB-479: Swap CTA text to 'project'

---

src/components/pages/student-submit/top-banner.js

[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-476/academia/students/submit)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-476)
This PR updates the copy shown on the Student Spotlight Submission Form.

DEVHUB-476: Swap Copy on Form

---

src/components/pages/academia/project-grid.js
src/components/pages/academia/students-educators-details.js

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-entry-page/academia/)
This PR cleans up responsiveness on the Academia Entry Page aside from the content grid.

DEVHUB-444 [Part 2]: Academia Entry Page Responsiveness

---

src/pages/academia/index.js
src/pages/academia/students/index.js
src/pages/academia/students/submit.js
src/templates/project.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-443/)
This PR adds or updates the `SEO` component on each student spotlight page to be sure the following items are supplied in some form:
- Page title
- Meta Description
- OG information (minus Image)
- Twitter information (minus Image)

DEVHUB-443: Add/Augment the SEO Tags on Student Spotlight Pages

---

src/components/pages/project/sidebar-content.js
src/components/pages/student-submit/form/project-info.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-477/)
This PR updates language in the student spotlight stuff to generalize any language to GitHub to include other repositories like GitLab or Bitbucket by using "View Code" and etc.

DEVHUB-477: Generalize Source Code Repo Language

---

src/components/dev-hub/academia-sign-up-form.js
src/components/dev-hub/project-card.js
src/components/pages/academia/students-educators-details.js
src/components/pages/educators/green-bulleted-list.js
src/components/pages/educators/sign-up-modal.js
src/components/pages/home/project-card-grid.js

[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-478-part-2/)
[UAT Sheet](https://docs.google.com/spreadsheets/d/10bDBzs-QnbaF5vdo19a1JRw-ALdaNZLOcS4Bil92joQ/edit#gid=0)
This PR continues the work to address design concerns on Student Spotlight. Here we:
- Adds the link on the home page to go to the gallery page
- Changes the description size on project cards
- Updates the color of `BulletText` on the entry page
- Updates the font family of the CTA links on the entry page
- Removes some spacing on the educators form and centers the form vertically

DEVHUB-478: Part 2

---

src/components/pages/student-submit/form/form-error-modal.js
src/components/pages/student-submit/form/form-submitting-modal.js
src/components/pages/student-submit/form/form-success-modal.js
src/components/pages/student-submit/form/index.js
src/utils/on-student-spotlight-form-submission.js
src/utils/upload-images-to-strapi.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-481/)
This PR cleans up logic relating to submitting the Student Spotlight project form and adds error handling for the various requests made.
Keeping as a draft while I clean some of the handlers up

DEVHUB-481 [Part 1]: Refactor Form Submission, add WIP Error Handling

---

src/pages/academia/index.js
src/pages/academia/students/index.js
src/pages/academia/students/submit.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6038071275e817aef70eaed7)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/e0c341e/devhub/docsworker-xlarge/feb-25-21-2/academia/)
Deploys a fix to OG:Url generation for Student Spotlight static pages
```
b44f7ed DEVHUB-500: Fix OG:URL /*/ bug on Academia Static Pages (#693)
```

DEVHUB-500: Fix OG:URL /*/ bug on Academia Static Pages (#693)

---

.gitignore
gatsby-config.js
gatsby-config.prod.js
package-lock.json
package.json
src/components/pages/home/hero.js
src/pages/learn.js
src/utils/get-featured-card-fields.js
static/sitemap.xml

[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/3aa7baf/devhub/docsworker-xlarge/march-03-21/)
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=603fa96875e817aef765148d)
```
2f87eff DEVHUB-498: Add tracking param to featured articles on home/learn pages (#698)
e58ffad DEVHUB-509: Convert to using sitemap-index (#697)
```

Deploy March 3rd, 2021

---

src/components/dev-hub/hero-banner.js
src/components/pages/academia/top-banner.js
src/components/pages/student-submit/top-banner.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=604268f275e817aef7e76d9f)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/568ca6b/devhub/docsworker-xlarge/march-05-21/)
```
445f794 DEVHUB-527: Maintain 1:1 Hero Image Aspect Ratio on Mobile (#703)
```

Deploy March 5th, 2021

---

cypress.json
cypress/integration/search.js
cypress/support/commands.js
src/components/dev-hub/searchbar/CondensedSearchbar.js
src/components/dev-hub/searchbar/ExpandedSearchbar.js
src/components/dev-hub/searchbar/Pagination.js
src/components/dev-hub/searchbar/SearchDropdown.js
src/components/dev-hub/searchbar/SearchResult.js

This PR adds a suite of UI tests for the upcoming Search UI. CI should continue to pass.
This leverages logic used in the text filter to stub responses.

DEVHUB-526: Add UI Tests for Search

---

cypress/integration/article.js
src/components/dev-hub/article-schema.js
src/templates/article.js
tests/unit/ArticleSchema.test.js
tests/unit/__snapshots__/ArticleSchema.test.js.snap
tests/unit/data/ArticleSchema.test.json

This PR adds schema for devhub blog posts.

 [DEVHUB-117] Metadata needed for devhub blog posts

---

cypress/integration/article.js
src/components/dev-hub/article-schema.js
src/templates/article.js
tests/unit/ArticleSchema.test.js
tests/unit/__snapshots__/ArticleSchema.test.js.snap
tests/unit/data/ArticleSchema.test.json

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=604a34a775e817aef7571048)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/c3d79e8/devhub/docsworker-xlarge/march-11-21/)
```
be6858c  [DEVHUB-117] Metadata needed for devhub blog posts (#706)
```

Release March 11 2021

---

src/components/pages/students/featured-project.js

[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/spotlight-width/academia/students/)
This PR simply adds a `width` declaration for the featured student spotlight project so it fills its entire container.

Fill featured spotlight project width

---

src/components/pages/students/featured-project.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=604a612c75e817aef7601832)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/c3d79e8/devhub/docsworker-xlarge/march-11-2021-2/)
```
cd43a53 Fill feature spotlight project width (#713)
```

Deploy fill feature spotlight project width (#713)

---

src/components/dev-hub/searchbar/ExpandedSearchbar.js
src/components/dev-hub/searchbar/SearchDropdown.js
src/components/dev-hub/searchbar/SearchResult.js
src/components/dev-hub/searchbar/SearchResults.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-555-misc/)
[Figma](https://www.figma.com/file/alg7BWjspWbpLmys9vS4KC/DevHub-Search?node-id=0%3A1)
This PR makes the following tweaks:
- Adjusts grid sizing of results on desktop and mobile
- Adds `aria-label` to the close button on mobile
- Updates line-heights to 24px where appropriate

DEVHUB-555: Misc Search UI Requests

---

src/components/dev-hub/searchbar/CondensedSearchbar.js
src/components/dev-hub/searchbar/ExpandedSearchbar.js
src/components/dev-hub/searchbar/SearchDropdown.js
src/components/dev-hub/searchbar/SearchResults.js
src/components/dev-hub/searchbar/SearchTextInput.js
src/components/dev-hub/searchbar/Searchbar.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-555-colors/)
Adds some more cleanup for the search UI, including:
- Bumping up sizes of icons on mobile
- Dropping font sizes on mobile
- Fixing the heights of search results
- Updating colors on the various icons

DEVHUB-555: Continued Cleanup

---

package-lock.json
package.json
src/components/dev-hub/global-footer.js
src/constants.js
src/pages/code-for-good.js
src/pages/community/index.js
src/pages/index.js
src/utils/make-link-internal-if-applicable.js
tests/utils/make-link-internal-if-applicable.test.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6052120b75e817aef7cb15ea)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25c77c5/devhub/docsworker-xlarge/march-17-2021/)
```
0a019e5 Bump gatsby-source-strapi to 1.0.0-alpha.0 (#721)
a77a2cb DEVHUB-503: Move all instances of developer.mongodb.com to one variable in repo (#716)
```
This PR releases an upgraded version of the Strapi source plugin as well as some prep work for the subdomain consolidation.

Deploy 1 March 17 2021

---

src/components/dev-hub/global-nav.js
src/components/dev-hub/menu-toggle.js
src/components/dev-hub/searchbar/CondensedSearchbar.js
src/components/dev-hub/searchbar/Searchbar.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/desktop-max-width/)
Fixes max width to 1440px

Fix max width on desktop

---

cypress/integration/search.js
src/components/dev-hub/global-nav.js
src/components/dev-hub/searchbar/CondensedSearchbar.js
src/components/dev-hub/searchbar/ExpandedSearchbar.js
src/components/dev-hub/searchbar/SearchResults.js
src/components/dev-hub/searchbar/SearchTextInput.js
src/components/dev-hub/searchbar/Searchbar.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-544-final/)
Fixes some misc UI/UX fixes from UAT:
- Input padding on Safari iOS
- Disables nav when expanded
- Magnifying glass colors
- Empty State

DEVHUB-544: Misc UI/UX

---

src/components/Link.js
tests/unit/Link.test.js
tests/unit/__snapshots__/Link.test.js.snap

This PR changes RegExp for fixing link logic.

DEVHUB-552: Fix mailto link logic

---

src/components/Link.js
tests/unit/Link.test.js
tests/unit/__snapshots__/Link.test.js.snap

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6054a6fe2723a9e448dee801)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25c77c5/devhub/docsworker-xlarge/march-19-21/)
* DEVHUB-552: Fix mailto link logic

Deploy DEVHUB-552: Fix mailto link logic (#727)

---

gatsby-config.js
gatsby-node.esm.js
src/queries/authors.js
src/templates/tag.js
src/utils/setup/create-strapi-author-pages.js
src/utils/setup/transform-author-strapi-data.js
tests/utils/transform-author-strapi-data.test.js

[Staging Sample Author](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-546/author/jordan-stapinski/)
This PR lays the ground work for pulling Strapi authors into DevHub by mapping the basic content to a page. The next step will be to correctly pull their articles.

DEVHUB-546 [Part 1] Strapi-based Author Page (No Article Grid)

---

src/components/Link.js
src/components/dev-hub/related-articles.js
src/components/dev-hub/searchbar/SearchResult.js
src/utils/is-link-for-image.js
src/utils/make-link-internal-if-applicable.js
tests/utils/is-link-for-image.test.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6058d0da2723a9e448a38a87)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25b048a/devhub/docsworker-xlarge/march-22-21/)
```
41c6dc8f DEVHUB-559: Fix Staging Internal Links (#737)
78d79d17 DEVHUB-570: Don't add trailing slashes to internal image links (#731)
```

Deploy March 22, 2021

---

cypress/integration/author.js
cypress/integration/learn.js
src/pages/learn.js
src/templates/tag.js

This PR adds a new page title for numbered article pages also refreshes some tests.

DEVHUB-560: Implement page number into page title for numbered article pages

---

cypress/integration/search.js
src/components/dev-hub/searchbar/ExpandedSearchbar.js
src/components/dev-hub/searchbar/Searchbar.js

This PR adds the opportunity to open a search bar on devhub with / (slash).

DEVHUB-549: Search on devhub with / shortcut

---

cypress/integration/author.js
cypress/integration/learn.js
cypress/integration/search.js
gatsby-config.js
gatsby-config.prod.js
gatsby-node.esm.js
src/components/dev-hub/searchbar/ExpandedSearchbar.js
src/components/dev-hub/searchbar/Searchbar.js
src/pages/learn.js
src/queries/client-side-redirects.js
src/templates/tag.js
src/utils/setup/create-client-side-redirects.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=605b3f142723a9e4481d703f)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/71e900f/devhub/docsworker-xlarge/march-24-21/)
```
c424c5d1 DEVHUB-549: Ensure slash key works on Firefox (#742)
102638e3 DEVHUB-549: Search on devhub with / shortcut (#734)
8aaa8668 DEVHUB-574: Add CMS Support for Gatsby Redirects (#741)
9f93d976 DEVHUB-560: Implement page number into page title for numbered article pages (#735)
```

Deploy March 24th 2021

---

cypress/integration/search.js

This PR adds a click to `body` so the proper focus is applied.

Fix Search Slash UI Test

---

cypress/integration/search.js
gatsby-node.esm.js
src/queries/search-article-rss-data.js
src/utils/setup/create-article-node.js
src/utils/setup/serialize-search-rss-data.js
tests/utils/create-article-node.test.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=605b73232723a9e448280bce)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/71e900f/devhub/docsworker-xlarge/march-24-21-2/)
```
cb44070b DEVHUB-553: Add Article raw_content to search XML (#745)
```

Deploy: DEVHUB-553: Add Article raw_content to search XML (#745)

---

cypress/integration/author.js
cypress/integration/learn.js
cypress/integration/tag.js
src/pages/learn.js
src/templates/tag.js

This PR changes H2 to H1 tags without style changes.

DEVHUB-561: Implement a H1 to all paginated article pages which contains the page number

---

.github/workflows/devhub-ci-test.yaml
.github/workflows/devhub-npm-test.yaml
cypress/integration/author.js
cypress/integration/learn.js
cypress/integration/tag.js
src/pages/learn.js
src/templates/tag.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=605e3117459c5eddf6cb6fe4)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/71e900f/devhub/docsworker-xlarge/march-29-21/)
```
6f1f28b0 DEVHUB-566: Fix Pop-up on Search Results - MongoDB (#749)
e71a93a1 DEVHUB-561: Implement a H1 to all paginated article pages which contains the page number (#736)
eb7532e4 DEVHUB-508: Upgrade General Support to Node 14 (#746)
```

Deploy March 29th, 2021

---

src/components/Literal.js
tests/unit/DefinitionList.test.js
tests/unit/Literal.test.js
tests/unit/__snapshots__/DefinitionList.test.js.snap
tests/unit/__snapshots__/Literal.test.js.snap

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=606366fe459c5eddf6d2ac2a)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/fde59d1/devhub/docsworker-xlarge/march-31-2021/)
```
183f450f DEVHUB-107: Update literal style (#755)
```

Deploy March 31, 2021

---

gatsby-config.js
gatsby-config.prod.js
src/components/dev-hub/feedback/feedback-container.js
src/components/dev-hub/feedback/index.js
src/queries/fragments/feedback.js
src/templates/article.js

[JIRA](https://jira.mongodb.org/browse/DEVHUB-593)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-592/)
This PR pulls in CMS data for questions for the DevHub Feedback project. The next step here will be to use the data and render the questions appropriately. The shape of the data can be seen in `src/queries/fragments/feedback.js`
Each star rating is an entry in the data, with a series of `forms` which represent the series of modals to provide in the UI.

DEVHUB-593: Prepare to use CMS Feedback Questions

---

src/components/dev-hub/series.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60707c78459c5eddf6b20f48)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/fde59d1/devhub/docsworker-xlarge/april-9-21/how-to/attribute-pattern/)
```
3435f3e1 Fix series CSS post emotion 11 (#764)
```

Deploy: Fix series CSS post emotion 11 (#764)

---

src/queries/articles.js
src/utils/setup/create-article-node.js
src/utils/setup/get-time-to-read.js
tests/utils/create-article-node.test.js

(Not for review)
This PR adds the initial logic for a v0 of calculating time to read for an article. This is not used anywhere yet.

Skunkworks: Add Simple TTR at Build Time

---

src/components/dev-hub/card-list.js
src/components/dev-hub/card.js
src/utils/parse-podcasts.js
src/utils/setup/create-tag-page-type.js
src/utils/setup/handle-create-page.js
src/utils/simplify-twitch-response.js
src/utils/simplify-youtube-response.js

No Review
This PR adds TTR to the different content cards. This is just for POC purposes, so code is not going into production at this time.

Add TTR to Content Cards

---

src/components/dev-hub/card-list.js
src/components/dev-hub/card.js

No review
This PR cleans up some elements of TTR on cards.

Misc TTR Clean up

---

src/components/ArticleRating.js
src/components/dev-hub/cms-form.js
src/components/dev-hub/feedback/feedback-container.js
src/components/dev-hub/feedback/helpers/getStarRatingFlow.js
src/components/dev-hub/feedback/index.js
src/templates/article.js

This PR renders one flow for the case in which someone clicks on one star. Let's check how modal windows works. If all changes will work how expected - the next step will be another flow and form submitting.

DEV-HUB-611: Implement modal window and style it

---

src/components/ArticleRating.js
src/components/dev-hub/article-share-footer.js
src/templates/article.js
tests/unit/ArticleRating.test.js
tests/unit/__snapshots__/ArticleRating.test.js.snap

Recreated https://github.com/mongodb/devhub/pull/763

DEVHUB-610: Implement star rating for article page

---

src/queries/rss-feed-article-data.js
src/queries/search-article-rss-data.js
src/utils/setup/serialize-rss-data.js
src/utils/setup/serialize-search-rss-data.js
src/utils/transform-article-strapi-data.js

[Staging RSS feed](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/jordanstapinski/DEVHUB-585-search/rss.xml)
[Staging Search XML](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/jordanstapinski/DEVHUB-585-search/search-rss.xml)
This PR ensures Strapi content shows up in our RSS feed and can be searched

DEVHUB-585: Add Strapi Articles to Search Indexing, RSS Feed

---

src/components/dev-hub/feedback/feedback-form.js
src/components/dev-hub/modal.js

[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/jordanstapinski/DEVHUB-626-1/)
Based on feedback from the design team, here are some of the following changes:
- Swapped the close icon on the modal to use a new icon
- Reduced padding on the modal
- Added some margin to the bottom of the header

DEVHUB-626: Part 1 of Design UAT

---

src/components/dev-hub/feedback/feedback-final-step.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/DEVHUB-626-2/)
This PR continues design asks for the feedback project by changing the color and behavior of the community link at the end.

DEVHUB-626: Part 2 of Design UAT

---

src/components/dev-hub/card.js
src/components/pages/academia/students-educators-details.js

[JIRA](https://jira.mongodb.org/browse/DEVHUB-619)
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-619/)
This PR uses Emotion's `shouldForwardProps` option to filter out props leaking to the DOM.

DEVHUB-619: Use shouldForwardProps for invalid props

---

package-lock.json
package.json
src/components/dev-hub/card.js
src/components/pages/academia/students-educators-details.js
src/utils/parse-podcasts.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60900ca309293ae626f7b876)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25f8cf4/devhub/docsworker-xlarge/may-03-2021/)
[Changelog](https://wiki.corp.mongodb.com/display/DEVREL/Developer+Hub+Release+Notes)
```
44b9fe2b DEVHUB-619: Use shouldForwardProps for invalid props (#790)
8838b84c Add podcast descriptions (#785)
```

Deploy May 3rd 2021

---

gatsby-node.esm.js
src/classes/snooty-article.ts
src/queries/rss-feed-article-data.js
src/queries/search-article-rss-data.js
src/utils/setup/create-article-node.js
src/utils/setup/get-strapi-article-list-from-graphql.js
src/utils/setup/schema-customization.js
src/utils/setup/serialize-rss-data.js
src/utils/setup/serialize-search-rss-data.js

[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/allow-zero-articles/)
This PR handles a case where there are zero Strapi articles and also fixes uses of prefix paths at build time for Snooty articles

Support the case for zero Strapi articles, fix withPrefix use

---

src/utils/transform-article-strapi-data.js

This PR adds some basic defaults so basic Strapi articles won't cause a build to fail in staging

Set defaults for Strapi to avoid failing builds

---

src/classes/strapi-article.ts
src/components/Emphasis.js
src/components/List.js
src/components/Literal.js
src/components/Reference.js
src/components/dev-hub/related-articles.js
src/queries/articles.js
src/utils/setup/schema-customization.js
src/utils/transform-article-strapi-data.js

This PR cleans up prop type use to reduce console errors and turns on related links for articles

Cleanup Proptypes and Enable Related Links

---

src/classes/strapi-article.ts
src/components/Emphasis.js
src/components/Link.js
src/components/Reference.js
src/components/Strong.js
src/utils/find-section-headings.js
src/utils/setup/transform-author-strapi-data.js
src/utils/transform-article-strapi-data.js
tests/unit/__snapshots__/Emphasis.test.js.snap
tests/unit/__snapshots__/Strong.test.js.snap

[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/8b11548/devhub/docsworker-xlarge/may-13-21/)
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=609d6e9ef1f6937450425358)
```
10743db7 Correctly get Strapi preview URLs for social share (#818)
a6b49bf8 Use Component Factory to compose styles (#817)
e224423a Remove unused debug param since signature changed (#815)
f1dfd8ee Don't require author images (#814)
d47464ba DEVHUB-653: UProperly render anchor tags from Strapi (#813)
33e59eb3 DEVHUB-660: Default to H2 and above for TOC (#812)
```

Deploy Misc Strapi Cleanup

---

gatsby-node.esm.js
src/components/dev-hub/card-list.js
src/pages/learn.js
src/utils/setup/create-podcast-pages.js
src/utils/setup/handle-create-learn-page.js
src/utils/setup/handle-create-page.js

This PR adds new logic for podcasts on learn page. Now the click event opens a new page instead of player.

DEVHUB-557: Swap Podcast functionality on Learn Page

---

src/components/ComponentFactory.js
src/components/Table.js
src/components/TableCell.js
src/components/TableRow.js
src/components/dev-hub/card-list.js
src/pages/learn.js

[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/8b11548/devhub/docsworker-xlarge/may-14-21/)
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=609ecba0f1f69374508a9ee6)
```
d8fcdc54 DEVHUB-670: Don't sort by date for search results (#821)
1b70df4e DEVHUB-651: Add Table, TableRow, and TableCell support for Strapi (#820)
```

Deploy (Monday, May 17): Search Sort Bug

---

cypress/integration/video.js

[Integration test for video pages](https://jira.mongodb.org/browse/DEVHUB-671)

DEVHUB-671: Video pages integration test

---

src/components/dev-hub/layout.js
static/opensearch.xml

This PR adds tab searching. [DEVHUB-596](https://jira.mongodb.org/browse/DEVHUB-596)

DEVHUB-596: Tab search

---

src/components/dev-hub/breadcrumb-schema.js
src/components/dev-hub/hero-banner.js
src/components/dev-hub/project-title-area.js
src/components/pages/educators/top-banner.js
src/templates/article.js
src/templates/project.js
tests/unit/BreadcrumbSchema.test.js
tests/unit/__snapshots__/BreadcrumbSchema.test.js.snap
tests/unit/data/BreadcrumbSchema.test.json

This PR adds improvements for breadcrumbs and add CSS truncate effect for long text. [DEVHUB-457](https://jira.mongodb.org/browse/DEVHUB-457)

DEVHUB-457: Breadcrumbs improvements.

---

src/components/dev-hub/breadcrumb-schema.js
src/components/dev-hub/hero-banner.js
src/components/dev-hub/layout.js
src/components/dev-hub/project-title-area.js
src/components/pages/educators/top-banner.js
src/templates/article.js
src/templates/project.js
static/opensearch.xml
tests/unit/BreadcrumbSchema.test.js
tests/unit/__snapshots__/BreadcrumbSchema.test.js.snap
tests/unit/data/BreadcrumbSchema.test.json

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60b130ddf1f693745062bbc8)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/c441a9e/devhub/docsworker-xlarge/may-28-21/)
```
19c1cb2c DEVHUB-457: Breadcrumbs improvements. (#841)
eb6432fb DEVHUB-596: Tab search (#844)
```

Deploy May 28th 2021

---

src/components/dev-hub/layout.js
static/opensearch.xml

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60b646a0f1f6937450792b9a)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/c441a9e/devhub/docsworker-xlarge/june-1-2021/)
```
9b8cc63f DEVHUB-596: Cleanup Title and Link (#848)
```

DEVHUB-596: Cleanup Title and Link (#848)

---

static/opensearch.xml

No staging
This PR fixes the OSD once checked in prod to remove the `&`

DEVHUB-596: Remove & from query params

---

src/components/dev-hub/top-banner.tsx

[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25c77c5/devhub/docsworker-xlarge/strapi/)
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60b66e94f1f6937450833a51)
```
36862d0e DEVHUB-218: (#852)
```

DEVHUB-218: (#852)

---

src/pages/community-champions.js

[JIRA](https://jira.mongodb.org/browse/DEVHUB-711)
Created a new blank page at /community-champions

DEVHUB-711: Construct a Page at /community-champions

---

src/templates/article.js

[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/c441a9e/devhub/docsworker-xlarge/june-15-2021/)
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60c8b8b9f1f69374504dcefd)
```
7055c6e5 SFix safari article overlay (#865)
```

Deploy June 15, 2021

---

src/components/Literal.js
src/templates/article.js
tests/unit/__snapshots__/DefinitionList.test.js.snap

[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/16ac865/devhub/docsworker-xlarge/june-16-21/)
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60ca3d25f1f69374509cd0fe)
```
8282fc69 DEVHUB-689: Wrap link text anywhere (#842)
```

Deploy June 16, 2021

---

gatsby-config.js
gatsby-config.prod-new.js
gatsby-config.prod.js
src/utils/setup/article-rss-feed.js
src/utils/setup/search-rss-feed.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60d4cc9da1eeec1fdc6e8bd2)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/03e261b/devhub/docsworker-xlarge/june-24-2021/)
```
eee4811a DEVHUB-720: Swap site URLs for XML files generated (#879)
```

Deploy June 24, 2021

---

src/components/dev-hub/hero-banner.js
src/pages/community-champions.js

[Staging link](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/sophia.li/update-alt-text/community-champions)

Community Champions - add and update alt text for images

---

src/pages/community-champions.js

[Staging link](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/sophia.li/update-media-queries/community-champions/)
just 2 minor tweaks mike wanted me to make!

Community Champions entry page - update media queries

---

src/components/dev-hub/searchbar/ExpandedSearchbar.js
src/components/dev-hub/searchbar/Searchbar.js

[Job Using Staging Branch](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60ec96eba1eeec1fdc2d2a0b)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/ddfb40a/devhub/docsworker-xlarge/july-13-21/)
Output of `versions.sh`:
```
5525b8b1 DEVHUB-772: Also Update when isFocused changes (#893)
53505f6f DEVHUB-772: Only Listen for Search Keydown When Focused (#888)
```

Deploy July 13, 2021

---

cypress/integration/search.js

This PR adds retries for a flaky Search UI test while we continue to diagnose the root cause to limit CI failures

Add Retries for Search Test

---

cypress/integration/search.js
gatsby-config.js
gatsby-config.prod.js
src/constants.js
src/utils/make-link-internal-if-applicable.js
static/sitemap.xml
tests/utils/make-link-internal-if-applicable.test.js

[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60ef56e8a1eeec1fdcc781e5)
[Staging Site](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/ddfb40a/devhub/docsworker-xlarge/july-15-21/)
```
71743186 [July 15th] DEVHUB-753: Remove Forums from DevHub Sitemap, Update Links (#873)
552a0ead Add Retries for Search Test (#896)
```

Deploy: July 15th 2021 (Forums New Domain)

---

src/pages/community-champions.js

[JIRA](https://jira.mongodb.org/browse/DEVHUB-735)
[Staging link](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/sophia.li/DEVHUB-736/community-champions)
Created the "For the Future" section of the Community Champions entry page.

DEVHUB-736: Entry Page - For the Future

---

pull_request_template.md

This PR adds a PR template which will be used to auto-populate this description field. I added some basic things we seem to include on every PR as well as some additional points of clarification if we need reviews from outside folks.
As always, open to any thoughts on what we can add/remove!

Add PR Template

---

src/components/dev-hub/academia-sign-up-form.js

-   JIRA Ticket N/A (small bug)
-   [Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/academia-form-state/)
-   This PR fixes a bug with the checkbox on the academia form. There was a bug where toggling off the checkbox still resulted in the state for the checkbox showing `on`. We want this to be a boolean.
-   The state for the form should now be correct with true/false for the checkbox values
-   The requirement validation should still work

Fix unchecking the form checkbox

---

src/components/dev-hub/article-schema.js
src/templates/article.js
src/templates/video.tsx
tests/unit/ArticleSchema.test.js
tests/unit/__snapshots__/ArticleSchema.test.js.snap
tests/unit/data/ArticleSchema.test.json

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60feeb73322bd9a61f5c4639)
-   [Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/ddfb40a/devhub/docsworker-xlarge/july-26-21-2/)
-   Releases DEVHUB-781 to master, fixes odd histories on our branches due to squash/merge

Release, Monday July 26th (2nd)

---

src/components/dev-hub/academia-sign-up-form.js
src/components/dev-hub/champion-application-form.js
src/components/dev-hub/community-champion-application.js
src/components/dev-hub/community-champion-form.js
src/components/dev-hub/modal.js
src/components/dev-hub/text-area.js
src/pages/community-champions.js
src/utils/invalid-form-input-messages.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-760)
-   [Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/sophia.li/DEVHUB-760/community-champions/)
-   Created the Champion application form UI and also handled form validation.
- Verify that a modal with the form pops up upon clicking one of the `Apply to Become a Champion` buttons (one is on the hero banner and one is at the very bottom of the entry page - test both!).
* Verify that the form UI closely matches the [mockup](https://www.figma.com/file/2NubIdV3S8OCiXsbqt3LAa/Community-Champions) for both desktop and mobile. Note that text input fields will appear different since we will be migrating to leafy ui components later.
- Also check the UI for the "Success" modal. Since I have not handled …

DEVHUB-760: Champion application form UI

---

gatsby-config.prod-new.js
gatsby-config.prod.js

Fix config typo

---

src/components/dev-hub/academia-sign-up-form.js
src/components/dev-hub/community-champion-form.js
src/utils/devhub-api-stitch.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-761)
-   [Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/sophia.li/DEVHUB-761/community-champions/)
-   This PR handles form submissions and calls the `submitCommunityChampionApplication` Realm function which inserts application responses to the `devhub.community_champion_application_responses` collection. 
Success case:
- Fill out all the fields of the form with valid input, then submit and verify that the "Thank you for applying!" success modal shows up right after. Then, verify that your response was properly inserted into our [collection](https://cloud.mongodb.com/v2/5eb9a4925f91995d7c0e426a#metrics/replicaSet/5ec43e18e19df87d804548cf/explorer/devhub/community_champion_application_responses/find)
Error …

DEVHUB-761: Application Form - Managing State of UI

---

src/components/dev-hub/codeblock.js
src/pages/404.js
src/pages/academia/educators.js
src/pages/code-for-good.js
src/pages/community/events.js
src/pages/community/index.js
src/pages/learn.js
src/utils/determine-correct-leafygreen-language.js
tests/utils/determine-correct-leafygreen-language.test.js

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=610ad0ce382fd7618ee727fe)
-   [Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/cf33d36/devhub/docsworker-xlarge/4-aug-21/)
-   [Release Notes](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/cf33d36/devhub/docsworker-xlarge/4-aug-21/)
-   This PR deploys the following PRs to production:
```
f62bcfa6 DEVHUB-789: Gracefully Handle Unsupported Lanagues in Codeblocks (#922)
87a39230 DEVHUB-518: Resolve Named Export Warnings (#927)
```
-   The warnings implemented do not show in the staging build. This is expected.
-   [ ] Product …

Deploy: August 4th, 2021

---

src/constants.js
tests/utils/make-link-internal-if-applicable.test.js

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=610c2cdb7814dfcacdf02145)
-   [Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/cf33d36/devhub/docsworker-xlarge/05-aug-21/)
-   This PR releases the fix for 404 links to the forums
-   Tests should pass
-   Links to the forums should not 404

Deploy: Aug 5th 2021

---

src/components/dev-hub/podcast-player/player-contols.js
src/templates/podcast.tsx

Devhub 768 podcast pages

---

src/templates/community-champion-profile.js

-   [Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/sophia.li/add-height-width-props/community-champions/nuri-halperin/)
-   adding height and width props to the certificate badge `img` 
-   Inspect the image and verify the two props are there

add height and width props to certificate image

---

src/components/dev-hub/student-spotlight/github-student-pack.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-804)
-   [Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-804/academia/students/)
-   This PR fixes a typo on the students page for student spotlights. (excusive --> exclusive)
-   Check the spelling here has been corrected

DEVHUB-804: Fix typo on student spotlight page

---

src/classes/strapi-article-series.ts
src/components/dev-hub/student-spotlight/github-student-pack.js
src/utils/setup/is-strapi-article.js

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=611c28927dcf01293067772c)
-   [Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/3a801bb/devhub/docsworker-xlarge/18-aug-2021/)
-   Deploys the following PRs to PROD
```
b0729b2f DEVHUB-801: Filter Draft Series Articles from Prod Platform Builds (#944)
91bef796 DEVHUB-804: Fix typo on student spotlight page (#948)
```
-   Series should continue to work as expected
-   The linked typo should be fixed
- …

Deploy Wednesday 18 August 2021

---

src/components/dev-hub/blog-post-title-area.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-807)
-   [Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-807/how-to/document-enrichment-and-schema-updates/)
-   This PR fixes a flexbox bug where large tags cause the text area with dates to shrink and flow onto another line. The solution was to add `flex-shrink` and set it to 0 so this area never decreases in size.
-   Check out this article and compare to prod. Check out other articles to ensure this looks good

DEVHUB-807: Fix split date text on desktop

---

src/components/Break.js
src/components/ComponentFactory.js
src/components/Delete.js
src/utils/determine-correct-leafygreen-language.js
src/utils/query-string.js

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61310b287dcf012930075744)
-   [Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/7386a2d/devhub/docsworker-xlarge/sept-2-21-second/)
-   Releases the following PRs:
```
6aa4a417 Handle plus symbol in decodeURI (#961)
20a6b0de DEVHUB-583: Fix Directive Warnings (Break, Delete, Golang) (#959)
```

Deploy DEVHUB-583, Plus Symbol in DecodeURI

---

environments/prod.yaml

DEVHUB-819 fixing prod url

---

environments/prod.yaml
gatsby-node.esm.js
src/components/pages/home/hero.js
src/components/pages/home/twitch-feature.js
src/utils/setup/handle-create-home-page.js

DEVHUB-891 commenting snooty article and feature articles

---

.drone.yml

DEVHUB-891 changing mode to preview

---

.drone.yml

DEVHUB-819 testing push to staging branch

---

.drone.yml

DEVHUB-819 testing push by branch

---

.drone.yml
Dockerfile

Devhub 819 stg

---

cypress/integration/community-champions/entry.js
package-lock.json
package.json
src/components/dev-hub/consistent-nav.js
src/pages/learn.js

-   [Staging Site](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/7386a2d/devhub/docsworker-xlarge/release-sep-21/)
-   [Staging Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6149dc89c608bec57fdb8370)
```
05376cbc DEVHUB-849: Accept lowercase content filters (#980)
ffb194d0 DEVHUB-850: Fix Dep Error on Champions Modal (#982)
6a364bfd DEVHUB-848: Use grid sizing to prevent jumpy anchor link (#981)
```
-   Automated testing should pass
-   [X] Release Note Update (only for …

Release: September 21, 2021

---

Dockerfile
environments/prod.yaml
environments/staging.yaml

-   Adds .npmrc to add docker file to point to our internal repo.

DEVHUB-819 Adding npmrc for docker file

---

.drone.yml

-   Going off of https://docs.drone.io/plugins/popular/docker/ and other options in Slack

DEVHUB-819: Use build_args_from_env

---

.drone.yml

Add env in drone as well

---

src/components/pages/academia/students-educators-details.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-857)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-857/academia/)
-   As in the linked ticket, we update two pieces of copy relating to an updated policy change for Academia. This is purely a copy change.
-   Visit the staging link and observe the updated copy
-   [X] Product Review

DEVHUB-857: Update copy for Academia Student benefits

---

gatsby-node.esm.js
src/components/pages/academia/students-educators-details.js

Friday first thing deploy due to DEVHUB-857 requirement.
-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6155fe258670bd273183c245)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/7386a2d/devhub/docsworker-xlarge/october-1-21/)
```
2367542b Await snooty image download (#993)
4721ec04 DEVHUB-857: Update copy for Academia Student benefits (#991)
```

Deploy: October 1 2021

---

cypress/integration/community.js
cypress/integration/home.js
src/components/dev-hub/page-helmet.js
src/components/pages/home/events-feature.js
src/constants.js
src/pages/community/events.js
src/pages/community/index.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-898)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-898/)
-   This PR replaces some links that were going to /community/events with a link specified in the ticket. The redirects are done in S3/CMS
-   Automated tests have been updated
-   Links should open properly
-   [x] Product Review

DEVHUB-898: Point to events/webinars page on .com

---

cypress/integration/community.js
cypress/integration/home.js
src/components/dev-hub/page-helmet.js
src/components/pages/home/events-feature.js
src/constants.js
src/pages/community/events.js
src/pages/community/index.js

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61899696c13055282d200301)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/7386a2d/devhub/docsworker-xlarge/nov-9-21/)
```
2121a11d DEVHUB-898: Point to events/webinars page on .com (#1011)
```
This will be accompanied by S3 redirects for the URLs specified in the ticket
-   [ ] Release Note …

DEVHUB-898: Point to events/webinars page on .com (#1011)

---

src/components/dev-hub/SEO.js
src/queries/articles.js
src/utils/setup/schema-customization.js
src/utils/transform-article-strapi-data.js

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6192cf6a5314b0809fbbb4cf)
-   [Staging Site](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/36de2b8/devhub/docsworker-xlarge/nov-16-21-deploy/)
```
281afca2 Add twitter card to schema
409f484d DEVHUB-707: Use twitter_card field (#1009)
```

Deploy: November 16th 2021

---

src/utils/setup/parse-markdown-to-ast.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-650)
-   This PR adds support for one last Snooty directive, Tabs ([like this one](https://www.mongodb.com/developer/article/realm-database-cascading-deletes/)) using the common directive proposal. Usage is like:
```
::::tabs
:::tab[]{tabid="java"}
java code
:::
:::tab[]{tabid="golang"}
golang code
:::
::::
```

DEVHUB-650: Add support for tabs/tab directive

---

environments/prod.yaml
environments/staging.yaml

-   Added these SSO environment variables in Kanopy and now want to link from the environment YAML files
-   Double check these are added as expected

Add drone config for env variables

---

src/components/pages/academia/students-educators-details.js
src/components/pages/educators/program-benefits.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-875)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-875/academia/)
-   This PR changes Academia Educators copy as requested in the JIRA ticket. I am awaiting a design question from Mike based on a UI change as a result of shorter copy.
-   [X] Product Review (Academia)
-   [X] Design Review

DEVHUB-875: Update Educators Copy

---

src/queries/articles.js
src/utils/setup/schema-customization.js
src/utils/transform-article-strapi-data.js

-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-492)
-   In conjunction with the [CMS PR](https://github.com/10gen/devhub-cms/pull/82), this PR pulls these fields in on the front-end
-   Check that the fields being pulled in here are reasonable

DEVHUB-492: Pull in missing social share data

---

src/components/dev-hub/raw-html.js

-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6197bbf75314b0809fe5d0c1)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/ac1a74d/devhub/docsworker-xlarge/deploy-nov-20-21/)
```
85052b8b DEVHUB-321: Add Support for Specific HTML Embeds (#984)
```

Deploy: November 19 2021

---

src/utils/setup/handle-create-home-page.js

This addresses the issue of preview server being down.

DEVHUB-926 Resolving featured articles issue with preview server

---

src/classes/podcast.ts
src/classes/twitch-video.ts
src/classes/youtube-video.ts
src/components/dev-hub/text.js
src/templates/tag.js
src/utils/get-isodate.js
tests/unit/__snapshots__/Heading.test.js.snap
tests/unit/__snapshots__/ListTable.test.js.snap

-   https://jira.mongodb.org/browse/DEVHUB-941
-   http://developer-hub-stage.s3-website-us-east-1.amazonaws.com/CI/devhub/harika.kotipalli/DEVHUB-939/
- Tag pages should be sorted
-   Tag pages will be sorted by update date or published date

DEVHUB-939 Adding sort to the tag card lists

---

.github/workflows/devhub-ci-test.yaml
gatsby-node.esm.js
src/utils/get-metadata.js

fixes the issue with snooty reload

Devhub 939

---

src/utils/setup/parse-markdown-to-ast.js

accepts parameters start date and end date for youtube directive in strapi.

DEVHUB-944 Fixing youtube start data
