- src/components/dev-hub/layout.js
Saw some overflow for images in the article
> cap images to 100% width by default

- src/components/dev-hub/button.js
- src/components/dev-hub/codeblock.js
- src/components/dev-hub/copy-button.js
This PR does two things for the codeblock:
- Writers are trying to put in language options that don't match with the leafygreen codeblock languages (i.e., writers put in `csharp` when leafygreen wants `csp`). Sue is going to determine a mapping from writer language to leafygreen language and then we can add that in. For now, setting the language to `auto` resolves this.
- Adds a prop to the `Button` to disable the arrow
> Codeblock Button and Language Changes

- src/components/Link.js
Links are sent as references, so I'm using the existing link component to forward to our styled link component
> reference dev-hub link component

- src/components/dev-hub/blog-post-title-area.js
- src/components/dev-hub/blog-tag-list.js
- src/components/dev-hub/card.js
- src/pages/storybook.js
- src/templates/article.js
- src/utils/get-tag-links-from-meta.js
- src/utils/map-tag-type-to-url.js
This PR:
- Removes the hardcoding on breadcrumbs and will add another breadcrumb if `meta.type` is supplied, with a link to that page assuming it is going to be `/tag/${meta.type}` for now.
- Removes products and languages from the header tag list and adds `/tag` to the link so they also link to the expected page
> Article Hero Cleanup

- src/components/dev-hub/blog-post-title-area.js
- src/components/dev-hub/byline-block.js
- src/pages/storybook.js
- src/templates/article.js
We were not getting the author's image previously. Sophie and I worked ou this new structure for the author in article metadata:
```
// meta object
{
author:
{
name: 'Author Name',
image: '/path/to/image.jpg'
},
...rest
}
```
This PR changes `article.js` and child components to expect author as an object.
> Support Author as Object Type

- src/components/dev-hub/filter-bar.js
- src/pages/learn.js
This PR adds the 'All' option to the filter dropdowns. For now, I did not put a number next the all the option because in order to get that value i would have to make the call for all articles (regardless of the filter) and then count them.
I personally think it looks okay as is, but If we want a number next to all, I'm thinking we should add that to the stitch function that returns the other values.
> add all option for filter

- gatsby-node.js
- src/components/dev-hub/related-articles.js
- src/templates/article.js
This PR is not to be merged yet, it is a WIP for how I want to tackle related articles.
We get `meta.related` back, which (once the parser is updated), will return an array of nodes (not strings as it is with some test data). These nodes could be links to other articles or external based on the wiki.
We don't get the images for internal articles back with this node, so this WIP suggests adding it in `createPages` if it exists, and using a placeholder otherwise (still need to move the placeholder into createPages). This way we can safely add the image to the related node and reference it every time.
Curious if this approach is best? I left samples of the internal reference doc nodes in `article.js`. I don't think Role Docs would be useful here?
> Related Internal Articles

- src/components/dev-hub/blog-post-title-area.js
- src/templates/article.js
This PR adds support for the "Updated Date" field for an article. I need to double check with Sophie the exact name of this field.
On extremely small screens, let's stack the text to avoid odd wraps.
> Article Updated Date

- src/components/dev-hub/link.js
I'm not sure if this breaks any assumptions we had about link size somewhere, but by default links should be the same size as their surrounding text
> inherit parent font size for links

- src/components/dev-hub/blog-post-title-area.js
Marketing wants the updated date (if available) to come first. This PR swaps the existing order.
Not sure if they also want "Published" before the published date as well?
> Swap updated and publish dates for articles

- gatsby-node.js
- src/components/dev-hub/layout.js
- src/templates/tag.js
This PR adds logic to pull and generate pages for tags and tag-like things (authors, languages, products, and types).
The data is passed to the `tag.js` template in `context`.
~Still WIP, trying to clean up unnecessary iteration, but happy for any feedback too.~
> Tag Page Routes

- src/components/Literal.js
This PR fixes literal values extending out of the defined width to avoid breaking words. We want to break the word to provide a consistent max width.
Before:
After:
> Add overflow wrap to literal values

- src/components/dev-hub/notification.js
- src/pages/index.js
- src/utils/request.js
- src/utils/use-twitch-api.js
If the mongodb channel is streaming we'll return that data otherwise we'll check for the last recorded video. That will potentially be used as the Twitch feature on the homepage.
I think removing the error and pending state would be more efficient while we're not using them, but we can comment them out when enable the API calls before launch if needed.
> check for streams and videos

- gatsby-node.js
- src/components/dev-hub/byline-block.js
- src/templates/article.js
- src/utils/get-tag-page-uri-component.js
- src/utils/map-tag-type-to-url.js
This PR fixes encodeURI issues with Gatsby by instead replacing non-alphanumeric characters in a url with dashes, so:
mongo 4.4 --> mongo-4-4
.net --> -net
c# --> c-
etc.
> Replace encodeURI and non-alphanum chars with regex check

- src/components/dev-hub/byline-block.js
- src/templates/article.js
The default author images were accidentally being fed into `withPrefix`, which prevented them from being used properly (since we don't need a prefix for the default image here).
This PR adds a case to check if we are using the default image before using the `withPrefix` function.
> Render default image without withPrefix if no image exists

- src/components/RefRole.js
- src/components/Reference.js
I had some confusion on the difference between RefRole and Reference
RefRole is used for on page anchors and inter-document linking. Reference is basically any link.
We'll handle all links with an http/https prefix as external and open in a new tab for now. We can be smarter about this in the future
> new tab for external links

- src/components/dev-hub/related-articles.js
This PR adds logic to support external links on related articles. It [looks like the writers are trying to do so](https://github.com/ljhaywar/devhub-content/blob/node-changestreams/source/quickstart/nodejs-change-streams-triggers.txt) at this point.
The type here is a `Reference`, so I went off the structure from the `Reference` component to get the needed fields.
> Reference External Articles

- gatsby-node.js
- src/components/dev-hub/series.js
- src/templates/article.js
- src/utils/get-series-articles.js
- tests/unit/get-series-articles.test.js
This PR supports the top-level TOML means of defining a series by adding some build-time logic to the `createPages` step. Given data that can look like:
```
const allSeries = {
'test-articles': [
'article/article',
'quickstart/nodejs-how-to-connect-to-your-database',
],
'test-articles-two': [
'article/active-active-application-architectures-with-mongodb',
'quickstart/nodejs-how-to-connect-to-your-database',
'how-to/working-with-mongodb-stitch-through-the-mongo-shell',
],
};
```
this PR handles attaching relevant data about each series an article is in to its context at build-time.
I also added support for articles in multiple series, and updated the stylings for series a bit to match updated styles.
> Handle top level TOML series definitions

- src/components/dev-hub/author-image.js
- src/components/dev-hub/byline-block.js
- src/templates/tag.js
Sophie has updated her article repo, so re-creating pages will now show author images! This also has been updated in the parser and should be fixed soon for everyone in new builds.
This PR adds some styling support for the author images and refactors the author image work from the Byline Block and Tag pages out into a reusable component.
> Use background for author images and refactor into component

- src/components/dev-hub/global-nav.js
The nav on mobile was wrapping onto a newline because the text was 18pt. I dropped it to 14pt and it does not wrap.
This PR:
Before:
> Drop text size for nav on mobile

- src/components/RefRole.js
Should fix anchor links within articles. We don't receive `fileid`s so we were point to the root of the site.
> check for fileid and use href

- src/components/dev-hub/related-articles.js
This PR adds some styling improvements for related articles (specifically padding and handling >4 related articles).
- Added `flex-wrap` to keep width consistent and move more cards to new rows
- Fixed padding/margin to properly have card hover state
Because of flex-wrapping and a fixed width, I decided to just switch to a `column` flex under the large size. Otherwise cards were awkwardly flushed left.
> Add Related Article Flex-Wrap

- src/components/SubstitutionReference.js
Duplicates https://github.com/mongodb/snooty/pull/159.
We recently introduced changes to the AST around substitutions ([DOCSPLAT-114](https://jira.mongodb.org/browse/DOCSPLAT-114)). This PR updates the front-end to accept this new schema. Backwards compatible with previous parser versions!
> Update substitution reference component to match new AST

- gatsby-node.js
- src/templates/article.js
This PR removes some noisy logs from builds to help reduce clutter.
> Remove old console logs on builds

- gatsby-node.js
- src/pages/learn.js
This PR adds some flexibility to the featured articles on the learn page.
- We define three "featured articles" in `gatsby-node` in order of precedence on the learn page
- We parse the articles in `learn.js`
> Add flexible featured article support

- src/hooks/use-event-data.js
Saw that the Seattle.local was canceled so removing it from the events data.
> Remove seattle.local due to cancellation

- src/components/dev-hub/card.js
- src/components/dev-hub/hero-banner.js
-the hero images are background-images so we can't really add alt tags to those
-this adds blank alt tags for the article cards and hero on mobile for now
> Add alt tags to article and hero images

- src/components/dev-hub/article-share-footer.js
This PR adds the ability to share an article on LinkedIn (similar to with Twitter and Facebook):
> Add linkedin share for articles

- gatsby-node.js
This PR fixes the blank article on the learn page. What happened is we were getting data from stitch that looked like:
```
{ _id: 'some id',
query_fields: {
slug: '/'
// no other fields
}
}
```
While this data should be removed from stitch, we can also filter it out at build time. No learn page article should link to the home page.
> Remove erroneous article data from learn page

- src/components/dev-hub/card.js
- src/pages/index.js
- src/pages/storybook.js
Could use a hand checking for any places that still use children instead of title where appropriate. Think I caught all the cases.
We should use title for text only titles and only pass children for things like the twitch feature.
This also bumps the featured home page articles to 3 lines which is different than the design, but prevent the cutoff on most of the articles.
> move title

- gatsby-node.js
- src/components/dev-hub/filter-bar.js
- src/components/dev-hub/select.js
- src/pages/learn.js
This PR adds build-time logic to compute filtering values for the learn page filters. Specifically, now:
- Choosing a filter dynamically updates the other filter to show options where at least one article exists.
- Choosing filters dynamically changes the number shown available in the other filter.
- **Choosing both filters removes count numbers from the filters** (keeping numbers here did not make sense).
Please give this a try locally and see if anything is wonky!
The logic is a bit odd but I think this best supports how we want to use the filters. I chose to represent the filters like so:
Where each value loooks something like (here for `languages`):
> Filter Without Stitch, Dynamically Change Counts

- src/hooks/use-event-data.js
The community page was not rendering with an `events.slice` error. This seemed to be due to some changes on the events API which now give us a successful response.
This PR adds .json to that response to parse the returned events API data.
> Parse events API data as JSON

- src/pages/index.js
This PR switches the "watch" button on the homepage to open a modal to play a video in-site instead of linking out.
> Open twitch modal on homepage instead of link out

- src/utils/use-twitch-api.js
This PR resolves the undefined URL issue for the live notification on the home page. We did not get a url from twitch on the stream, so here we just add the channel url in.
> Add Twitch URL to Home Page Notification

- src/components/dev-hub/video-embed.js
Looks like we had to explicitly pass the video_id as an option. Many of the cors errors went away but there are still a couple cors warnings. The video in the modal should work now though and clicking on the `twitch` icon also links to the correct video as well. 
Although the video works I'm not sure how concerned we should be about the remaining cors warnings. Let me know if you all can view the live video as well!
> Pass twitch video_id to options for video player

- src/components/dev-hub/filter-bar.js
- src/pages/learn.js
This PR addresses the following design concerns for the devhub:
- increase space between filter bar and article grid ( 20px;)
- make sure 'all articles' and 'filter by' are vertically center aligned
- round the corner on the learn page hero graphic to match card images
> Design Improvements (Part 1)

- src/components/List.js
- src/components/ListItem.js
This PR flushes `li` text next to the bullet for a `ul`.
> Prevent ul text from wrapping under bullet

- src/components/dev-hub/copy-button.js
This PR fixes some alignment and padding issues with the copy button on codeblocks to address design concerns:
> Align copy icon and text on copy button

- src/templates/tag.js
This PR adds a `noindex` meta to the tag template pages re: a seo team request.
[Implementation Guide](https://support.google.com/webmasters/answer/93710?hl=en)
> Add noindex head meta to tag template pages

- src/components/dev-hub/button.js
This PR removes the slide-out hover state from secondary buttons, but keeps the existing border change on hover.
There is a primary button with the hover issue on the community page, but not sure how we would like to add a border to it. We may need a design for border, etc to remove the slide-out from primary buttons as well.
> Remove hover from secondary buttons

- src/templates/article.js
This PR fixes article dates being shown one day earlier than they should be (for example, an article could be published on August 10th and show August 9th).
What was happening was we were using `toLocaleString` on a date object that was being interpreted as UTC, without specifying 'UTC' as the timezone option in `toLocaleString` (we were using the browser's timezone).
Before:
(The first date is the date the article was published, the second date was after running the date through the `createDateObject` helper, and the third was the return value of `toDateString` without the 'UTC' tz declared in options being passed).
After:
I pulled the hour and minutes out, but wanted to show for effect.
> Fix article dates off by one day

- src/pages/index.js
This PR fixes varying widths for featured articles on the home page specifically.
There was an issue with widths varying on Firefox.
> Add width constraint for home page featured cards

- gatsby-node.js
This PR solves odd phantom data in the `learn` page.
What was happening is we were getting data from Stitch for articles that were oddly misshaped (see items 22 and 23):
This PR adds filtering to look for additional fields before handing data off to the learn page. We were already doing this for `/` cards.
> Add more restrictive phantom data filtering

- src/components/dev-hub/blog-tag-list.js
- src/utils/get-tag-links-from-meta.js
This PR caps the number of displayed badges in an expanded `BadgeList` at 5, and also re-orders the priority of badges to first show products, then languages, then tags.
> Cap Badge List Size, Reorder Badge Priority

- src/components/dev-hub/article-share-footer.js
- src/components/dev-hub/share-menu.js
- src/templates/article.js
- src/utils/get-article-share-links.js
This PR addresses [DEVHUB-66](https://jira.mongodb.org/browse/DEVHUB-66) by adding some detailed Tweet text to the auto-populated Tweet when sharing an article. The new copy looks like the following:
I also refactored the URLs between the article share footer and share tooltip so future copy changes can be easier. I also asked about updating copy for other Social Media choices as well, no responses yet there.
> Update Twitter Share Text, Refactor Share URLs

- gatsby-config.js
- gatsby-config.prod.js
- src/templates/tag.js
This is for [DEVHUB-69](https://jira.mongodb.org/browse/DEVHUB-69). This PR excludes the tag pages from the sitemap generation.
I used to [`exclude` option](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/#options) on the sitemap plugin. This needs a production environment to test and I don't have gatsby build figured out yet, but seems to be what will do the trick.
> Exclude tag pages from sitemap

- src/pages/index.js
On mobile the Twitch video on the home page is very tiny. Specifying the width to be 100% fixes this issue and allows users to see the video on mobile.
Before:
After:
> Fix Twitch Video Size on Mobile Home Page

- src/pages/learn.js
This PR adds some mobile styling logic to remove the right border for the featured article on the learn page while on mobile. This allows the article to span the full with and be centered appropriately.
Before:
After:
> Clean featured article style on mobile learn page

- gatsby-node.js
- package-lock.json
- package.json
- src/build-constants.js
- src/utils/setup/create-tag-page-type.js
- src/utils/setup/on-create-page.js
This PR adds the ability to accept new arrays in the content repo's top-level [snooty.toml](https://github.com/mongodb/devhub-content/blob/master/snooty.toml) file as such:
```
[featured_articles]
"homePage" = ['path/to/article', ...]
"learnPage" = ['path/to/article', ...]
```
which allows the content team to dynamically change featured articles on the home and learn pages.
This PR. is just the changes to `gatsby-node` to pull this. data in and pass to the home/learn pages. A following PR ( #245 ) will make the change on the home page to show dynamic featured articles.
> Support toml Featured Articles, Refactor gatsby-node

- lint-staged.config.js
- package.json
- preview-start.js
- src/components/dev-hub/controlled-tooltip.js
- src/components/dev-hub/event-list.js
- src/components/dev-hub/global-nav.js
- src/components/dev-hub/gradient-image.js
- src/pages/index.js
- tests/unit/use-event-data.test.js
Now that `npm test` works again, this PR enables linting and testing on commits (similar to with university) using husky/lint-staged.
After enabling this, there were some lint errors to handle, so these were taken care of as well.
> Add pre-commit hooks for linting/testing

- src/components/ComponentFactory.js
- src/components/dev-hub/chart.js
- src/components/dev-hub/stories/chart.stories.mdx
This PR adds support for embedded charts in articles. Sophie is adding the support to articles today, but the props to be passed to this component resemble the following:
```
nodeData={{
options: {
id: '6f921f0c-a1ee-4106-839c-412fad3c64e7',
autorefresh: 3600,
align: 'left',
width: 760,
height: 570,
url: 'https://charts.mongodb.com/charts-coronavirus-lwlvn',
},
}}
```
> Add Embedded Chart Support

- src/components/dev-hub/series.js
Had feedback that the ellipsis can be confusing for certain series, so updated the article titles to wrap
> let titles wrap

- src/components/dev-hub/blog-post-title-area.js
- src/components/dev-hub/byline-block.js
- src/templates/article.js
_This PR must merge in sync with a docs platform autobuilder change_
This PR does two things:
- Allows support of the `author` value in `meta` to be an array of author objects, instead of a single author object.
- Adds styling to support articles with multiple authors at once:
One author:
Two: 
Three:
> Support Multiple Authors (and Authors as Array)

- src/components/dev-hub/card-list.js
- src/components/dev-hub/codeblock.js
- src/components/dev-hub/select.js
- src/pages/learn.js
This PR adds a few more design improvements:
1. Changes codeblock border radius to 8px from 10px
2. Bumps the bottom padding on the learn page filter bar to 20px
3. Flips the arrowhead on filters for open and close
4. Adds margin to the "has more" button in the card list component.
> Misc Design Improvements

- gatsby-node.js
- src/utils/setup/on-create-page.js
This PR updates the logic for supporting featured articles to use the `pageGroups` field from Stitch's metadata. We still have a fallback case for if this has not been implemented yet by the authors or the parser.
Instead of diving into data from the `getMetadata` hook, we store the values from a single stitch call in gatsby-node and pass them through.
This will conflict with the refactor work, but I expect this PR to go in first, so I will handle conflicts on the refactor branch.
> Support Featured Articles in pageGroups

- jest.config.js
- src/utils/setup/create-tag-page-type.js
- src/utils/setup/on-create-page.js
- tests/utils/find-articles-from-slugs.test.js
- tests/utils/get-featured-articles.test.js
- tests/utils/get-learn-page-filters.test.js
This PR does a few things:
- Refactors logic to generate the filters for the learn page to not repeatedly call stitch. Instead we use the article objects we have to update language/product values.
- Cleans up var names from a prior PR
- Adds testing for both generating the filters and getting featured articles
- Adds a `utils` subdirectory in `/tests` with a simple config (since this is mainly for js helpers, not components).
> Refactor and Test onCreatePage

- src/templates/article.js
Our CDN provider redirects pages to the trailing slash version, so we should use that in our links.
> add trailing slash to articleUrl

- gatsby-node.js
- src/utils/setup/construct-db-filter.js
- src/utils/setup/save-asset-files.js
- tests/utils/construct-db-filter.test.js
This PR pulls three more helper functions out of gatsby node, and adds testing for `constructDBFilter`. `saveAssetFiles` is a bit more difficult to test since it involves file I/O, so I left that out.
> Pull saveAssetFiles, constructDbFilter Out of gatsby-node

- src/utils/setup/on-create-page.js
- tests/utils/find-articles-from-slugs.test.js
This PR allows the incoming featured articles from the parser to have an **optional** leading slash, where before it was mandatory.
> Account for possible no leading slash in passed data

- src/components/dev-hub/chart.js
- src/components/dev-hub/stories/chart.stories.mdx
Both themese get a `devWhite` border, but the light theme also gets a white background in order to legibly render the text
Light theme before:
Light theme after:
Dark theme:
> add border and background for charts

- src/components/dev-hub/event-list.js
- src/hooks/use-event-data.js
- src/pages/community/events.js
The community index page jumps a bit because it loads data from the events API. I noticed the community index page was missing a loading state, so I added it to the `useEventData` hook and copied the simple loading state from the events page into the `EventsListPreview` component
> Add loading state to events hook

- src/components/dev-hub/global-footer.js
- src/components/dev-hub/global-nav.js
- src/components/dev-hub/layout.js
This PR updates the page layout to support a full-width nav and footer. The main logical change was moving `max-width` related info out of the global wrapper and into the nav, main, and footer, and constraining child elements to it.
The nav/footer changes are pretty similar in this way.
Other pages should look normal, I checked on Chrome/Firefox but some extra poking around the different pages just to confirm this would be great!
I also bumped the hover state color for the nav by request.
Dan is currently taking a look, but any changes forthcoming would likely be minor.
> Full-width Nav and Footer

- gatsby-node.js
- src/utils/setup/init-stich.js
This PR starts some work on abstracting our data source (stitch) out of the gatsby node APIs. Here we just move the stitch setup into its own helper function and clean up the promise logic in it.
> Move Stitch Initialization to utils

- versions.sh
This PR adds a versions.sh script like we have for mitx to check staging against master. We can use this for deploys to the master branch in the future.
If you want to try locally, you will need to run `chmod 777 ./versions.sh` first to give execution permissions. There also isn't anything on staging not on master right now.
> Add versions.sh Script

- package-lock.json
- src/components/dev-hub/SEO.js
- src/templates/article.js
[[JIRA](https://jira.mongodb.org/browse/DOP-930)] Requirements:
- If `:canonical-href: https://example.com` is specified for a page (on line 2, below `:template: devhub-article`), use this value as the page's canonical URL
- Otherwise, use the page's actual URL
> DOP-930: Add support for canonical-href option

- src/templates/article.js
This PR cleans up some twitter SEO logic, by just removing the `twitter` directive from the Article `contentNodesMap` and just checking the `childNodes` straight from the passed in data.
This allows us to remove the splice operation which was removing `twitter` from the contentNodes.
> Pull twitter meta from childNodes directly

- versions.sh
The versions script was using `MASTER` instead of `PROD` for the branch alias, so it was not picking up the right branch to check
> Fix MASTER to PROD for versions script

- gatsby-node.js
- src/utils/setup/postprocess-document.js
- tests/utils/postprocess-document.test.js
This PR moves operations relating to postprocessing incoming documents from our data store (stitch) to a helper method with tests.
Doing so helps us more align with Gatsby API methodology by moving `onCreateNode` related processes to one place.
I also removed the unused `IMAGE_FILES` object.
> Extract Document Postprocessing

- src/components/dev-hub/global-nav.js
Dan has asked for the following changes to the nav:
- Remove hover/active states from the logo for home (existing convention should be enough for users to know it is clickable)
- Shrinks the size of the nav to 58px and 2px for the bar underneath
- Switches the hover/active backgrounds to use 40% opacity
Staging:
This PR:
Closer look at hover/active:
> Nav hover/active states, smaller font and height

- gatsby-node.js
- src/utils/setup/validate-env-variables.js
- tests/utils/validate-env-variables.test.js
I'm starting to refactor pieces of `gatsby-node` so we better match pieces of the Gatsby Node API based on what each Node API method is doing.
This piece moves some environment validation logic from the `sourceNodes` step of the lifecycle to the `onPreBootstrap` part of the lifecycle, because it is a better fit here. `sourceNodes` should simply be about pulling in data from any APIs, not validating env variables. `onPreBootstrap` runs earlier in the process and is for checking options and requirements.
As for the env validation itself, I decluttered an unnecessary return from it and instead just throw an error right in the function to abstract it from `gatsby-node`. I also added a quick test.
> Move env validation into onPreBootstrap part of the lifecycle

- gatsby-node.js
- src/utils/setup/get-related-pages-with-images.js
- tests/utils/get-related-pages-with-images.test.js
Continuing with cleaning up `gatsby-node`, this PR moves a helper for related images out of `gatsby-node` and adds a test for it.
At this point `gatsby-node` just contains implementations of the Gatsby Node API methods, which is much cleaner!
> Move related pages helper out of gatsby node

- src/utils/setup/save-asset-files.js
The `saveAssetFiles` function had a concurrency issue. We were using the `fsPromises` API, which gives us the ability to query the filesystem using Promises, however we were not properly blocking for these queries to complete.
This PR uses `fsPromises` properly and blocks for both creating a static directory and writing a static file. It also lets us remove `mkdirp` (which was way outdated) because `fs.mkdir` with `{recursive: true}` is identical, so it is much easier to see what is going on here.
I also noticed `gatsby develop` did not get killed mid-build after making this change.
> Use fs Promises for asset handling

- gatsby-node.js
- src/utils/setup/create-article-page.js
- tests/utils/create-article-page.test.js
This PR simply moves the logic for creating an article page into another file and adding a few tests for it (things like properly adding series, related articles, etc.).
> Extract "Create Page" logic and Test

- gatsby-node.js
- src/utils/setup/create-asset-nodes.js
- src/utils/setup/postprocess-document.js
- src/utils/setup/save-asset-file.js
- src/utils/setup/save-asset-files.js
- tests/utils/create-asset-nodes.test.js
- tests/utils/postprocess-document.test.js
Now that we have broken up pieces of gatsby-node, we can begin to optimize pieces of the build process by leveraging Gatsby's caching.
This PR optimizes writes to disk on repeated builds for static assets (images, etc.) and cuts build time by about 33% (about 4 seconds) on a repeated build (a build where the cache has already been populated).
What happens on a first build is the `createNode` method writes a new node to the cache which stores the asset ID in cached files. On a repeated build, we just use the cache instead of making a new node, therefore we do not call the `onCreateNode` handler and avoid writing out to disk.
I cleared my local `static` folder and re-ran the build. I didn't notice any missing assets.
> Cache static assets to accelerate repeated builds

- cypress/integration/home.js
- cypress/support/commands.js
- src/components/dev-hub/card.js
- src/components/dev-hub/modal.js
- src/pages/index.js
This PR adds Cypress Integration testing to the home page. Right now, we can locally run these commands in Chrome, Edge, and Firefox after starting a development server.
I added checks for the following home page pieces:
- Featured Articles render (between 1 and 4) with images and refs to articles
- Learn MongoDB button links to learn page
- Twitch content renders with a thumbnail and pops open the content modal
- Events link has the expected href
We don't need specific data for these tests, since I just check the structure of components and props exist
> Add cypress testing for the home page

- src/components/dev-hub/event-list.js
- src/hooks/use-event-data.js
- src/pages/community/events.js
I noticed components using the `useEventData` hook were no longer using the url param supplied after refactoring events to use multiple sources. 
This PR simply removes references to that argument from caller components and the hook, because `fetchEventData` now has that url contained in its file.
> Remove unused url arg from useEventData

- cypress/fixtures/eventData.json
- cypress/fixtures/liveEventData.json
- cypress/integration/community.js
- cypress/support/commands.js
- src/components/dev-hub/events.js
This PR adds new integration testing for the `/community` page.
Since we might not want to continuously hit the events APIs, I was able to [mock them through cypress](https://docs.cypress.io/guides/guides/network-requests.html#Testing-Strategies). 
Interestingly enough, cypress can't mock `fetch`, so there are [some workarounds](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window-fetch#readme) they recommend to do so (by deleting fetch on navigating to that page).
I added testing for the following pieces:
- mock a www.mongodb.com event API response and check the event object created is correct (with external link)
- mock a live.mongodb.com event API response and check the event object created is correct (with external link)
- check the "see …
> Add Integration Testing for the Community Page

- package-lock.json
- package.json
- src/components/dev-hub/codeblock.js
This PR upgrades the leafy codeblock to v3.4.3. Additionally I made the following tweaks:
- The codeblock README lists `csp` as a valid shorthand for csharp, but it actually expects `cs`. I singled this case out in the component language logic.
- Added the `copyable={false}` prop
- Cleaned up borders around the code component
> Upgrade leafy codeblock to 3.4.3

- src/components/dev-hub/codeblock.js
I thought I had added this into the codeblock dep update but it looks like I missed it.
This PR updates the border on the codeblock to be uniform throughout:
> Fix codeblock border

- gatsby-config.js
- gatsby-config.prod.js
- package-lock.json
- package.json
- src/queries/rss-feed-article-data.js
- src/queries/site-url.js
- src/utils/setup/create-article-node.js
- src/utils/setup/create-article-page.js
- src/utils/setup/serialize-rss-data.js
- tests/utils/create-article-node.test.js
This PR uses the [gatsby-plugin-feed](https://www.gatsbyjs.org/packages/gatsby-plugin-feed/) plugin to add an RSS feed for our articles at `/rss.xml` on production builds. GitHub won't let me attach an 'xml' file here, so I took a screenshot (and am happy to share the file on request).
For each article I included:
- Title
- Description
- Link
- Published Date
with results sorted so the newest articles are first. I'm not sure what else we would want to add in here.
> Add an RSS Feed for Articles

- src/pages/index.js
This PR fixes the play button on the thumbnail for the Twitch video thumbnail on the home page to be properly centered.
Staging:
This PR:
> Center Play Button on Twitch Preview

- gatsby-node.js
- src/utils/setup/on-create-page.js
- src/utils/setup/remove-excluded-articles.js
- tests/utils/remove-excluded-articles.test.js
This PR enables the front-end to remove requested articles from being shown on the learn page. We are expecting this to come from the back-end as `learnPageExclude` as one of the page groups.
Specifically, if an article is requested to be removed from the learn page:
- We still create the article as normal
- We still show the article in the `tag` pages
- We do not show the article on the learn page
- We do not count the article in the filters on the learn page
I wrote a unit test for the exclusion, as well as locally checked a value for `learnPageExclude` to check out the behavior.
> Allow Authors to Exclude Learn Page Articles

- src/components/ListTable.js
- src/components/dev-hub/global-nav.js
- src/hooks/use-media.js
- tests/unit/__snapshots__/ListTable.test.js.snap
This PR fixes two things for mobile articles:
- Adds an overflow to the table directive component to allow tables to be scrollable horizontally (This is broken on articles such as [this one](https://developer.mongodb.com/article/map-terms-concepts-sql-mongodb) in prod)
- Fixes the `useMedia` hook during static rendering. While building, the hook value is the default value, and then gets re-calculated when served. This fixes an issue with the top nav where refreshing on an article page would look like this:
Not 100% sure why this works, but the component is now properly re-rendering with the updated hook value, so this seems to have fixed a logical issue in the `useEffect` of `useMedia`.
> Mobile Article Layout Issues

- .github/workflows/devhub-ci-test.yaml
- .github/workflows/devhub-npm-test.yaml
- README.md
- cypress.json
- cypress/support/commands.js
- package-lock.json
- package.json
This PR adds a github action for CI testing a development build of the devhub with cypress to PRs to both staging and master. Furthermore, this PR adds conditional `npm install`ing only if a cached copy of `node_modules` is unavailable.
**Test Duration** (these tests are run in parallel)
e2e tests run in ~2 minutes
unit tests run in ~1 minute
I resolved issues with `npm installing` if a cache is available for `node_modules` which cut times down significantly on both test jobs. Restoring the cache still takes a bit of time, but this is likely because it is ~200MB compressed. Caching here is still faster than a fresh install.
> Add Cypress Github Action (With Caching)

- src/constants.js
- src/utils/fetch-twitch-videos.js
- src/utils/use-twitch-api.js
Pulled out just the logic for accessing videos from `useTwitchApi.js` to reuse it for the video/media page.
> Generalize Twitch Video Logic

- .prettierrc
- package-lock.json
- package.json
This PR bumps `prettier` to v2.0.4 (like mitx), with the `allowParens: avoid` option set in the `.prettierrc` file.
> Bump Prettier to 2.0.4

- src/components/dev-hub/filter-bar.js
- src/pages/learn.js
- src/templates/article.js
This PR fixes layout overflow issues for the learn page and articles specifically on resolutions near the iPad (~760px). There were some points where the desktop layout was overflowing or inaccessible so this PR addresses them by switching to the mobile view at this point:
- Learn page filters were overflowing
- Article page share/TOC buttons (towards the top) layout was also overflowing (likely what was being seen on Ken's article.
Before:
After:
> Fix Learn/Article iPad Layout Issues

- .github/workflows/devhub-ci-test.yaml
- cypress.json
I recently got access to use the snooty parser and store parsed data on Atlas from the DOCSP team, so this PR switches our testing data from using Sophie's parsed data to my integration testing content repo.
This allows us to keep data consistent across CI runs, and also test new cases by customizing our integration testing data to fit our needs (we now can control our own content repo, parse it, test against it, and see it in staging before deployment).
> Switch parsed data source to CI repo for CI testing

- gatsby-config.js
- gatsby-config.prod.js
- src/utils/setup/article-rss-feed.js
This PR uses our favicon for the RSS feed, and also adds `site_url` and `feed_url` which are passed to the rss `feedOptions` [here](https://www.npmjs.com/package/rss#itemoptions) through Gatsby.
I also pulled this object out of the config files and just reference it in config and config-prod instead.
This adds the following node to the RSS XML:
Not sure the best way to preview this, but it seems this is the correct field for `rss` to have the favicon.
> Add image, other meta to rss feed

- src/components/dev-hub/media-block.js
- src/pages/index.js
- src/pages/learn.js
This PR fixes two layout issues:
1. The events section of the index page was not taking up the full width. This was because the media width was not properly passed to the media block. I also removed right margin from the media element if it is reversed.
2. Centers featured content horizontally on the learn page.
Before:
After:
> Center Featured Learn Content, Expand Index Events

- cypress.json
- cypress/integration/article.js
- cypress/support/commands.js
- src/components/dev-hub/article-share-footer.js
- src/components/dev-hub/contents-menu.js
- src/components/dev-hub/series.js
This PR adds cypress testing for a specific article off of the integration content repo (`/article/3-things-to-know-switch-from-sql-mongodb/`).
I added the following general tests:
- Tested the header is populated with all of the important information
- Tested the contents menu brings the user to a specific header when requested
- Social URLs to LinkedIn, Twitter, Facebook work as expected
- A series is shown with links populated
- Proper SEO/meta tags are maintained (checking various fields on `meta` to ensure og/meta fields are populated as we expect)
> Add cypress testing for article pages

- src/components/dev-hub/article-series.js
- src/components/dev-hub/series.js
- src/templates/article.js
This PR lays some logical groundwork for an upcoming change to the series component. We are going to want to style links a bit differently whether its article is before or after the current one in the series (to promote continuing the series).
This PR changes logic to pass the active item index in the series to the series component instead of the title, so it will be easier to get past or upcoming series items by comparing indices.
I also moved conditional styling into the css prop.
Upcoming design (not in this PR):
> Reorganize Series Logic for Past/Upcoming Series Items

- cypress/integration/author.js
- cypress/integration/tag.js
This PR adds some simple cypress tests for the tag pages. We test:
- The header and breadcrumbs are populated with the relevant tag
- Articles are being populated on the tag page
- An article that has the tag `SQL` is displayed on the `SQL` tag page
- The `robots` meta name exists with the value `noindex`
> Cypress Tests for Tag Pages

- src/components/dev-hub/series.js
- src/components/dev-hub/theme.js
This PR updates an updated series component based on some new designs. The key changes are:
- We now will use the "stacked" series component from mobile at all times
- Three possible states for an article, active, past or upcoming (with distinct designs)
- Updated unicode icons to properly render on all browsers (Firefox was having an issue rendering the previous unicode values). The new unicode values are consistent across all browsers.
- Cleaned up some padding, etc.
- Cleaned up bug where a wrapped last link caused the dotted border to extend past the last bullet
[Mockups](https://mongodb.invisionapp.com/d/main/#/console/19833232/414977912/preview)
This PR:
> Updated series component

- src/components/dev-hub/codeblock.js
This PR fixes an issue only on safari where the codeblock line number border was on all four sides of the `div` (and wider than it should have been). It should only be on the right side. Explicitly setting border widths to 0 fixed this.
Before:
After:
> Fix Codeblock Border on Safari

- src/components/dev-hub/card-list.js
- src/pages/media.js
This PR does a few things with the `CardList`:
1. Fixes an issue with default props where instead of using default values, we null check and use `[]` if passed `null` (we were being passed `null` which overrode the previous default).
2. Moves `<CardContainer>` in `CardList` to wrap all the cards
3. Adds commentary about future work to come with this component to handle different types of items and articles.
Pages to check:
- /learn
- /tag
- /media
> Fix default props in card-list, update CardContainer

- src/components/dev-hub/layout.js
This PR fixes an odd chrome-only bug. When on the index page and hovering over the play button in the twitch video modal, the background would flash white momentarily.
Adding a background to the `GlobalWrapper` seemed to address the problem.
Before:
After:
> Fix Chrome Play Button Flashing Bug

- src/components/dev-hub/filter-bar.js
[Relevant Ticket](https://jira.mongodb.org/browse/DEVHUB-116)
DevRel wants the following logic for the filters on the learn page:
**Products**
- Place "Atlas" as the first product (after "All"), then sort by count in descending order.
**Languages**
- Sort by count in descending order.
This PR adds the logic to the learn page filters to add this sorting in.
> Add sort logic to filters on the learn page

- .storybook/webpack.config.js
- src/components/dev-hub/icons/icons.stories.mdx
- src/components/dev-hub/stories/blockquote.stories.mdx
- src/components/dev-hub/stories/card.stories.mdx
- src/components/dev-hub/stories/chart.stories.mdx
- src/components/dev-hub/stories/codeblock.stories.mdx
- src/components/dev-hub/stories/series.stories.mdx
- src/components/dev-hub/stories/video-embed.stories.mdx
This PR adds two new stories to storybook for `BlockQuote` and `VideoEmbed` and also adds mdx docs updates for the following stories (to clean up a bit):
- `Card`
- `Icons`
- `Chart`
- `Codeblock`
- `Series`
You can check these out by running the storybook
> Add blockquote, video stories, update other stories

- cypress/integration/home.js
- src/utils/fetch-live-event-data.js
This PR does two things:
- Removes the live API key to fix API calls to live.mongodb.com for events
- Omits the twitch-related cypress tests while we figure out the API issues there
> Remove live API key, omit twitch test

- src/components/dev-hub/card-badge.js
- src/components/dev-hub/card-list.js
- src/components/dev-hub/card.js
This PR adds a card badge component that makes it easier to identify the source of a media content. The badges are placed on the bottom left side of the thumbnail images.
> Card (media source) badge component

- src/components/dev-hub/twitch-fallback-card.js
- src/pages/index.js
This PR creates a component used if Twitch API calls fail/give us `null` video data. A question on this iframe:
- Using the channel id always checks for streams, there is no way to just get the last video without an ID. We could hardcode a video ID since more often than not the team won't be streaming, does this make sense here?
Desktop:
Mobile:
> Create an iframe twitch fallback component

- src/components/Image.js
- src/components/dev-hub/card.js
- tests/unit/__snapshots__/Figure.test.js.snap
This PR adds the `loading="lazy"` attribute to:
- Images within articles
- Images on cards
I also checked out the network tab and verified it didn't load certain images until they were close to the viewport, neat!
Some snapshots needed to be updated due to the new attribute
> Add lazy loading to article, card images

- src/components/dev-hub/related-articles.js
- src/utils/setup/get-related-pages-with-images.js
- tests/utils/get-related-pages-with-images.test.js
This PR solves [DEVHUB-124](https://jira.mongodb.org/browse/DEVHUB-124).
The issue was the data we were getting back for related articles was different from what we previously had. Before we just got `target` for all types of article links (internal and external). Now they are sending multiple types of related articles back with different fields for each based on whether they use the `doc` directive or try as a link (what Lauren was doing). This PR will handle both cases for robustness:
A "reference" type
A "ref_role" type
Neither of these had `target` so building related articles would fail. Also, these values have leading slashes, which older values did not.
This PR optionally checks for any possible field that could have the slug/url: `target` (not sure if this is even in use anymore), …
> Fix related pages by using refuri and fileid

- src/components/dev-hub/related-articles.js
Normally with `Links` and `Cards` we use the `to` prop for internal links so we don't have to put `withPrefix` everywhere. With related articles, we have both internal and external references, so we cannot be 100% sure which prop to use so we default to `href` instead of `to`.
This led to a small issue for internal related articles, because we were using `href` but not `to` we have to add `withPrefix` so any url prefix is maintained. You can see a broken related article [here](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/b10d18e/devhub/docsworker-xlarge/05-12-20-2/quickstart/bson-data-types-decimal128). Funny enough is that this will break on staging but not prod, since prod has no url prefix.
This PR adds a `withPrefix` call for internal doc references for internal …
> Use withPrefix for internal doc links

- src/components/dev-hub/tab.js
This PR makes minor css changes to list the buttons on the `Tab` component in a single column (as opposed two) on mobiles.
> List tab buttons in a single column on mobile

- src/components/dev-hub/badge.js
- src/components/dev-hub/card-list.js
- src/components/dev-hub/card.js
- src/components/dev-hub/stories/badge.stories.mdx
This PR documents the `Badge` component on storybook and makes the thumbnail images for twitch videos square to match the other cards (Youtube thumbnails are still in progress). It also renames the `CardBadge` component to `Badge` since its use is not restricted to just `Card` components.
> Storybook entry for the badge component and card-list changes

- src/components/dev-hub/slider.js
- src/components/dev-hub/stories/slider.stories.mdx
This PR creates a Slider component using `<input type="range" />`, which we will use when playing podcasts. It supports props for state management by parents, and works on chrome, ff, and safari!
I also made a quick story for it.
> Create a Slider Component

- .storybook/addons.js
- package-lock.json
- package.json
- src/components/dev-hub/stories/form.stories.mdx
For forms, we are also going to be using the leafygreen checkbox. This PR adds this package in and also creates a quick story for it. Should be simple enough to use with our forms.
> Add leafygreen checkbox

- src/components/dev-hub/section-header.js
This PR adds the section header component that will be used in the `Academia` page.
> Section header component

- src/components/dev-hub/card.js
Before, we were always given square images for our cards, so we didn't have any issues with different aspect ratios causing different size cards. Unfortunately, YouTube thumbnails don't come in 1:1 aspect ratios, so we were getting this effect:
This PR updates the Card Image logic to always fit the image into a 1:1 aspect ratio box so even if an image isn't a square, we will make it one. We take the initial image, center it, and fill the rest of the space so it matches other aspect ratio images. We get this done by using [padding-top against a 100% width](https://css-tricks.com/aspect-ratio-boxes/). We end up with this:
> 1:1 Aspect Ratio For Any Card Image

- src/components/dev-hub/global-footer.js
- src/pages/community/index.js
This PR satisfies [DEVHUB-129](https://jira.mongodb.org/browse/DEVHUB-129). This PR updates the links to the community forums to reference the location on the developer subdomain.
This change was made in two places, as requested:
- The global footer "Community Forums"
- The "join" button on `/community`
> Update Community Forums Links

- src/constants.js
- src/hooks/use-twitch-api.js
- src/pages/index.js
- src/utils/devhub-api-stitch.js
This PR is the last piece of work for moving existing APIs to Stitch, and also finishes migrating our Twitch use to the New Twitch API.
This PR incorporates a new Stitch function called `fetchMDBTwitchStream`, which is very similar to work done for Twitch Videos into the codebase by adding a new wrapper to call Stitch and incorporating it in the hook used by the homepage to check streams before checking videos.
Now, on the homepage we should see the old card back again (although there is no stream right now, a video does show) and no 401 errors in the console. The title was also missing from this card so I added it back in.
> Use Stitch for Twitch Streams

- src/hooks/use-all-videos.js
- src/utils/devhub-api-stitch.js
- src/utils/fetch-youtube-data.js
This PR moves the logic for which playlist ID is used for YouTube into Stitch. It also cleans up syntax so we just pass `maxResults` to Stitch and not `{maxResults}`.
> Move playlistId logic into Stitch

- src/components/dev-hub/input-label.js
- src/components/dev-hub/input.js
- src/components/dev-hub/select.js
- src/components/dev-hub/text-area.js
Our form element sizes were off compared to the original design spec. Not sure how this happened, but this PR adjusts the `input`, `textarea` and `select` components to be 60px tall by default and 40px tall with the `narrow` prop.
24px tall line height + 2 * 16px padding + 2*2px border = 60px for default
24px tall line height + 2 * 6px padding + 2*2px border = 40px for narrow
> Update form element sizes

- src/utils/setup/on-create-page.js
- src/utils/setup/remove-page-if-staged.js
- tests/utils/remove-page-if-staged.test.js
This PR gives us a way to maintain pages "in development" that don't go live to prod. Simply put, if a page is "staged" then we remove it if we are building in a production environment. This allows us to continue to develop these pages locally without anything being publicly available on production.
This approach is pretty simple because we can simply case on `SNOOTY_ENV`, which is `staging` at all times unless we run a job on the workerpool. This might be a bit stricter than we want, but the ability to case on `SNOOTY_ENV` seems like the best solution here.
We also can do things like continue to build cypress tests since `SNOOTY_ENV` is `staging` for CI testing as well, so we can have testing for the correct endpoint in place before a page ships out as well.
I wrote a quick test as well …
> Allow Staging Dev Pages

- src/components/dev-hub/academia-sign-up-form.js
- src/components/dev-hub/success-state.js
- src/utils/devhub-api-stitch.js
This PR adds logic for sending academia form data to a new Stitch function called `submitAcademiaRegistration`, which performs an insert into Atlas with this data. I also have a Stitch trigger setup for handling writes to Atlas (ideally to send a notification to Lieke) but this piece is incomplete.
Here we can see the data in Atlas:
> Handle Academia Form Submits

- src/pages/community/index.js
This PR changes the callout for linking to forums on the community page to the copy requested in [DEVHUB-143](https://jira.mongodb.org/browse/DEVHUB-143)
> Update community callout for forums

- src/components/dev-hub/mongodb-live-banner.js
Noticed it wasn't taking the full space on very large displays:
This PR:
> Give .live banner 100% width

- src/components/dev-hub/blockquote.js
- tests/unit/__snapshots__/BlockQuote.test.js.snap
I have found a potential solution to some of our z-index woes and have implemented it on the Blockquote.
After #347 the `GlobalWrapper` had a background which caused some unintended side-effects. One of which was hiding a piece of the `Blockquote`:
In fact, this piece of the Blockquote had a z-index of -1. Since we did not reset the stacking context for the Blockquote, this was hiding under every parent up to `<body />`. Adding this background exposed this problem.
This PR adds a `div` to the Blockquote which resets the stacking context, so the blockquote sits in front of other elements and using z-indices here is with respect to the blockquote only.
Funny enough, it seems this can also help with the `Button` hover state, should we want to bring that back in.
> Create new stacking context for blockquote

- src/utils/fetch-youtube-data.js
While testing the media component I found a small bug. The `publishAt` on `snippet` from YouTube is for when this video was added to the playlist. We should be sorting by when the video is published to YouTube.
I made the API call change in Stitch as well to get `contentDetails` as well, and the sorting is as expected after this PR.
[Here are the docs for playlist items](https://developers.google.com/youtube/v3/docs/playlistItems), where we can see this distinction.
> Use YouTube Video PublishDate for Sorting

- src/components/dev-hub/card.js
- src/components/dev-hub/icons/mdb-dev-leaf-desktop.js
This PR cleans up some lingering console errors related to incorrect prop casing. Specifically:
- On the nav image, we needed to camelcase in a few spots
- On cards, we conditionally render a styled component or the gatsby `Link`. If we render the latter, we must lowercase attributes as they are passed through to the DOM.
> Clean up prop errors in console

- gatsby-config.js
- gatsby-config.prod.js
- gatsby-node.js
- package-lock.json
- package.json
- src/pages/academia/educators.js
- src/utils/setup/on-create-page.js
This PR moves the academia page to `/academia/educators` and sets up a redirect for `/academia` to `/academia/educators`.
When running the `develop` server, there is a blip where it renders a 404 thten goes to the correct place. Fortunately, the [`gatsby-plugin-meta-redirect`](https://github.com/nsresulta/gatsby-plugin-meta-redirect) creates a small file to help handle this redirect on production builds so this will not happen after a production build.
> Move /academia to /academia/educators

- gatsby-node.esm.js
- src/utils/setup/create-article-node.js
- src/utils/setup/create-article-page.js
- src/utils/setup/create-asset-nodes.js
- src/utils/setup/create-tag-page-type.js
- src/utils/setup/get-related-pages-with-images.js
- src/utils/setup/handle-create-page.js
- src/utils/setup/init-stich.js
- src/utils/setup/remove-excluded-articles.js
- src/utils/setup/remove-page-if-staged.js
- src/utils/setup/save-asset-files.js
- src/utils/setup/validate-env-variables.js
- tests/utils/find-articles-from-slugs.test.js
- tests/utils/get-learn-page-filters.test.js
This PR follows off the esm work to convert gatsby-node related modules to use `import/export` syntax. No functionality has been added or removed.
I renamed the helper module `onCreatePage` to `handleCreatePage` since this now conflicts with the gatsby node API function name. Before with `exports.onCreateNode` this was not an issue.
> Convert ES5 require syntax to import/export for gatsby-node

- src/components/dev-hub/academia-sign-up-form.js
- src/components/dev-hub/project-sign-up-form.js
This PR changes a few things on the academia form, and one similar change on the project sign up form:
- Fixed a bug where the Checkbox required message did not show on Chrome (thinking about opening a PR for Leafygreen for this, since it seems important enough)
- Error messages for first name, last name, and email now show a "cannot be blank" message if blank instead of just the type validation
- Removed validation regex for email (also done on project sign up form)
> Update form error handling UX

- src/pages/academia/educators.js
This PR adds [Tahiya's changes from Dan](https://github.com/mongodb/devhub/commit/cf529cf0f8f2a476837a72a614c13a00feb97355) into the academia page. It swaps the educators/students sections copy, adds some padding below the sign-up form, and adjusts the leaf image position.
Perhaps the branch got merged in before these changes were pushed up but not sure
> Increase margin under signup form and swap eligibility section text

- src/utils/devhub-api-stitch.js
- src/utils/fetch-lybsin-podcasts.js
- src/utils/parse-podcasts.js
- src/utils/setup/fetch-build-time-media.js
- src/utils/setup/handle-create-page.js
This PR moves the `fetch` for Lybsin Podcasts also into Stitch. `fetch` is not supported at build-time since `window` is undefined 🤦  so this is a requirement to use podcasts at build-time. Part of this was moving the postprocessing `parsePodcasts` into its own module.
I also updated the function to get build time data to support both videos and podcasts, to save on overhead for instantiating a stitch client.
This is the last piece of work to get media elements pulled at build time.
> Podcasts in Stitch, Build Time

- src/components/dev-hub/card-list.js
There was a `0` floating at the bottom of the card list. This was because we are preparing for podcasts and didn't properly use our ternary operators on the length. This was not in prod.
This PR removes the 0.
> Remove extra 0 from card list

- src/hooks/use-all-videos.js
- src/hooks/use-podcasts.js
- src/pages/learn.js
- src/utils/fetch-lybsin-podcasts.js
- src/utils/setup/fetch-build-time-media.js
- src/utils/setup/handle-create-page.js
This PR builds off of the previous work to move media fetching into build-time to use this media data on the learn page. This removes the "jittering" effect so long as there is no new content between the latest build and when the page is rendered.
I updated the hooks to take a default value, so that way if the fetch returns identical data there should not be a rerender.
The target branch for this PR is not staging, it is the branch with media on the learn page.
> Use build-time media on the learn page

- src/utils/setup/get-staging-pages.js
- src/utils/setup/handle-create-page.js
This PR moves the local variable `STAGING_PAGES` into Stitch and adds support to access it. This will allow us to control when pages are released without needing a code change on the repo (so long as the change is done before a new build).
In Stitch I set up a basic value called `STAGING_PAGES` which is just an array of pages we don't want out on Prod yet. I also set up a very simple function called `fetchStagingPages` which serves as a getter for this value.
> Move logic for staged pages into Stitch

- src/components/dev-hub/global-nav.js
[DEVHUB-150](https://jira.mongodb.org/browse/DEVHUB-150)
This PR switches the "community" link on the top nav to point to the community forums instead of the existing community page.
This PR does not touch the community page files, since it seems like DevRel will update these in the future. They still live and are accessible at `/community` and `/community/events`. We can stage these, but not sure what the best course of action here is.
> Swap Nav link to Community Forums

- src/pages/academia/educators.js
This PR addresses images being different sizes on various browsers on the academia page.
The issue was Chrome was reading the `width` attribute off of images to provide flexbox positioning. Firefox did not work the same way. The solution here was to use flexbox css to specify an exact pixel width for these images.
Now the images look great on any browser. I also moved the leaf one up a bit to get it in line with the design.
Before (FF):
After (FF):
> Add flexbox constraints for Academia Images

- src/pages/academia/educators.js
We also can add `alt` tags to academia page images to help with screen reading. This PR adds alt tags to the two body content images on the academia page.
Feedback on content welcome!
> Add alt tags to images on academia page

- src/pages/code-for-good.js
This PR fixes links on cfg to use `href` instead of `to` and addresses max width issues on firefox and safari mobile
> Fix to links, max width

- src/pages/code-for-good.js
These would show as white when `visited`, but we would always like them as green.
> Set CFG visited links to green using href

- src/pages/academia/educators.js
This PR removes padding from the new `academia/educators.js` page header for mobile displays. This will allow help us get better alignment with the body content.
> Remove padding from hero banner on mobile

- src/pages/code-for-good.js
This PR addresses some design tweaks for the Code for Good page. Specifically, this PR:
- Disables the `shouldContainBackground` prop on the hero banner, allowing the image to break aspect ratio while shrinking (keeping the waves grounded to the bottom of the banner).
- Disables the pink hover state on the hero banner link
- Uses flexbox to manage when to wrap the hero banner link and gives spacing between the button and link when wrapped.
Here are some screenshots:
> Fix text sizing, background waves cover

- src/components/dev-hub/byline-block.js
- src/utils/get-author-prefix.js
- tests/utils/get-author-prefix.test.js
[Ticket](https://jira.mongodb.org/browse/DEVHUB-84)
This PR updates the BylineBlock logic to comma-split lists of authors when three or more are present. One example of this locally is in the article `/article/johns-hopkins-university-covid-19-data-atlas` which has four authors. I decided to abstract this logic out and test it since it got a little complicated.
- If there is one author, it should look like 'By Author Name' (same as before)
- If exactly two: 'By First Author and Second Author' (same as before)
- If 3+: 'By First Author, Second Author, and Third Author' (new!)
(The tests should help shed light on this)
Before:
After:
> [DEVHUB-84] Comma-split Three or More Authors

- src/utils/fetch-event-data.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/fix-event-local-urls/community/events/)
[Broken Production Link](https://developer.mongodb.com/community/events/)
This PR fixes addresses an issue where event data is coming in with relative links to an event on mongodb.com instead of absolute links. We don't try to format them as-is so this would try to link to developer.mongodb.com/community/events/events/eventname instead of mongodb.com/events/eventname
The solution here was to regex check for either `http` or `www` starting off this field. If this is the case then we don't add anything to the URL. If not, we add the mongodb.com/ prefix to make the link absolute.
> Fix local URLs coming from Events API

- cypress/integration/article.js
- src/components/dev-hub/article-share-footer.js
- src/components/dev-hub/share-menu.js
- src/utils/get-article-share-links.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-200)
[Staging Link (Sample Article)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/share-trailing-slash/how-to/static-website-deployments-mongodb-stitch-hugo-git-travis-ci)
This PR removes trailing slashes from our social share links on articles, including the copy functionality, twitter, facebook, and linkedin* (see below). I also was going to refactor these two components a bit more but it seemed pretty large for just this small change so I decided to hold off.
To verify:
- Check out the sample article
- Share links should all have the article url without a trailing slash (LinkedIn is odd and keeps putting it there even though we don't pass it, will look into this separately)
- Share links on top and …
> Remove Share Links Trailing Slash

- cypress/integration/article.js
- src/components/dev-hub/SEO.js
- src/templates/article.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-169)
[Staged Article With Relevant Tags](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-169/article/3-things-to-know-switch-from-sql-mongodb)
[Staged Article Without Relevant Tags Rendered](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-169/article/active-active-application-architectures)
This PR builds off of some previous SEO work to allow writers to omit several SEO fields, including:
- `twitter:site` (defaults to `@mongodb`)
- `og:url` (defaults to the expected url)
- `og:type` (defaults to `article`)
After this change, writers can omit these fields from their rSTs and have the expected value populate for them. I did the same in the devhub content integration …
> DEVHUB-169: Add Support for Optional SEO Fields

- cypress/integration/article.js
- cypress/support/commands.js
- gatsby-ssr.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-205)
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-205/)
This PR adds several requested statcounter tags to the bottom of each page (see JIRA). The approach I took was to use a Gatsby plugin option called `onRenderBody`, which gives an option to specify tags to put at the end of the `body` tag.
To verify, each page should have tags within `body` towards the bottom that look like this:
I added a cypress test just to verify one of the tags exists (felt that was strong enough)
> DEVHUB-205: Add support for statcounter

- gatsby-config.js
- gatsby-config.prod.js
- src/queries/search-article-rss-data.js
- src/utils/setup/create-article-node.js
- src/utils/setup/search-rss-feed.js
- src/utils/setup/serialize-search-rss-data.js
- tests/utils/create-article-node.test.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-202)
[Staging RSS Feed File](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-202/search-rss.xml)
Deepak has asked for a second DevHub RSS feed, this time adding some custom fields relating to search. Initially I was thinking of adding to the existing feed but we decided to just keep this separate should we want to change the Search logic (he will be pulling from the generated XML file).
I've verified this format works for Deepak so we should be good on when to include/exclude fields, but will leave some PR comments.
To do so, we did the following things:
- Add the new fields `type`, `authors` (with name), and `tags` for an article into its GraphQL node
- Create a new query to query GraphQL for these …
> DEVHUB-202: Add Second RSS Feed for Text Filter

- src/components/dev-hub/empty-text-filter-results.js
- src/components/dev-hub/filter-bar.js
- src/pages/learn.js
[InVision](https://mongodb.invisionapp.com/share/5GWV0HJSXZR#/screens/415163294)
[Staging Link (learn page)](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/text-filter-layout/learn)
This PR begins some work to implement the new learn page text filter (see InVision). The goal of this project is to add a new filter for the learn page which will hit a backend to fetch articles to show based on a text query (search, but we are not calling it search). More than happy to give additional context on the project! 
This does some small logic rearrangements on the learn page to be able to render content returned from a text filter query.
Before, we rendered content based on which learn page tab was selected. I moved that logic and replaced this with a `switch` …
> DEVHUB-204 Part 1: UI Scaffolding

- src/components/dev-hub/empty-text-filter-results.js
[InVision](https://mongodb.invisionapp.com/d/main/#/console/19769567/429514727/preview) (Dan also checked and gave LGTM)
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/text-filter-empty/learn/) (Learn Page, Hardcoded Empty State)
This PR continue with the text filter work and adds in the desired empty state. Note for the staging link I hardcoded it in for an easier time reviewing, this is not an actual change.
> DEVHUB-204 Part 2: Empty State

- src/queries/search-article-rss-data.js
- src/utils/setup/create-article-node.js
- src/utils/setup/serialize-search-rss-data.js
- tests/utils/create-article-node.test.js
For [DEVHUB-202](https://jira.mongodb.org/browse/DEVHUB-202)
[Staging RSS Feed link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/rss-updates/search-rss.xml)
[Master RSS link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/staging/search-rss.xml)
This PR adds four fields we also need for the text filter work into the RSS feed:
- `atf-image`: the location of the image shown with each article
- `slug`: the location of the article
- `products`: the list of products tags
- `languages`: the list of languages tags
To Verify:
- Check out the staging RSS feed link and compare with master RSS feed link (pick a specific article)
- The only changes should be the additions of these four fields. Nothing else should be different.
Here …
> DEVHUB-202: Add Four Missing Text Filter RSS Fields

- src/components/dev-hub/select.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/aria-label-dropdowns/)
I was running an accessibility audit on the learn page and found we should provide better labeling on the dropdowns for screen-reading purposes. This short PR adds the `aria-label` attribute to the `Select` component to do so by default from now on.
> Add aria-label tag for selects

- src/components/dev-hub/filter-bar.js
- src/components/dev-hub/select.js
[Staging Link (Learn Page)](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/disabled-selects/)
This PR adds a small but nice piece of functionality in conjunction with the new text filter. When the user is using the text filter, the other filter types (product, language) are unavailable since we are filtering from an external service. This PR disables those filters when unavailable to provide a better experience for the user.
To verify:
- When the text filter input is empty, the dropdowns next to it should be enabled
- When the text filter input is not empty, the dropdowns next to it should be disabled
> Disable Dropdown Selects when Text Filtering

- cypress/integration/article.js
- src/components/dev-hub/link.js
- src/components/dev-hub/series.js
- tests/unit/__snapshots__/Heading.test.js.snap
- tests/unit/__snapshots__/Link.test.js.snap
- tests/unit/__snapshots__/Reference.test.js.snap
[Linked Issue](https://github.com/gatsbyjs/gatsby/pull/25180)
[Broken Series in Prod](https://developer.mongodb.com/article/schema-design-anti-pattern-summary)
[Staging Link to Series Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/relative-link-fix/article/map-terms-concepts-sql-mongodb)
[Staging Link to Article with Related Articles (just to confirm it still works)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/relative-link-fix/quickstart/bson-data-types-decimal128)
Recently we updated Gatsby to v2.22.11 to v2.24. In 2.22.17 [they changed the Link behavior so any paths without a leading slash are now interpreted as relative](https://github.com/gatsbyjs/gatsby/pull/24054) 🤦 
This PR adds a check to the `Link` …
> DEVHUB-220: Relative Link Fix

- src/utils/setup/get-related-pages-with-images.js
- tests/utils/create-article-page.test.js
- tests/utils/get-related-pages-with-images.test.js
[Staging link to article that failed CI build before](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/fileid-type-change/quickstart/bson-data-types-decimal128)
(Check out the related article at the bottom)
Related link data structure before:
```
[
{
type: 'ref_role',
position: { start: [Object] },
children: [],
domain: 'std',
name: 'doc',
target: [ '/how-to/bucket-pattern', '' ]
flag: '',
fileid: [ '/how-to/bucket-pattern', '' ],
image: '/images/atf-images/illustrations/schema-design-patterns.png'
}
]
```
Related link data structure after:
```
[
{
type: 'ref_role',
position: { start: [Object] },
children: [],
domain: 'std',
name: 'doc',
target: '/how-to/bucket-pattern',
flag: '',
fileid: [ '/how-to/bucket-pattern', '' ],
image: …
```
> Fix fileid use for target

- cypress/integration/tag.js
- cypress/support/commands.js
- src/components/dev-hub/blog-tag-list.js
[JIRA (Request in Thread)](https://jira.mongodb.org/browse/DEVHUB-63)
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-63/learn)
This PR adds a request to bump the default number of tags that show from 2 to 3. I also added a cypress test to make sure expanding continues to work well.
To Verify:
- Check out the staging link
- Check out card tags
- Make sure any with `...` indeed expand to 4+
> DEVHUB-63: Change default number of tags shown to 3

- cypress/integration/learn.js
- src/pages/learn.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-225)
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-225/learn/)
This PR adds a small change to use a query param to keep track of the TextFilter value. Previously we were not doing so, so by keeping track of it with the rest of the existing learn page filters we can add it to the query params basically for free.
I also added a cypress test to model this behavior
A/C:
- There should be a `text` queryParam for the learn page if and only if there is some value in the text filter.
- This query param should be the same as the value in the text filter
- On loading the page with this query param, the filter should be properly updated
> DEVHUB-225: Use a Query Param for Text Filter

- src/components/dev-hub/select.js
[Staging Link (working example)](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/hydrate-select-enabled/learn/?text=foo)
[Staging Link (broken example)](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/776b8b8/devhub/docsworker-xlarge/09-28-20/learn/?text=staging)
When checking the staging branch I noticed some odd behavior on the Select when it should be disabled. What happens is we have a query param so the text filter should be filled and the other dropdown filters should be disabled (see working staging link for this in action).
Gatsby, at build-time, would default to the `enabled=true` when generating static html. We would then render the page with a query param and the styling would not be updated as expected because at build-time we …
> Re-hydrate enabled styles for Selects

- cypress/integration/learn.js
- gatsby-browser.js
- package-lock.json
- package.json
- src/components/dev-hub/card-list.js
- src/pages/learn.js
[JIRA 222](https://jira.mongodb.org/browse/DEVHUB-222)
[JIRA 184](https://jira.mongodb.org/browse/DEVHUB-184)
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-222/learn)
This PR does a few things related to the load more button on card lists to make it more SEO friendly. Specifically:
1. The Load More button is now a link which appends a query param to the end of the current URL which will control how many items are shown
2. Implements the `shouldUpdateScroll` Gatsby Browser API method to keep the scroll position constant if a link goes to the same page (such as adds a query param)
A/C:
- A new `page` query param pops up when clicking "load more"
- Scroll position does not change
- The other query params still exist and work around …
> DEVHUB-222 & DEVHUB-184: "Load More" with Query Params

- src/components/dev-hub/card-list.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/rerender-cardlist/learn/?page=2)
[Broken Prod Link](https://developer.mongodb.com/learn/?page=2)
(See "How To Verify")
This PR fixes a re-render flash bug when using the "Load More" button on the `CardList`. What was happening before (and in the broken link) is for a split second when you click "Load More" the `CardList` rerenders with only having a total of the initial limit of cards (12) before a `useEffect` checks the query params for which "page" the user is on and then loads more. So some results would be hidden and then re-appear also losing track of scroll state.
The fix is to try to get the "page" before invoking `useState` so the first render always has the correct `page` and we do …
> Fix CardList Flash on "Load More"

- cypress/integration/article.js
- src/templates/article.js
[Staging Link (Fixed Article)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/fix-updated-date/article/coronavirus-map-live-data-tracker-charts)
[Prod Link (Broken Article)](https://developer.mongodb.com/article/coronavirus-map-live-data-tracker-charts)
Somewhere along the way we were expecting the name of this field to be `updatedDate` but it was coming in as `updated-date`. This PR swaps to the correct field name and adds a cypress test for it as well.
Note in the broken article there is no updated date in the heading but in the staging link there is.
> Fix updated date field

- cypress/integration/article.js
- src/utils/get-article-share-links.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/linkedin-url-slash/article/johns-hopkins-university-covid-19-data-atlas)
We have some unsolved redirect issues on the DevHub for article links. Take a look at the [LinkedIn debugger specifically for this article](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdeveloper.mongodb.com%2Fhow-to%2Fuse-atlas-on-heroku) and [this is what happens when someone tries to share the article without a trailing slash](https://www.linkedin.com/shareArticle/?url=https://developer.mongodb.com/how-to/use-atlas-on-heroku). If we add back in a trailing slash for this case, the preview functionality is restored.
Facebook and Twitter handle this well, but LinkedIn has always been a bit flaky. [Try to …
> Add Trailing Slash to LinkedIn Share URLs

- cypress/integration/tag.js
- package-lock.json
- package.json
- src/components/ComponentFactory.js
- src/components/dev-hub/button.js
- src/components/dev-hub/layout.js
- src/components/dev-hub/tab-context.js
- src/components/dev-hub/tabs.js
- src/utils/browser-storage.js
[Staging Article Using New Directive](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/tabs/article/sample-tabs-article)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-238)
This PR adds a component to support a new Article directive called `.. tabs::`. [Here is the documentation](https://docs.mongodb.com/meta/tutorials/tabbed-content/) on this directive, but in a nutshell the premise is this:
- An article can use `.. tabs::` and hide content within
- The typical use case is for toggling which programming language to display on code
- **When one tab on a page changes, the others change to match (so programming language stays constant, etc)** (try this one out!)
- Tabs support a `:hidden:` option which hides the tab bar from view (so content toggles)
- Each …
> Tab Directive Support

- src/components/dev-hub/audio.js
[Staging Learn Page](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-243/learn)
When listening to Podcasts on the DevHub, there was a lag between moving the slider component and having the feedback show up in the UI (as well as the podcast playing). What was happening was when we changed the slider we would only update the underlying react-player to seek and not immediately move the slider/update state. The slider would catch up on the next second the podcast was playing since state os also updated by react-player.
By updating the state here as well we get a much smoother UX when using the slider!
To Verify:
- Check out the staging learn link and try to play a podcast
- Seek to some points on the podcast via the slider, the experience should be good …
> DEVHUB-243: Make podcast playing smooth

- cypress/integration/article.js
- src/components/dev-hub/tabs.js
[Staging Article (the one used in the cypress tests)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/cypress-tabs/article/sample-tabs-article)
This PR continues with adding tests for the Tabs component by adding Cypress tests for it. Using a sample article, the UI tests check basic rendering and interactions, as well as some of the different options including the `hidden` option. I'd suggest checking out the staging link provided to help see some of these tests in action!
> Cypress Tests for Tabs Component

- src/utils/setup/save-asset-files.js
[[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/sophstad/ss/fix-assets/)] Use the aggregation pipeline to split our assets query into chunks of a given size. A subset of results is returned each time, which avoids hitting Realm's memory limit. This approach was significantly faster than running `.find()` multiple times, which proved prohibitively slow.
> Chunk asset queries

- cypress/integration/learn.js
This PR fixes an issue with cypress on the learn page where we were not effectively re-querying the DOM after a re-render ([similar issue to this mitx PR](https://github.com/10gen/mitx/pull/5123) with a similar resolution).
By cleaning this up, we don't need to optionally retry anymore for the following test, and I renamed some of the `describes` for clarity.
> Clean up cypress concurrency issue

- tests/unit/Tabs.test.js
- tests/unit/__snapshots__/Tabs.test.js.snap
- tests/unit/data/Tabs.test.json
The new Tabs component has gone through a dry run and functionally there are no changes to make. As a result, now is a time to fully add the component into our testing suite.
First up, this PR adds a basic snapshot test with data provided by the Snooty parser.
> Construct basic snapshot test for tabs

- gatsby-node.esm.js
- src/components/ComponentFactory.js
- src/components/Extract.js
- src/components/Root.js
- src/components/Step.js
- src/components/Steps.js
[[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/sophstad/ss/DOP-1667/)] Parser PR https://github.com/mongodb/snooty-parser/pull/230 introduced a new `root` node to improve the accuracy and traceability of diagnostics. The front end now needs to dive into these root nodes in order to render their contents.
Duplicates https://github.com/mongodb/snooty/pull/304.
> DOP-1667: Render children of root nodes

- cypress.json
- cypress/integration/learn.js
- cypress/support/commands.js
- src/components/dev-hub/blog-post-title-area.js
- src/components/dev-hub/card-list.js
- src/components/dev-hub/tab.js
[Staging Link (to learn page)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-251/learn/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-234)
This PR makes a tweak to the general `CardList` component which will now account optionally for an article's `updated-date` when sorting. Most of the work here is improving the end-to-end tests to add a check for this behavior as well as clean up some tests impacted by the ordering change.
> DEVHUB-251: Sort CardList by created-date

- .github/workflows/devhub-ci-test.yaml
To help with QA workflow improvements, we set up a new branch for storing CI data and will be using `master` to strictly clone the `devhub-content` repo. This PR changes the GH Action test to use the new branch
> Switch CI test branch off master

- gatsby-node.esm.js
- src/utils/setup/create-asset-nodes.js
- src/utils/setup/save-asset-files.js
- tests/utils/create-asset-nodes.test.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-252/)
[JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-252)
This PR follows the [related Snooty work](https://github.com/mongodb/snooty/pull/315/files) by changing the datatype of an asset from a string to an object containing the following fields:
- `checksum` (essentially a hash of the image)
- `key` (the filepath to store at)
Here is a summary of what I changed:
- Changed our GraphQL representation of an image to also have a `paths` array field (for all of the relevant filepaths to save as)
- Changed our local representation of assets from an Array to an Object mapping the checksum value to filepaths
- Updated testing
> DEVHUB-252: Support Object Representation for Assets

- .github/workflows/devhub-ci-test.yaml
- .github/workflows/devhub-npm-test.yaml
Bumps the following GH Action plugins:
- Cache
- Cypress
- Upload (for artifacts on failure)
The reason this came up was I noticed these deprecation warnings in the CI job generally. [Here is a job with the warnings](https://github.com/mongodb/devhub/actions/runs/345764491).
We are not using `set-env` in our configs so I assumed this was one of the plugins we use and lo and behold, the CI job on this PR has no such warnings.
> Bump GH Actions plugin versions

- src/pages/index.js
- src/utils/setup/get-item-type-from-url.js
- src/utils/setup/handle-create-page.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/js/home-featured-refactor/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-234)
This PR is related to a larger effort to un-hardcode logic for experiences on the DevHub which only support articles by refactoring Home page "Feature Article" section.
Previously, we had some logic and terminology which suggested this section only supports articles (which it still does right now), but this PR lays the foundation for supporting new content types here by doing the following:
- Adding a new `type` field to featured articles which can be used to distinguish between pieces of content. Ideally these should all share the same API (TS would be awesome for this someday) but until then this can help distinguish …
> DEVHUB-234: (part 1) Refactor Featured Home Articles Logic

- src/pages/404.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/add-404-title/404/)
I noticed the 404 page does not have a `title` applied, so this PR gives it one to show up in the browser tab. For copy I went off of what University has (`404 | MongoDB University`) and chose `404 | MongoDB Developer Hub`. Previously it just showed the link in the browser tab
> Add Title for 404 page

- package-lock.json
- package.json
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/gatsby-226/)
[Changelog (non-exhaustive)](https://github.com/gatsbyjs/gatsby/blob/master/docs/reference/release-notes/v2.26/index.md)
This PR upgrades our version of Gatsby to the newest 2.26.0. Nothing functionally should change for our users.
> Bump gatsby to 2.26

- cypress/integration/learn.js
- gatsby-browser.js
- src/components/dev-hub/input.js
- src/components/dev-hub/select.js
- src/pages/learn.js
- src/utils/get-article-share-links.js
- src/utils/learn-page-tabs.js
- src/utils/query-string.js
- src/utils/remove-trailing-slash.js
- tests/utils/remove-trailing-slash.test.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-185/learn)
This PR fixes some bugs with state on the learn page. Namely, the following points were addressed:
- Clears all state when the top `learn` link is clicked on the nav bar. (DEVHUB-185)
- Adds a query param to the URL based on which tab is clicked (articles, podcasts, etc.)
- Fixes a bug where the `select` component would not reset state while controlled by a parent if cleared
- Fixes a bug where pagination would change which filter settings were applied
- Adds an "enum" (actually an object since we are not on TS) for the different tabs on the learn page
- Fixes a bug where the URL would flicker with query params when certain filters were applied
Acceptance Criteria:
- Filters, …
> DEVHUB-185 and DEVHUB-235: Learn Page Filter State

- package-lock.json
- package.json
- src/components/dev-hub/codeblock.js
[Staging Article](https://docs-mongodbcom-staging.corp.mongodb.com/remove-auto-option/devhub/jordanstapinski/DEVHUB-258/article/3-things-to-know-switch-from-sql-mongodb)
[Prod Article](developer.mongodb.com/article/3-things-to-know-switch-from-sql-mongodb)
This cannot be merged until a PR in devhub content is approved. This is because `auto` is no longer supported.
This PR upgrades the LeafyGreen code block to v7 from v3. This re-structures how the component is rendered on the DOM so we had to update the styling here as well since it is now using a CSS table for the overall layout.
What we do now is use an absolute element for the light grey background on the line numbers and gradient. Check out the staging links to see the style and highlighting in action!
> Upgrade LeafyGreen Code Block, Add Line Highlighting

- src/components/Figure.js
- src/components/Image.js
- src/utils/get-image-alignment-style.js
- tests/unit/__snapshots__/Figure.test.js.snap
[JIRA](https://jira.mongodb.org/browse/DEVHUB-322)
[Broken Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/staging/article/schema-design-anti-pattern-bloated-documents)
[Fixed Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-322/article/schema-design-anti-pattern-bloated-documents)
This PR fixes a bug that has been around but not uncovered until now. The idea is that with a `figure` that has some `align` option and a caption, the caption does not float with the image. The solution is to have the entire block float together! I also took this chance to clean up some CSS in the `figure`
Check out the article in the staging link and the broken article link. In the latter you will see for some GIFs the …
> DEVHUB-322: Let captions float with images in figures

- src/components/Figure.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-322/article/schema-design-anti-pattern-bloated-documents#example)
fyi @sophstad I added some margin in #567 that then got repeated by leaving `nodeData` align alone. This is a happy medium by allowing the centering to persist, but not duplicating anything else
> Remove option if not centered to repeat duplicated CSS

- src/components/dev-hub/stories/student-spotlight.stories.mdx
- src/components/dev-hub/student-spotlight/index.js
- src/components/dev-hub/student-spotlight/share-project-cta.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-295)
This PR adds a simple component to encourage students to share their work by giving some short text and a CTA. On "small mobile" (< 350px) the copy breaks line, so perhaps we want to shorten the copy.
> DEVHUB-295: Add Share Something CTA

- src/components/dev-hub/hover-card.js
- src/components/dev-hub/stories/card.stories.mdx
- tests/unit/HoverCard.test.js
- tests/unit/__snapshots__/HoverCard.test.js.snap
[JIRA](https://jira.mongodb.org/browse/DEVHUB-291)
[Figma](https://www.figma.com/proto/QuUf86imwSoPNYoxZX3az2/Academia---Student-Spotlights?node-id=508%3A379&scaling=min-zoom)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-291/) (check out the events image on the home page, this is now a Hover Card. This home page change is not part of the PR)
This PR adds a new unused component to the library: `HoverCard`. This component presents an image and on focus or hover, displays its children above an opaque backdrop.
> DEVHUB-291: Hover Card

- src/utils/setup/find-articles-from-slugs.js
- src/utils/setup/get-learn-page-filters.js
- src/utils/setup/handle-create-home-page.js
- src/utils/setup/handle-create-learn-page.js
- src/utils/setup/handle-create-page.js
- tests/utils/find-articles-from-slugs.test.js
- tests/utils/get-learn-page-filters.test.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/refactor-build-time-pages/)
When I was getting ready to work on Student Spotlight for the home page, I noticed an opportunity for refactoring. We had many pieces of logic in `handle-create-page.js` relating to the home and learn pages. Additionally this file was becoming quite bloated.
This PR splits the logic from that one module into five with `handle-create-page` become a much lighter `switch` for routing logic to the correct page handler. This makes our code also much more clear to read.
> Refactor build time pages

- src/components/pages/home/academia-feature.js
- src/components/pages/home/community-feature.js
- src/components/pages/home/events-feature.js
- src/components/pages/home/feature-section.js
- src/components/pages/home/hero.js
- src/components/pages/home/index.js
- src/components/pages/home/twitch-feature.js
- src/pages/index.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/modularize-home-page/)
This PR does some cleanup of the home page as we move closer to Student Spotlight and Strapi. Managing the home page has become somewhat cumbersome as all logic and components were located in one file. Moving the key sub-components into a new file structure gives us some benefits and patterns for the future:
1. Easier to read/maintain code.
2. Allows us to better use Gatsby's `Static Queries` to interact with Strapi data on the component level, letting us scale in the future by grabbing data only where it is needed versus potential prop drilling.
3. Sets up logic for building scalable pages in the `pages/` or `templates/` directories as we move towards a period of generating new …
> Modularize Home Page

- cypress/integration/article.js
- src/templates/article.js
- src/utils/add-trailing-slash-if-missing.js
- tests/utils/add-trailing-slash-if-missing.test.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-348/)
[Staging Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-348/how-to/realm-google-authentication-android)
[CROUD diagnosis (Row 1)](https://docs.google.com/spreadsheets/d/16N2GL58j3y2SRATvpIUFiVq_MftYY6lphwyJVrAbyg0/edit#gid=993232630)
This PR adds logic for adding a trailing slash (if missing) to a canonical URL when it is auto-generated by this software. If an author provides a canonical URL we respect it as-is, but if they omit a canonical URL (as they should) we will generate the correct version for them.
To verify:
- Check out the article in the staging link
- Check the source code and find "canonical", this URL should now have a …
> DEVHUB-348: Add Trailing Slash to Auto-Generated Canonical

- cypress/integration/article.js
- src/templates/article.js
- src/utils/add-trailing-slash-if-missing.js
- tests/utils/add-trailing-slash-if-missing.test.js
[Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5ff36737ceb0c9c2e5f4cdf6)
[Staging](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/1770f61/devhub/docsworker-xlarge/canonical-with-slash-articles/)
```
9cb70b9 DEVHUB-348: Add Trailing Slash to Auto-Generated Canonical (#577)
```
> DEVHUB-348: Add Trailing Slash to Auto-Generated Canonical (#577)

- src/components/dev-hub/card-list.js
- src/components/dev-hub/paginate.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/generic-pagination/learn)
This PR takes some pagination logic from the card list and moves it into a more general `Pagination` component which will allow us to paginate any group of items (not just `Card`s).
This behavior is covered by a test on the learn page. There should be no functional differences from the existing behavior.
To verify:
- Check out any page with pagination
- Click "Load more"
- More items should appear as normal and the `?page=...` in the URL should update as consistent with production
> Create Generic Pagination

- .github/workflows/devhub-ci-test.yaml
- .github/workflows/devhub-npm-test.yaml
This PR updates only testing infrastructure.
We set up a new EC2 testing instance for the CMS so we can isolate testing data and have a "staging" CMS environment before going to production. Now, we can comfortably control the test data coming in for CI purposes. I also updated the config to run on any PR now.
All tests and builds should pass on this branch.
> Update GH actions to point at test Strapi instance

- src/components/dev-hub/global-nav.js
- src/queries/fragments/top-nav.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-387-pull-in-data/)
This PR breaks the existing nav and prepares for integrating with the new data source. We add a GraphQL static query and pull data before doing a WIP mapping from data to components.
> DEVHUB-387 [Part 2]: Pull in GraphQL Data

- src/components/dev-hub/global-nav.js
- src/components/dev-hub/nav-item.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-388/)
[Figma](https://www.figma.com/proto/8m3qEliKXVtcqjf17jtVjL/DevHub-Nav?node-id=379%3A1454&scaling=min-zoom)
This PR adds hover actions to the top-nav based on the Figma designs. The goal is to create accessible sub-menus which appear on hover or focus.
> DEVHUB-388: Add Hover States for Menu Items

- src/components/dev-hub/video-embed.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/lazy-load-videos/)
This PR removes some unused JS by using the react player `lazy` option. We already do this on podcasts but missed it for videos.
This saves about 50Kib of unused JS.
> Lazy load react-player for videos

- src/components/dev-hub/blog-tag-list.js
- src/components/dev-hub/grid.js
- src/components/dev-hub/student-spotlight/github-student-pack.js
- src/components/dev-hub/student-spotlight/share-project-cta.js
- src/components/pages/students/all-projects.js
- src/components/pages/students/featured-project.js
- src/pages/academia/students/index.js
- src/queries/fragments/project.js
- src/utils/transform-project-strapi-data.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-302-layout/academia/students/)
This PR adds the rest of the data into the Gallery page and fixes layout on desktop (mobile still WIP from design). We had to do some additional refactorings here:
- Switched Grid from copying in `css` to copying in `style`
- Allowed the `BlogTagList` to not navigate
- Added tags into query calls
> DEVHUB-302 [Part 4]: Basic Gallery Layout

- src/components/pages/home/project-card-grid.js
- src/queries/fragments/project.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-299-from-strapi/)
Now that the single type is set, this PR swaps the query to use the single type field for the featured home page projects. Since GraphQL does not think this is a Project type we cannot use an existing fragment. There is likely a workaround here but did not find anything quickly so will come back to it for cleanup.
> DEVHUB-299 [Part 2]: Swap Home-Page Featured Projects to use Single Type

- src/queries/fragments/project.js
- src/utils/transform-project-strapi-data.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-372/)
This change reflects Strapi model changes in [this CMS PR](https://github.com/10gen/devhub-cms/pull/9). In order to view `name` on the table view for a collection we had to move it out of a repeatable type `BasicInfo`. This change just updates queries pulling in `name` accordingly.
Project cards still show `name` where desired thanks to the mapping :)
> DEVHUB 372: Move projects out of info in GraphQL Queries

- src/queries/fragments/project.js
No staging link since this is not yet in use, a successful build means the queries are still valid
This PR moves the `name` field for querying a student from within bio to out of bio to reflect the CMS change [here](https://github.com/10gen/devhub-cms/pull/11).
> DEVHUB-372: Move Student Name in Query

- src/components/pages/academia/index.js
- src/components/pages/academia/students-educators-details.js
- src/pages/academia/index.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-300-body-content/academia/)
This PR adds the rest of the content to the academia entry page and finishes setting up the desktop layout (mobile design is WIP).
I opted to not put this content as Strapi fields for two main reasons:
1. Copy changes seem relatively unlikely
2. Don't want to bloat Strapi fields, that way our internal partners can better find what they actually will update frequently.
Of course should we want to migrate these fields into Strapi that would be easy given this component structure.
> DEVHUB-300 [Part 2]: Desktop Academia Entry Page with Content

- src/components/dev-hub/tab.js
- src/pages/learn.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-397/)
This PR adds support for anchoring to the section below featured content on the learn page by adding an html `id` attribute. We are still playing around with what best represents this section, but `skip-featured` is where we are at for now.
I also updated Nav data in Strapi so this staging link will feature a nav that will directly point to the tab above the content grid.
> DEVHUB-397: Add Learn Page Anchor to All Content

- src/pages/learn.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-397-main/)
We decided to change the anchor llink to `#main` from `#skip-featured` as this also better represents where we are anchoring to on the Learn page. The relevant content has also been updated on Strapi.
> DEVHUB-397 [Part 2]: Swap Anchor ID to Main

- gatsby-browser.js
- src/utils/has-anchor-link.js
- src/utils/is-new-page.js
- tests/utils/has-anchor-link.test.js
- tests/utils/is-new-page.test.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-397-scroll-learn/)
This PR fixes a potentially poor UX issue with the incoming nav. If a reader is on the learn page and uses the nav to again navigate to the learn page, nothing would happen. This is because of how loose we are being in `gatsby-browser` in not updating scroll position if a pathname has not changed.
Now, we also check to see if where we are navigating to has an anchor tag and we respect it. I also added testing for this behavior. Here are some places this could impact (and seems to continue to behave consistently):
- On the learn page using the new nav
- On the learn page changing the tab active (New position removes the anchor tag already)
- On the learn page or tag pages when …
> DEVHUB-397 [Part 3]: Ensure Page Scroll if Anchor Link Exists

- src/components/dev-hub/global-nav.js
- src/components/dev-hub/menu-toggle.js
- src/components/dev-hub/nav-item.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-389-initial-layout/)
This PR just marks a point to check-in the initial layout and behavior of a mobile-friendly version of the new nav, it is by no means ready for production.
This PR adds the following:
- A toggle-able hamburger menu icon lifted from University which open/closes the menu when on mobile
- An absolutely-positioned list of mobile menu options
Next steps:
- Fix padding/spacing on nav items
- Make nav items full width
- Capture focus or make height 100% when menu is open
> DEVHUB-389 [Part 1]: Initial Mobile Nav Layout

- src/components/dev-hub/nav-item.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-389-sizing/)
This PR continues to clean up the mobile-nav layout by doing the following:
- Sets up a flexbox for laying out the title vs arrow icon
- Cleans up padding for elements on mobile, moves padding css out of the shared `css` object.
- Swaps the dropdown menu to `position: relative` on mobile.
Again, this is not 100% ready for production, but this PR gets the layout closer.
> DEVHUB-389 [Part 2]: Clean up Padding, Layout for Expanding Menus

- src/components/dev-hub/global-nav.js
- src/components/dev-hub/nav-item.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-389-full/)
This PR updates the mobile nav behavior when expanded to do the following:
- Expand at least the full height remaining (below the initial nav bar)
- Disable parent scrolling while the nav is open
- Allow the user to scroll if needed
- Restore normal scrolling when closed
I also fixed a desktop bug opened by moving spacing logic out of some shared CSS
> DEVHUB-389 [Part 3]: Full-height Mobile Nav Experience

- src/components/dev-hub/global-nav.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-430-desktop/)
This PR adds a slight offset to the desktop home logo SVG to align it with other text.
Before:
After:
> DEVHUB-430 [Desktop]: Add slight SVG-related offset for desktop graphic

- src/components/dev-hub/nav-item.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/link-full-width/)
This PR fixes a UX issue with the forthcoming nav where "Direct links" (or links that went to external sites) at the top level had a smaller target area than dropdowns. This was because we didn't give the `Link` the full size available.
The solution was to clean up the tree a bit so these links just used the same exact styling as other headers, but instead used the `Link` component as opposed to a `div`.
> Increase Direct Link Target Area

- src/components/dev-hub/global-nav.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/fix-logo-padding/)
This PR fixes a bug where using negative margin consequentially changed the nav height on desktop. Using `transform` removes this issue.
> Use transform instead of negative margin for logo

- src/templates/project.js
[Staging (single project page)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-306/project/database-development-dcp)
This PR simply adds the CTA and GH Student Pack components to the student project template. I added some padding for the CTA which may change as we add in "explore more student projects"
> DEVHUB-306:  Add CTA and GH Student Pack to Project Page

- src/components/dev-hub/icons/arrowhead-icon.js
- src/components/dev-hub/nav-item.js
- src/components/dev-hub/select.js
[Staging (Not in use yet)](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/chevron-directions/)
This PR adds a new `right` arrow option for the `ArrowheadIcon` component. We also swap the direction indicator from being a binary to being more scalable.
I also noticed the up/down rendered JSX was essentially identical aside from one path `d` value, so I combined these for clarity.
> Add right arrow option to ArrowheadIcon

- src/components/pages/project/additional-projects.js
- src/components/pages/project/index.js
- src/templates/project.js
[Staging (single project)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-307/project/go-fifa)
This PR adds the "explore more student spotlights" section to the project pages. The algorithm for determining which to feature is naive and is as follows:
- Pull all projects (limit to 5)
- Filter out any with the same name
- Limit to 4 and map to the correct interface
Ideally, we would randomize these to get more exposure to all projects, but would like to confirm with product how this should behave exactly. The algorithm can be updated separately of the design.
> DEVHUB-307: Add Explore More Projects (Desktop)

- src/components/pages/project/index.js
- src/components/pages/project/sidebar-content.js
- src/components/pages/project/students.js
- src/components/pages/project/tools-used.js
- src/queries/fragments/project.js
- src/queries/projects.js
- src/templates/project.js
- src/utils/transform-project-strapi-data.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-445/project/go-fifa)
This PR adds the rest of the sidebar content for a project, including the "Tools used", GitHub Link (if provided), and Project Link (if provided). For these we had to add the `github_url` and `project_link` into the GraphQL query.
> DEVHUB-445: Add rest of Sidebar Content

- src/pages/academia/students/index.js
- src/templates/project.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/titles/)
This PR adds page `title` tags, as well as some of the basic SEO skeleton for the project template pages. I imagine we will fill these in more later, but missing page `title`s was a glaring need.
> Add page titles, basic SEO to gallery and projects

- src/components/ComponentFactory.js
- src/components/Image.js
- src/components/List.js
- src/components/Reference.js
- src/templates/project.js
[Staging (Project with images, link, list)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-442/project/EHRS-Peru)
This PR adds support for rendering three items coming from Strapi by augmenting our existing parsing implementation from the component factory:
- Images (needed to support `url` on `nodeData`)
- Unordered Lists (needed to support `ordered` on `nodeData`)
- Links (Needed to add `link` type to component factory and support `url` on `nodeType`).
An alternative approach could have been to distinguish the type to be specific to Strapi, but these changes are small enough to just integrate into our existing components.
> DEVHUB-442: [Part 1] - Render Unordered Lists, Links, Images from Strapi

- cypress/integration/author.js
- cypress/integration/community.js
- cypress/integration/home.js
- cypress/integration/learn.js
- cypress/integration/tag.js
- gatsby-config.js
- gatsby-config.prod.js
- package-lock.json
- package.json
- src/components/dev-hub/link.js
- src/utils/add-trailing-slash-if-missing.js
- src/utils/get-article-share-links.js
- tests/unit/Reference.test.js
- tests/unit/__snapshots__/Heading.test.js.snap
- tests/unit/__snapshots__/Link.test.js.snap
- tests/unit/__snapshots__/Reference.test.js.snap
- tests/utils/add-trailing-slash-if-missing.test.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-384/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-384)
This PR fixes an SEO issue regarding additional 308 redirects. Here, we build pages with trailing slashes using the [force-trailing-slashes](https://github.com/jon-sully/gatsby-plugin-force-trailing-slashes) plugin. In addition:
- Any internal `Link`s should have a trailing slash
- Any internal `Link`s should respect query params or anchor links when navigating and keep those on the end
- The article share copy button should copy a link with a trailing slash
Some of these features are more about DEVHUB-423 which deals with internal links, but I also felt it was appropriate ti lay some groundwork here
> DEVHUB-384: Build, Link to Pages with Trailing Slashes

- src/components/dev-hub/image-gallery.js
- src/queries/projects.js
- src/templates/project.js
- src/utils/transform-project-strapi-data.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-304)
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-304-additional/project/go-fifa/)
This PR adds support for `additional_images` for a project to show up on the project page. These image thumbnails in the bottom right can be clicked on to open the image in the main view.
> DEVHUB-304 (Part 2): Add support for additional_images for a project

- package-lock.json
- package.json
- src/components/pages/student-submit/form/dropzone-thumbnail.js
- src/components/pages/student-submit/form/image-dropzone.js
- src/components/pages/student-submit/form/project-info.js
- src/components/pages/student-submit/form/submit-form-fieldset.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-309/academia/students/submit/)
This PR uses a lightweight NPM package called `react-dropzone` to construct the project image upload section of the submission form for student spotlights.
The next step will be improving the UX to allow for an easier choice of which image is the main one.
> DEVHUB-309 [Part 1]: Add react-dropzone backed Image Upload

- src/pages/index.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-458)
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-458/)
This PR follows a suggestion from Croud to add our brand data to the home page. Since we are using `Helmet` to manage the `head`, we have to use straight-up HTML and cannot export into a different component for perhaps a cleaner solution.
As for the values, I used what www.mongodb.com is using right now, with some obvious substitutions for DevHub
> DEVHUB-458: Add Structured Brand Data

- src/components/pages/student-submit/form/index.js
No staging (since state is not enabled yet for field elements)
This PR updates the logic for validating the student spotlight submit form. Now, we validate a single fieldset before moving onto the next one (instead of incorrectly trying to validate the entire form. We use a `reduce` on the `input`s within the form to check validity since the `FieldSet.checkValidity()` method only returns true.
> DEVHUB-308: Correctly validate at the fieldset level

- src/components/dev-hub/card.js
- src/components/dev-hub/related-articles.js
- src/components/dev-hub/stories/card.stories.mdx
- src/components/pages/home/hero.js
- src/pages/learn.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/remove-card-limits/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-461)
This PR removes the truncation set on titles and descriptions from existing cards
> DEVHUB-461: Remove truncation on all cards

- src/components/dev-hub/card.js
- src/components/dev-hub/related-articles.js
- src/components/dev-hub/stories/card.stories.mdx
- src/components/pages/home/hero.js
- src/pages/learn.js
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6022c91dab23346c202a3b7d)
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/revert-648-DEVHUB-461/)
This PR removes the truncation on cards in production.
```
fc38380 Revert 648 devhub 461 (#651) --> revert with truncate at 4 lines
94f2e6f Remove truncation on all cards (#648)
```
> 2nd Deploy: Feb 10th 2021

- src/pages/learn.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/fix-slash-on-filters/)
This PR fixes a bug where the filters on the learn page unintentionally removed the trailing slash off of `/learn/`. We would like to keep this.
To test:
- Go to the learn page
- Turn on a filter (or any combination of filters)
- Verify the url has `/learn/?...`
- Remove filters
- Verify the url has `/learn/...`
> DEVHUB- 463: Fix trailing slash not staying when filtering on learn

- src/components/dev-hub/global-nav.js
- src/components/pages/home/hero.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/add-missing-keys/)
This PR adds missing `key` fields to two components:
- Top nav items
- Featured items on the home page
We were seeing console errors for these. This PR now resolves those. I also swapped to a named export for the `GlobalNav`
> Add missing keys to nav and featured home page items

- src/components/pages/student-submit/form/image-dropzone.js
- src/components/pages/student-submit/form/index.js
- src/components/pages/student-submit/form/project-info.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-313-images/academia/students/submit/)
This PR adds in the state of the image dropzone properly into our reducer and also allows for proper validation when all images are removed. Using the available ref on the dropzone, we can hook into the `input` and clear the value if there are no more images we are tracking. The only programatic value that can be used for an `input type="file"` is the empty string, so that is why we chose it here.
> DEVHUB-313: Clear Image Dropzone State for Validation

- src/components/pages/student-submit/form/index.js
- src/components/pages/student-submit/form/new-student-fieldset.js
- src/components/pages/student-submit/form/promote-yourself.js
- src/components/pages/student-submit/form/single-student-fieldset.js
- src/utils/student-spotlight-reducer.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-312-multiple-edit/academia/students/submit/)
This PR addresses the need to manage when elements in the form expand/collapse between sections as well as working with multiple students. I went for the array approach since it is scalable and straight forward to understand, although with all the spreads I am sure somewhere we can improve performance slightly.
The key for students is in our representation if the last student is "empty" (meaning any field that isn't a default one for state is null), we remove it which helps keep our state in order.
> DEVHUB-312 [Part 2]: Properly track form expand states

- src/components/pages/student-submit/form/project-info.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-478/academia/students/submit/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-478)
This PR removes client-side requirement of the GitHub URL on the student spotlight form. This already is not required by the CMS so removing this validation is all we needed to do in order for it to be optional.
> DEVHUB-478: Make GitHub URL not required

- src/components/dev-hub/article-share-footer.js
- src/components/dev-hub/grid.js
- src/components/dev-hub/project-title-area.js
- src/components/dev-hub/student-spotlight/github-student-pack.js
- src/components/dev-hub/theme.js
- src/components/pages/project/tools-used.js
- src/components/pages/students/gallery-hero-banner.js
- src/templates/project.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-grid/)
This PR begins to work on mobile-responsiveness for student spotlights by using the given `grid` and adding new tablet/mobile values to it. This is a checkpoint as there is still more work to be done, but here is a list of changes:
- Uses new tablet/mobile grids on the project pages
- Swaps layout of top elements on project pages
- Removes extreme padding from GH student pack component on mobile
- Drops GH student pack link sizing to P2
- Moves ArticleShareFooter into new slot on grid
> DEVHUB-444 [Part 1]: Begin Implementing Grid

- src/components/dev-hub/grid.js
- src/components/pages/academia/project-grid.js
- src/components/pages/project/additional-projects.js
- src/components/pages/students/all-projects.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-grid-ratio/)
This PR begins to add some mobile props to the Grid to allow for better-responsive layouts. With this we currently updated the grid on the academia entry page, gallery page, and project pages
> DEVHUB-444 [Part 3]: Add Mobile Options to Grid

- src/components/dev-hub/author-image-list.js
- src/components/dev-hub/grid.js
- src/components/dev-hub/media-block.js
- src/components/pages/home/academia-feature.js
- src/components/pages/project/additional-projects.js
- src/hooks/use-ref-dimensions.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-responsive-grid/)
This PR adds some JS logic to the Grid to make it properly responsive on various device widths. There was some work that also needed to be done to the MediaBlock since it was giving us a width of 16px for some reason. I noticed modifying this also seemed to impact rendering of other images on the home page which should not happen. This is another bug but will be addressed in future iterations of the home page.
> DEVHUB-444 [Part 4] - Maintain 1:1 Aspect Ratio for Grid

- src/components/dev-hub/academia-sign-up-form.js
- src/components/pages/academia/project-grid.js
- src/components/pages/academia/top-banner.js
- src/components/pages/educators/how-to-join.js
- src/components/pages/educators/sign-up-modal.js
- src/components/pages/educators/top-banner.js
- src/components/pages/students/gallery-hero-banner.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-478-part-1/)
[UAT Sheet](https://docs.google.com/spreadsheets/d/10bDBzs-QnbaF5vdo19a1JRw-ALdaNZLOcS4Bil92joQ/edit#gid=0)
This PR begins addressing cosmetic concerns on Student Spotlight. Namely, this PR:
- Swaps the link tertiary hover state to green and removes the transition used
- Fixes a bug where the academia educators form submission kept the additional top copy
- Swapped copy to greyLightTwo in several headers
- Cleaned up text sizes in the bulleted list of how to join on the educators page
> DEVHUB-478 part 1

- src/components/dev-hub/blog-tag-list.js
- src/components/dev-hub/hero-banner.js
- src/components/pages/academia/top-banner.js
- src/components/pages/educators/program-benefits.js
- src/components/pages/educators/top-banner.js
- src/components/pages/project/sidebar-content.js
- src/components/pages/students/featured-project.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-478-part-3/)
[UAT Sheet](https://docs.google.com/spreadsheets/d/10bDBzs-QnbaF5vdo19a1JRw-ALdaNZLOcS4Bil92joQ/edit#gid=0)
This PR continues with the design alterations for Student Spotlight. Namely:
- Removing the tag hover state if navigation is off
- Exposing the `background-position` on the Hero Banner Image for more fine desktop use
- Restricting the benefit graphics on the educator page to 200px wide max
- Making a few links bold and ensuring clickable areas are appropriate
> DEVHUB-478 [Part 3]

- src/components/dev-hub/blog-tag-list.js
- src/components/dev-hub/image-gallery.js
- src/components/dev-hub/project-title-area.js
- src/components/pages/project/sidebar-content.js
- src/components/pages/project/students.js
- src/components/pages/project/tools-used.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-478-part-4/)
This PR continues work on cosmetic design tweaks for Student Spotlight. Here we:
- Shrink the Hero section on projects to move content above the fold on most machines
- Fix image resolution issues on the image gallery and fix the size of the current image
- Exposes a prop to remove the condensed view of the blog tag list
- Adds `target="blank"` to several links
> DEVHUB-478 [Part 4]

- src/components/pages/student-submit/form/dropzone-thumbnail.js
- src/components/pages/student-submit/form/promote-yourself.js
- src/components/pages/student-submit/form/single-student-fieldset.js
- src/components/pages/student-submit/form/submit-form-fieldset.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-480/academia/students/submit/)
This PR fixes a bug where on collapse we remove student forms from the DOM. This would cause the photo selected to be lost because the file input is uncontrolled.
I also fixed the object-fit for thumbnails above in the form and cleaned that up a bit, as well as added `window.confirm` before removing a student.
> DEVHUB-480: Don't Remove Fieldset from DOM

- src/components/dev-hub/grid.js
- src/components/dev-hub/project-card.js
- src/components/dev-hub/student-spotlight/github-student-pack.js
- src/components/pages/academia/project-grid.js
- src/components/pages/academia/students-educators-details.js
- src/components/pages/educators/how-to-join.js
- src/components/pages/educators/program-benefits.js
- src/components/pages/project/additional-projects.js
- src/components/pages/students/all-projects.js
- src/components/pages/students/featured-project.js
- src/pages/academia/students/index.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-nitpicks/)
[Figma](https://www.figma.com/file/QuUf86imwSoPNYoxZX3az2/Academia---Student-Spotlights?node-id=1231%3A2529)
This PR clean up mobile-responsive behavior and sticks to our Figma for mobile styling. Here is what was updated in this PR:
Academia entry page:
- Swapped text color to more white on mobile since hover state is less prevalent on mobile
Educators Page:
- Fixed padding throughout
- Removed centering of text
- Fixed margins throughout
- Swapped ordering of bottom section on mobile
Gallery page:
- Made the featured project responsive
- Adjusted padding throughout
Misc:
- Removed extra content on project cards on mobile
- Let the GitHub image scale appropriately
- Fixed issues …
> DEVHUB-444 [Part 5]: Nitpicks

- src/components/pages/student-submit/form/condensed-student-entry.js
- src/components/pages/student-submit/form/dropzone-thumbnail.js
- src/components/pages/student-submit/form/image-dropzone.js
- src/components/pages/student-submit/form/index.js
- src/components/pages/student-submit/form/new-student-fieldset.js
- src/components/pages/student-submit/form/project-info.js
- src/components/pages/student-submit/form/promote-yourself.js
- src/components/pages/student-submit/form/submit-form-fieldset.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-form/academia/students/submit/)
This PR adjusts the project submission form for Student Spotlights to be more mobile-responsive. Here are the highlights:
- Enable the `AuthorImage`s to show on mobile
- Adjust some top/side padding for larger input sizes
- Cleans up the image dropzone grid so we don't have to do manual setting of grid rows on the children
> DEVHUB-444 [Part 6]: Form Responsiveness

- src/components/dev-hub/input-label.js
- src/components/pages/student-submit/form/condensed-student-entry.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-labels/academia/students/submit/)
This PR updates the `labels` for inputs/textareas to prevent them from wrapping onto the next line. This PR also uses a new grid for the condensed view of a student when submitting, like so:
> DEVHUB-444 [Part 7]: Fix input label overflow, student view

- src/components/dev-hub/media-block.js
- src/components/dev-hub/modal.js
- src/components/pages/academia/students-educators-details.js
- src/components/pages/educators/how-to-join.js
- src/components/pages/home/academia-feature.js
- src/components/pages/student-submit/form/promote-yourself.js
- src/components/pages/students/featured-project.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-cleanup/)
This PR cleans up some mobile-specific issues for Student Spotlight. Here are the highlights:
- Adds a new prop to `MediaBlock` which lets us reverse the order of content on mobile
- Decreases the amount of padding on modals for mobile displays by default to 8px
- Drops the size of images on the academia entry page
- Properly aligns content on the "How to Join" section
- Makes the featured project image a link
- Adds scrolling to top of the form section when a new student is added
> DEVHUB-485 Mobile Cleanup

- src/components/dev-hub/image-gallery.js
- src/components/dev-hub/student-spotlight/share-project-cta.js
- src/components/pages/project/students.js
- src/templates/project.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-444-project-page/project/go-fifa/)
This PR clean up non-responsive elements of the project page, including the image gallery. Namely:
- Swaps image gallery to CSS grid and changes layout for mobile
- Removes bottom border from students list on mobile
- Adds 16px padding on the left and right for the share CTA component (since it is now below max width)
> DEVHUB-444 [Part 8]: Mobile Project Page

- src/components/pages/academia/students-educators-details.js
- src/components/pages/educators/program-benefits.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-314-alt/)
This PR adds some `alt` tags for `img`s added in the student spotlight project
> DEVHUB-314: Add alt tags for other student spotlight images

- src/components/pages/student-submit/form/image-dropzone.js
- src/components/pages/student-submit/form/index.js
- src/components/pages/student-submit/form/main-image-dropzone.js
- src/components/pages/student-submit/form/project-info.js
- src/utils/on-student-spotlight-form-submission.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-485-split-form/academia/students/submit/)
This PR switches the functionality of the image collection for student spotlight projects to have a separate `input` for the Main Image versus the Additional Images. This makes choosing the main image for a project more intuitive since we don't have drag/drop or so.
This logic can definitely be generalized and refactored and that will come next. The first step is making the functional change and then we will refactor both the image-dropzone to generalize as well as the upload logic to batch everything together.
> DEVHUB-485: Split Images in Form (v1, Pre-refactor)

- src/components/Heading.js
- src/utils/setup/parse-markdown-to-ast.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-485-fix-headings/project/database-development-dcp/)
This PR adds support for the `depth` property coming from Headings from strapi. This let's us properly render a heading as H1-5. It should not impact existing articles but project pages should now have a more clear hierarchy.
> DEVHUB-485: Add support for depth property on nodeData for headings

- src/utils/on-student-spotlight-form-submission.js
- src/utils/upload-images-to-strapi.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/fix-submission-form/academia/students/submit)
This PR fixes a security issue with how we were uploading images to Strapi. Now we use a Realm webhook which acts as a pass-through which forwards requests to Strapi.
> Use Realm Webhook for HTTPS FormData Pass Through

- src/pages/academia/index.js
- src/pages/academia/students/index.js
- src/pages/academia/students/submit.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/fix-spotlight-og/academia/)
This PR updates the logic for generating OG links on several static pages. This actually populates the tag correctly at build-time as `location` is provided at build time.
> DEVHUB-500: Fix OG:URL /*/ bug on Academia Static Pages

- .gitignore
- gatsby-config.js
- gatsby-config.prod.js
- package-lock.json
- package.json
- static/sitemap.xml
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-509/sitemap.xml)
This PR updates the logic for the sitemap to use a sitemap-index to point to the DevHub sitemap (now moved) as well as the Community Forums sitemap.
The cleanest way found was to generate a static xml file for the index to the two and use that while updating the location of the existing sitemap. This lets us keep the existing sitemap as-is and add in the new content without breaking past changes.
> DEVHUB-509: Convert to using sitemap-index

- src/components/pages/home/hero.js
- src/pages/learn.js
- src/utils/get-featured-card-fields.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-498/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-498)
This PR adds `tck` params to articles on the home and learn pages based on the above JIRA request. My approach involved just updating the function we used to generate the fields for featured cards and adding another parameter for the page name.
> DEVHUB-498: Add tracking param to featured articles on home/learn pages

- src/components/dev-hub/breadcrumb-schema.js
- src/components/dev-hub/breadcrumb.js
- tests/unit/BreadcrumbSchema.test.js
- tests/unit/__snapshots__/BreadcrumbSchema.test.js.snap
- tests/unit/data/BreadcrumbSchema.test.json
This PR adds schema for breadcrumbs. Breadcrumb structured data can be used to mark-up breadcrumb navigation links and provide search engines with additional information on the hierarchy and structure of the website.
> DEVHUB-457: Structured data breadcrumbs: Implement breadcrumb schema to all pages

- src/components/dev-hub/hero-banner.js
- src/components/pages/academia/top-banner.js
- src/components/pages/student-submit/top-banner.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-527/)
This PR fixes a bug which did not constrain the aspect ratio of the hero image on articles, etc. on mobile. For some pages, we still don't mind leaving the ratio alone so we disable this behavior selectively.
> DEVHUB-527: Maintain 1:1 Hero Image Aspect Ratio on Mobile

- src/components/dev-hub/global-nav.js
- src/components/dev-hub/searchbar/CondensedSearchbar.js
- src/components/dev-hub/searchbar/ExpandedSearchbar.js
- src/components/dev-hub/searchbar/Pagination.js
- src/components/dev-hub/searchbar/SearchDropdown.js
- src/components/dev-hub/searchbar/SearchResult.js
- src/components/dev-hub/searchbar/SearchResults.js
- src/components/dev-hub/searchbar/SearchTextInput.js
- src/components/dev-hub/searchbar/Searchbar.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-515/)
[Figma](https://www.figma.com/proto/alg7BWjspWbpLmys9vS4KC/DevHub-Search?node-id=31%3A2711&scaling=min-zoom)
I expect CI to still fail while we mess with the mobile nav. So long as that is the sole issue we can merge into the staging branch since we will come back to this anyway.
This PR applies the majority of the DevHub search reskin to the new search UI. I also removed some dead code and such. This should remove all `uiColors` uses (aside from some uses on `upToSmall` which will be removed when it is time to do mobile).
> DEVHUB-515: Apply Design Reskin

- src/components/dev-hub/searchbar/SearchDropdown.js
- src/components/dev-hub/searchbar/SearchResults.js
- src/components/dev-hub/searchbar/Searchbar.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-216-2/)
[Figma](https://www.figma.com/proto/alg7BWjspWbpLmys9vS4KC/DevHub-Search?node-id=188%3A5061&scaling=min-zoom)
This PR addresses two quick mobile changes for search, updating the results background color and removing the 9 limit for results.
> DEVHUB-516 (part 2): Swap mobile color, remove limit for results on mobile

- src/components/dev-hub/global-nav.js
- src/components/dev-hub/nav-item.js
- src/components/dev-hub/searchbar/SearchResults.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-544-1/)
[Figma](https://www.figma.com/file/alg7BWjspWbpLmys9vS4KC/DevHub-Search?node-id=213%3A33)
This PR addresses some small search ui related fixes:
- Expand on 1200+px by default only
- Swaps color scheme for mobile
- Makes padding on nav 24px for all above ~1000px
- reduces result space on mobile
> DEVHUB-544 (part 1): Padding, Mobile Colors, Default Expand

- src/components/dev-hub/searchbar/CondensedSearchbar.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/search-top-ui/)
This PR fixes a small visual glitch where using `background-color: none` would cause a flash of grey on the magnifying glass when using SSR.
> DEVHUB-544 (part 2): Use an initial color for SSR

- cypress.json
- cypress/integration/search.js
- src/components/Link.js
- src/components/dev-hub/global-nav.js
- src/components/dev-hub/link.js
- src/components/dev-hub/searchbar/SearchResult.js
- src/components/dev-hub/searchbar/Searchbar.js
- src/utils/show-on-device-size.js
- tests/unit/__snapshots__/Heading.test.js.snap
- tests/unit/__snapshots__/Link.test.js.snap
- tests/unit/__snapshots__/Reference.test.js.snap
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-544-flash/)
This PR addresses an SSR issue with the searchbar. Previously, the logic for expand/collapse was a bit complicated, so we used a `useMedia` hook to render the same searchbar if expanded or condensed. This resulted in some jittering on renders due to SSR, since the condensed state would be the default state when building HTML.
This approaches uses a different SSR responsive-layout pattern (similar to artsy/fresnel) where we ship two layout options and use CSS to render the correct one. While the DOM get slightly larger, the UX benefit is far greater in this case, since we would not add significant code being sent. This is also not duplicate-content, so it should not have SEO impacts. …
> DEVHUB-544: Flash on UI, Forward Refs on Links

- src/components/dev-hub/searchbar/Pagination.js
- src/components/dev-hub/searchbar/SearchDropdown.js
- src/components/dev-hub/searchbar/SearchResults.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-555-mobile/)
This PR updates the colors for pagination and fixes a bug where iOS scrolling would break the container of the search results.
> DEVHUB-555: Mobile UI Issues, Pagination Color

- package-lock.json
- package.json
- src/components/dev-hub/global-nav.js
- src/components/dev-hub/searchbar/ExpandedSearchbar.js
- src/components/dev-hub/searchbar/SearchContext.js
- src/components/dev-hub/searchbar/SearchDropdown.js
- src/components/dev-hub/searchbar/SearchLoader.js
- src/components/dev-hub/searchbar/SearchResults.js
- src/components/dev-hub/searchbar/Searchbar.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-555-active/)
This should be the last round of improvements for the new search UI, namely:
- Uses `shouldAutofocus` for a better UX
- Adjusts active state colors
- Adds Leafy hooks into the project
- Adds a loader
- Pulls out the width transition as this was pushing content off the screen
> DEVHUB-555: Misc Accessibility/UX

- package-lock.json
- package.json
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/strapi-plugin-alpha/)
This PR upgrades the Strapi source plugin to `1.0.0-alpha.0`. Although it is `alpha`, it has been active for about four months and is the newest version. Most changes are dep bumps under the hood.
> Bump gatsby-source-strapi to 1.0.0-alpha.0

- src/components/dev-hub/searchbar/ExpandedSearchbar.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-565/)
This PR simply uses the `Article` tab on the learn page when completing a search.
> DEVHUB-565: Add article tab query param

- src/components/dev-hub/searchbar/ExpandedSearchbar.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-565/)
```
4c272dbd DEVHUB-565: Add article tab query param (#728)
```
> Deploy DEVHUB-565: Add article tab query param (#728)

- cypress/integration/strapi-author.js
- gatsby-node.esm.js
- src/utils/setup/create-strapi-author-pages.js
- src/utils/setup/create-tag-page-type.js
- src/utils/setup/get-author-list-from-graphql.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-546-article-pop/author/lauren-schaefer/)
This PR finishes the work needed to support Authors from Strapi (without Strapi articles yet). We pull articles in from Snooty should they exist. We also now clearly make an author's page using CMS data if available, matching based on name.
> DEVHUB-546: Pull in Snooty Articles

- src/components/Link.js
- src/utils/is-link-for-image.js
- src/utils/make-link-internal-if-applicable.js
- tests/utils/is-link-for-image.test.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-570/)
Some broken links included links to image files, which were being applied with trailing slashes. This PR isolates this case and removes trailing slashes from links to images.
> DEVHUB-570: Don't add trailing slashes to internal image links

- src/components/dev-hub/related-articles.js
- src/components/dev-hub/searchbar/SearchResult.js
- src/utils/make-link-internal-if-applicable.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-559-related/)
This PR follows the broken picture links PR by adding an optional param to enable `withPrefix` for internal links that are referenced as external links.
> DEVHUB-559: Fix Staging Internal Links

- gatsby-node.esm.js
[Staging](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25c77c5/devhub/docsworker-xlarge/march-19-21/quickstart/node-connect-mongodb/)
This PR adds some quick Gatsby-side redirects for the UI-elements which point to redirected content. This was done on Fastly but with Gatsby's internal linking setup we also need to add these here to totally redirect.
This will be fast-followed by a CMS-friendly change to allow these to be done without code deploys.
> Add Gatsby redirects for Node Connect pages

- gatsby-node.esm.js
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6058f2d42723a9e448aa58e1)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25b048a/devhub/docsworker-xlarge/node-redirects/)
```
93e1b388 Add Gatsby redirects for Node Connect pages (#739)
```
> Add Gatsby redirects for Node Connect pages (#739)

- gatsby-config.js
- gatsby-config.prod.js
- gatsby-node.esm.js
- src/queries/client-side-redirects.js
- src/utils/setup/create-client-side-redirects.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-574/)
This PR builds off of the previous redirect work to add support for client-side redirects to come from the CMS. The two existing redirects are kept, the infrastructure has just moved to Strapi for easier handling.
> DEVHUB-574: Add CMS Support for Gatsby Redirects

- cypress/integration/search.js
- src/components/dev-hub/searchbar/Searchbar.js
[Try it out here](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-549-ff/)
I noticed the Slash did not work on Firefox because Firefox opens a quick find window with that key. We need to use `preventDefault` in order to block that. I also swapped the event from keyUp to keyDown so it would work as soon as the key has been pressed. I also shortened the UI test and was able to omit the `wait`
Give it a try with the link above!
> DEVHUB-549: Ensure slash key works on Firefox

- gatsby-node.esm.js
- src/queries/search-article-rss-data.js
- src/utils/setup/create-article-node.js
- src/utils/setup/replace-directives-in-content.js
- src/utils/setup/serialize-search-rss-data.js
- tests/utils/create-article-node.test.js
[Staging Search XML](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-553/search-rss.xml)
This PR adds a field called `raw_content` ONLY to the search XML file (to prevent page bloating and slowing build times) from a new Snooty Realm App function. This right now is the straight-up file content of the article but in Realm we removed various rST syntax, such as directive definitions and options, long strings of `-` and `=`s.
Once this is in, we can update the webhook to index and search.
> DEVHUB-553: Add Article raw_content to search XML

- .github/workflows/devhub-ci-test.yaml
- .github/workflows/devhub-npm-test.yaml
I have tried to run testing (unit and e2e) and Gatsby scripts on my local machine with node 14. Looks all is fine. This PR just updates config.
> DEVHUB-508: Upgrade General Support to Node 14

- src/pages/learn.js
This PR fixes pop-up on Search Results. The problem is in 'articles' and 'ActiveCardList' component. When we have some result from search bar - 'articles' will be empty, that why the scrollbar is blinking.
> DEVHUB-566: Fix Pop-up on Search Results - MongoDB

- gatsby-node.esm.js
- src/components/dev-hub/SEO.js
- src/components/dev-hub/byline-block.js
- src/components/dev-hub/card-list.js
- src/queries/articles.js
- src/templates/strapi-article.js
- src/templates/tag.js
- src/utils/setup/create-strapi-article-pages.js
- src/utils/setup/create-strapi-author-pages.js
- src/utils/transform-article-strapi-data.js
[Staging Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-545-authors-seo/how-to/realm-test/)
This PR is another check in for DEVHUB-545. I started to deviate from the adapter pattern in some places where we were making things more convoluted just to use Snooty. It includes:
- Support for authors
- Support on Author pages
- Twitter Social Share support
Next will be:
- Setting up UI testing
- (New ticket) Adding articles to other tag/learn pages
> DEVHUB-545 [Part 2]: Add Authors, Twitter

- src/templates/strapi-article.js
- src/utils/find-section-headings.js
- src/utils/setup/parse-markdown-to-ast.js
[Staging Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-545-TOC/how-to/realm-test/)
This PR finishes off rendering the basic Strapi article content by adding heading content to the TOC. To do this, we did the following:
- Added the `id` field to headings to match Snooty's
- Updated the `find-section-headings` logic to check at a various `minDepth`.
> DEVHUB-545 [Part 3]: Add Headings to TOC

- src/components/Literal.js
- tests/unit/DefinitionList.test.js
- tests/unit/Literal.test.js
- tests/unit/__snapshots__/DefinitionList.test.js.snap
- tests/unit/__snapshots__/Literal.test.js.snap
[JIRA](https://jira.mongodb.org/browse/DEVHUB-107)
[Staging Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-107/quickstart/golang-multi-document-acid-transactions/)
This PR changes the style for a `Literal` based on the discussions in the linked JIRA ticket. We also update related test snapshots and use the `ThemeProvider` where needed.
> DEVHUB-107: Update literal style

- src/components/dev-hub/cms-form.js
- src/components/dev-hub/feedback/feedback-container.js
- src/queries/fragments/feedback.js
- src/templates/article.js
This PR begins to add logic to support "Generalized Forms", which are forms that can be re-used with incoming data about the layout of a form.
There is still more work to be done, but this begins to allow us to render forms more easily.
We should be sure of the following:
- Form state works appropriately
- Form labels/placeholders work appropriately
We will add some tests for this when the full project is coming together, but for now we can continue to clean this up so we can keep moving on the project.
> DEVHUB-592: Create a Generalized Form

- src/components/dev-hub/series.js
[Staging Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/fix-series-css/how-to/attribute-pattern/)
After migrating to emotion 11 we lost the breadcrumbs in series. This PR fixes that.
> Fix series CSS post emotion 11

- gatsby-node.esm.js
- src/components/dev-hub/blog-post-title-area.js
- src/components/dev-hub/icons/clock.js
- src/templates/article.js
- src/utils/setup/create-article-page.js
- tests/utils/create-article-page.test.js
No Review Needed
[Staging Link (Sample Article)](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/add-ttr-to-article/quickstart/php-setup/?tck=feathome)
This PR adds TTR to the header for articles. More cleanup is needed here, such as:
- Turning the clock icon into a component for reuse
- Cleaning up CSS/Number of elements for the `BlogPostTitleArea`
> WIP: Add TTR to Article Headers

- src/constants.js
- src/utils/devhub-api-stitch.js
This PR adds three functions which can be used in the devhub feedback project for handling actions with the modal. They are as follows:
- `createFeedback` which is to be called when the modal is opened. This creates an object in our DB for handling the user's feedback and returns that id
- `updateFeedback` which is to be called as the user enters more data
- `submitFeedback` which is to be called on completion
These are hosted in our backend-as-a-service on MongoDB Realm. Let me know if it is unclear how we plan to use these, thanks!
> DEVHUB-594 (prep): Add Endpoints for Form Submission

- gatsby-node.esm.js
- src/queries/articles.js
- src/utils/setup/create-article-node.js
- tests/utils/create-article-node.test.js
- tests/utils/create-article-page.test.js
No Review
This PR adds the base logic for pulling in associations from Realm/Atlas at build time to lay the groundwork for building a UI.
> No Review: Add Associations at Build-Time

- src/classes/snooty-article.ts
- src/components/dev-hub/card-list.js
- src/templates/article.js
- src/utils/get-featured-card-fields.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/DEVHUB-585-image-internal/)
This PR fixes a bug in migrating to the `Article` interface where `withPrefix` was being applied inappropriately. Now we use it at build time for assets.
> DEVHUB-585: Fix withPrefix Usage for Article Assets

- package-lock.json
- package.json
- src/utils/parse-podcasts.js
[Staging Site](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/add-podcast-description/learn/)
This PR adds and parses descriptions for podcasts. These are passed in raw HTML so I added a library to parse them for us. We now have ` description` field for the podcasts!
> Add podcast descriptions

- gatsby-node.esm.js
- src/classes/snooty-article.ts
- src/classes/strapi-article.ts
- src/components/dev-hub/blog-post-title-area.js
- src/components/dev-hub/card-list.js
- src/components/pages/home/hero.js
- src/utils/setup/find-articles-from-slugs.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/use-iso-date/)
This PR addresses some fixes after moving to the `Article` interface:
1. Swaps article dates to use ISO Date format
2. Undoes some logic where we set type to `article` for items being featured
3. Adds TOC headings to articles
> Misc Strapi Parity Fixes

- src/utils/setup/parse-markdown-to-ast.js
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/8b11548/devhub/docsworker-xlarge/may-11-21/)
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=609aa3d8e34a64024ac7c373)
```
b2d24ee5 DEVHUB-649: Add support for the charts directive (#805)
```
> DEPLOY DEVHUB-649: Add support for the charts directive (#805)

- plugins/gatsby-source-strapi/package.json
This PR updates lodash as per the dependabot warning for our export of the gatsby-source-strapi plugin
> Update lodash for dependabot warning

- src/components/ArticleRating.js
- src/components/dev-hub/feedback/feedback-container.js
- src/components/dev-hub/feedback/feedback-form.js
- src/components/dev-hub/feedback/star-rating-list.js
- src/components/dev-hub/modal.js
- src/components/dev-hub/star-rating.js
- src/templates/article.js
This PR cleans up some UX related to the devhub feedback project, namely:
- Fixes a bug where touching a star on iOS would fail to do anything
- Adds the stars on mobile to the modal
- Cleans up the iPad layout
- Fixes a bug where the modal would flash the desktop variant on mobile before changing to mobile
> DEVHUB-625: Add Stars to Mobile Design

- src/utils/find-section-headings.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-660/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-660)
This PR updates logic for Strapi headings in which we only want H2 and larger to show on the TOC. Previously we were showing any heading. This does not impact Snooty articles.
> DEVHUB-660: Default to H2 and above for TOC

- src/components/Link.js
[Staging Article](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-653/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-653)
This PR fixes anchor tags from Strapi. We had a case in `Link` to check for an anchor but we didn't explicitly remove any `target="_blank"` and so this was giving some wonky effects.
> DEVHUB-653: Properly render anchor tags from Strapi

- src/utils/setup/transform-author-strapi-data.js
In Strapi, we would fail a build if an author was provided without an image. This should not happen. Here we null check properly.
> Null Check Author Images from Strapi

- src/classes/strapi-article.ts
This PR fixes a bug where we had an extra old param for the heading nodes. Removing this fixes TOC for Strapi articles.
> Remove unused debug param since signature changed

- src/components/Emphasis.js
- src/components/Reference.js
- src/components/Strong.js
- tests/unit/__snapshots__/Emphasis.test.js.snap
- tests/unit/__snapshots__/Strong.test.js.snap
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/use-factory-for-composition/)
This PR makes an improvement to how we render `emphasis` (italics), bold, and links. Previously, we assumed the initial child of this node was text. However, this may be a link, or some other node. As a result, we want to pass the node's children again through the component factory to compose all needed styles.
> Use Component Factory to compose styles

- src/classes/strapi-article.ts
- src/utils/transform-article-strapi-data.js
[Staging Strapi Article
](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/jordanstapinski/use-image-url-social-share/how-to/realm-graphql-demo-custom-resolvers/)
This PR fixes a bug where we were not parsing the image URL for og and twitter images, meaning social share wouldn't render an image
> Correctly get Strapi preview URLs for social share

- src/components/ComponentFactory.js
- src/components/Table.js
- src/components/TableCell.js
- src/components/TableRow.js
[Staging (article with table)](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/jordanstapinski/DEVHUB-651/how-to/realm-test/#fourth-heading)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-651)
This PR adds support for three new directives which are Strapi-exclusive to use tables. The Snooty `ListTable` concept really doesn't map well to the Markdown concept of a Table. Also, these tables support embedding images, inline code, etc!
This is not in production use yet, the above article is just one for testing Strapi rendering.
> DEVHUB-651: Add Table, TableRow, and TableCell support for Strapi

- src/components/dev-hub/card-list.js
- src/pages/learn.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-670/)
This PR fixes a long-standing bug where search results on the learn page were being sorted by date. This was not present in the top searchbar. As a result of this PR, the searchbar is now in sync with the learn page.
> DEVHUB-670: Don't sort by date for search results

- src/components/dev-hub/feedback/feedback-container.js
- src/templates/article.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-666/)
After #792 we made some interface changes that were not properly updated on this feature branch to get the title and names for authors. This PR fixes those differences by getting `authors` instead of `author` and just uses `title` without needing to delve for a `value`
> DEVHUB-666: Fix feedback missing title, authors, inconsistent slashes

- src/components/ArticleRatingContext.js
- src/components/dev-hub/feedback/feedback-container.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-665/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-665)
This PR changes the behavior of the last modal (confirmation) which allows the modal close behavior and the CTA button behavior to be the same. We will keep the star rating showing so long as they get to the last modal regardless of how they close out of it.
I also added some ESLint ignores for the fallthrough logic since it is intentional.
> DEVHUB-665: Don't clear stars if is last modal

- src/components/dev-hub/feedback/feedback-container.js
- src/components/dev-hub/feedback/feedback-final-step.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-625-modal-styling/)
[Figma](https://www.figma.com/file/3p41Tj1q8K5T5wZzOMOiff/DevHub---Sentiment-Score?node-id=193%3A256)
This PR makes some changes to the style of the feedback modal. Specifically:
- Removes the border from the modal on mobile as it is full screen
- Adds padding to the last modal to be consistent with the other modals before
> DEVHUB-625: Remove Modal Border, Add Last Modal Padding

- cypress/integration/article.js
- src/components/dev-hub/blog-share-links.js
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-625-exposed-links/)
This PR updates the UX for copying a link from the article share on the side. This reverts the behavior to what we have on production which is to swap to a check mark which looks like the following:
We also added hover states to the icons to change the color as we had in PROD.
> DEVHUB-625: Use old check UX for copy, change hover color

- src/components/dev-hub/feedback/feedback-form.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-625-inconsistent/)
This PR makes a change to the layout of the feedback form where we remove the `inline-block` display from the `description` and instead use a `div` to assign margin to the bottom. We noticed using the inline option was causing the space between the title and description to become inconsistent if the description spanned multiple lines.
> DEVHUB-625: Use consistent spacing for text elements on modals

- src/components/dev-hub/article-share-footer.js
- src/components/dev-hub/blog-share-links.js
- src/components/dev-hub/contents-menu.js
- src/components/dev-hub/controlled-tooltip.js
- src/components/dev-hub/hover-tooltip.js
- src/components/dev-hub/icons/link-icon.js
- src/components/dev-hub/icons/linkedin.js
- src/templates/article.js
- src/templates/podcast.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/add-exposed-links/)
This PR mimics #804 to expose the links on the sides for the podcast pages. I also made sure to keep the tooltip text customizable. This way, if this project is ready for production first it can be deployed without the need for the devhub feedback project to be ready.
> Podcasts: Add Exposed Links for Social Sharing

- src/components/dev-hub/feedback/feedback-container.js
- src/hooks/use-viewport.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-664/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-664)
This PR add a new hook called `useViewport` which allows us to properly set full heights on mobile where keyboards, etc could interfere with a percentage height. Using a proper viewport correctly solves the problem. The feedback modal should be full height on all sizes/platforms now (tested with an Android emulator)
> DEVHUB-664: Add useViewport hook for mobile

- src/templates/article.js
- src/utils/add-leading-slash-if-missing.js
- tests/utils/add-leading-slash-if-missing.test.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-666-leading/)
This PR adds leading slashes to the slugs recorded for DevHub Feedback to be consistent with the metrics that show for us in Google Analytics. I would have liked to update all of the slugs for Articles but the `slugTitleMapping` has these. A separate feature will be added to ensure leading and trailing slashes for all slugs.
> DEVHUB-666: Add Leading Slashes to Feedback Slugs

- src/components/dev-hub/feedback/feedback-container.js
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-664-zoom/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-664)
One last piece for the DevHub feedback. As a result of #832 we also needed to change the height to be min-height: 100vh and height: fit-content. This allows users who zoom in to also not have the bottom background cut off. The JIRA also was updated with a picture of the broken UI
> DEVHUB-664: Use height: fit-content for zoomed in content

- cypress/integration/top-banner.js
- gatsby-config.js
- gatsby-config.prod.js
- src/components/dev-hub/layout.js
- src/components/dev-hub/top-banner.tsx
- src/utils/setup/schema-customization.js
[Staging Link (Mock Banner)](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-218/)
I expect tests to fail until the corresponding CMS change has been made.
This PR adds logic to consume a new Single Type called `TopBanner`. This has the images for the desktop/mobile banners as well as the target URL. This allows us to change banners in the CMS without any more code changes.
> DEVHUB-218: Support Banners from Strapi

- src/components/dev-hub/layout.js
- static/opensearch.xml
No Staging Needed
This PR cleans two small things for the Open Search Description implementation.
- Removes "Search" from the title as the browser adds it for us
- updates the link to use the `#main` anchor ID
> DEVHUB-596: Cleanup Title and Link

- src/components/dev-hub/top-banner.tsx
[JIRA](https://jira.mongodb.org/browse/DEVHUB-218)
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-218-center/)
This PR changes the banner to center on large screens (as a result of wanting to use img height/width tags)
Before:
After:
> DEVHUB-218: Center Banner on Large Screens

- cypress/integration/article.js
- gatsby-node.esm.js
- src/utils/fuzzy-slug-match.js
- src/utils/setup/remove-duplicated-articles.js
- tests/utils/fuzzy-slug-match.test.js
- tests/utils/remove-duplicated-articles.test.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-709)
This PR fixes some nondeterministic logic that would occur when our writing team begins re-writing content from Snooty (aka the Github/rST way of writing content) in Strapi.
Should an article be created in Strapi with the same "slug" (or URL after the initial developer.mongodb.com), we would create two pages at the same slug in Gatsby, which is nondeterministic. To be safe, this PR adds a case to remove articles from Snooty which have an identical slug in Strapi to ensure we only create one such article page. The requirement is for us to "prefer" the Strapi article.
The actual logic just involves us performing a filter on articles coming from Snooty to see if any have a slug that "fuzzy" matches one in Strapi and if so, remove it. "Fuzzy" …
> DEVHUB-709: Remove Snooty Articles with an identical Slug in Strapi

- gatsby-config.prod-new.js
No staging
To prepare for the upcoming subdomain consolidation, we will need the production config to have a prefix of `/developer`. This way, internal linking works as expected with the subdomain.
Without this, we would just keep linking to mongodb.com/article/... instead of mongodb.com/developer/article.
> DEVHUB-542: Add new config file for subdomain consolidation

- src/components/dev-hub/raw-html.js
[This PR for an Article](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/jordanstapinski/fix-inline-elements/how-to/realm-data-types/)
[Existing Article](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/25c77c5/devhub/docsworker-xlarge/strapi/how-to/realm-data-types/)
This PR checks if someone in Strapi uses HTML that is just a line break. We only want to use `span` for this to be inline and not a `div` since that would make it a block with height. The ask is to remove breaks from `div` and make them a span.
Check out this PR for an article and that same article as it is now from Strapi to see the difference!
> Let inline Strapi elements be inline

- src/templates/article.js
[Staging](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/fix-safari-grid/)
This PR fixes a bug on Safari (I'm not sure when it was introduced) relating to Rate this Article on Safari. I noticed sometimes the rate this article overlays the content of the article. We have the first image, when we want to have the second. This PR updates a CSS property that is not inferred on Safari desktop only (but looks fine elsewhere).
> Fix safari article overlay

- .github/workflows/devhub-ci-test.yaml
- lighthouserc.json
This PR adds a change to our GitHub actions CI testing to add testing two URLs with Google Lighthouse. [This plugin](https://github.com/treosh/lighthouse-ci-action) allows us to identify web performance metrics which can be used to judge the overall health of the site and prevent significant regression.
Google Lighthouse, if you are unfamiliar, is a tool which monitors overall site health and performance in specific areas. It also helps with Search Engine rankings (kind of). You can read up on it [here](https://developers.google.com/web/tools/lighthouse)!
> Add Google Lighthouse Tooling into Github Actions CI

- src/utils/generate-path-prefix.js
This PR adds support for a new environment variable which we can use which allows us to separate which username we use to get reStructuredText content from which username we use for a staging link. This allows us to properly build and stage the platform.
To test:
- Open .env.production
- Add a new line `GATSBY_STAGING_USER=<your computer username, such as sophia.li>`
- run `npm run clean; npm run build; make stage`
- The site should build and stage, with all images/fonts looking good
> Add new ENV option for username customization for staging links

- cypress/integration/strapi-article.js
- src/utils/transform-article-strapi-data.js
[Staging Strapi Article](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-706/how-to/build-ci-cd-pipelines-realm-apps-github-actions/)
[JIRA](https://jira.mongodb.org/browse/DEVHUB-706)
[What is a canonical URL?](https://yoast.com/what-is-a-canonical-url/) (For more context, we had an SEO suggestion that every page should have a canonical URL, defaulting to itself)
This PR changes behavior of articles from Strapi to add a fallback canonical URL if one is not supplied. The canonical URL is an HTML tag with `rel="canonical"` we can see if we inspect the DOM. Previouly, we had no fallback and just let the options be from Strapi be our source of truth absolutely.
> DEVHUB-706: Add Canonical URL Fallback for Strapi Articles

- src/components/dev-hub/global-footer.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-715)
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-715/)
This PR fixes a bug for mongodb.com/developer where the footer was using an absolute link instead of a relative one. This means the DevHub link on the footer went to mongodb.com and not mongodb.com/developer. This PR swaps which link we are using to one that checks if a link is external or internal before determining the appropriate target location.
> DEVHUB-715: Use relative links where appropriate for the footer

- gatsby-config.prod-new.js
- src/classes/search-article-result.ts
[Staging Search on Learn Page](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-710/learn/?content=Articles&text=world)
[Existing new domain search](https://www.mongodb.com/developer/learn/?content=Articles&text=world#main)
This PR fixes a bug where internal images from a search were not being applied with the `pathPrefix`, meaning instead of loading an image from `/developer/images/img` we were looking at `/images/img` which fails.
The solution was to see if an image file is local (starts with a slash) and if so, apply Gatsby's `withPrefix` function to tack on either `/developer` for the new domain or something else for a different build.
To verify, check out the staging link and see the images load whereas on .com/developer they do not!
> DEVHUB-710: Use withPrefix for Search Images

- .github/workflows/devhub-ci-test.yaml
- cypress/integration/strapi-article.js
- gatsby-config.prod-new.js
- lighthouserc.json
- src/classes/search-article-result.ts
- src/components/dev-hub/global-footer.js
- src/utils/generate-path-prefix.js
- src/utils/transform-article-strapi-data.js
[Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=60d35205a1eeec1fdc25578f)
[Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/03e261b/devhub/docsworker-xlarge/june-23-2021/)
```
cf83bc1c DEVHUB-710: Use withPrefix for Search Images (#875)
0c9c0ce5 DEVHUB-715: Use relative links where appropriate for the footer (#874)
f8cfd00e DEVHUB-706: Add Canonical URL Fallback for Strapi Articles (#869)
ebf6963e Add new ENV option for username customization for staging links (#870)
76f4f1d1 Add Google Lighthouse Tooling into Github Actions CI …
```
> Deploy, June 23 2021

- gatsby-config.js
- gatsby-config.prod-new.js
- gatsby-config.prod.js
- src/utils/setup/article-rss-feed.js
- src/utils/setup/search-rss-feed.js
[Staging Link (built off of gatsby-config.prod-new.js) Sitemap](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-720/sitemap.xml)
[Staging Link (built off of gatsby-config.prod-new.js) RSS feed XML](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-720/rss.xml)
[Staging Link (built off of gatsby-config.prod-new.js) Search RSS feed XML](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-720/search-rss.xml)
This PR makes some build-time changes to prepare us for the domain swap. Specifically:
- We parameterize the /rss.xml and /search-rss.xml files to take the appropriate site url into account. These should now have a consistent URL
- We fix a bug where the sitemap had …
> DEVHUB-720: Swap site URLs for XML files generated

- src/components/dev-hub/searchbar/ExpandedSearchbar.js
- src/components/dev-hub/searchbar/Searchbar.js
[JIRA](https://jira.mongodb.org/browse/DEVHUB-772)
[Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-772/)
This PR fixes some keyboard navigation behavior on DevHub. Previously, because of a key binding, readers could not scroll down on articles using arrow keys (up/down). This PR cleans up the event listener to only listen for these keys when the searchbar is focused on. To verify:
- Open the staging link
- Go to an article
- Try to scroll up/down using arrow keys
- Verify this does not work on production
- Search for something
- Press the down key and verify the first option is still highlighted
> DEVHUB-772: Only Listen for Search Keydown When Focused

- src/components/dev-hub/searchbar/ExpandedSearchbar.js
[Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-772-dep/)
It seemed like the staging link I had before worked sporadically and when testing again we may have been missing something. When the site is built with static rendering we set `isFocused` to `false` by default and don't update the event listener correctly. [I looked at the source code](https://github.com/mongodb/leafygreen-ui/blob/dea88e7dfa12fb44fe5dc429b0c97b2ad61ba075/packages/hooks/src/useEventListener.ts#L73) and it seems like the right thing to do is to also add `isFocused` as a dependency so the hook is re-run.
tl;dr, should work for real now all the time.
> DEVHUB-772: Also Update when isFocused changes

- gatsby-config.js
- gatsby-config.prod-new.js
- gatsby-config.prod.js
- src/constants.js
- src/utils/make-link-internal-if-applicable.js
- static/sitemap.xml
- tests/utils/make-link-internal-if-applicable.test.js
[Staging Link Sitemap](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-753/sitemap.xml)
This PR removes the community forums sitemap from DevHub's sitemap.xml and as a result, removes the existing sitemap index. This won't be merged until the forums is set to move on July 15th.
This also updates links on DevHub (minus the nav) to point to the new forums location
> [July 15th] DEVHUB-753: Remove Forums from DevHub Sitemap, Update Links

- package-lock.json
- package.json
This PR adds a new NPM package for radio buttons into our repo. [The source code (with documentation) is located here](https://github.com/mongodb/leafygreen-ui/tree/main/packages/radio-group)!
Once merged, to use the radio buttons, run `npm ci` and then follow the docs to add a `RadioGroup` and `Radio` to the form where needed, using the props `onChange` to run any code to update form state and `value` to control which one is active. If stuck I'm more than happy to help more :)
> Add Design Systems Radio Button Package

- src/pages/community-champions.js
-   [Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/sophia.li/set-champion-background-colour/community-champions/)
-  I noticed one of the champion photos had a transparent background, so the gradient shows through like this:
- This PR sets the background colour to white (colour confirmed by Mike 🙂). I think this will make it easier for us in the future if we get more champion photos with transparent backgrounds as we won't have to ask people for new photos each time. Lmk what you think!
- Check out Leandro's photo and verify the background is white.
> Community Champions - Set champion background colour

- src/pages/community-champions.js
-   JIRA Ticket N/A
-   [Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/jordanstapinski/add-champions-title/community-champions/)
-   This PR adds a `<title>` tag to the entry page. This tag is good for SEO as well as a nice improvement by putting something other than the URL in the tab for the page.
-   `react-helmet` is a library which puts any children into the `head` of the HTML page created to keep metadata organized
-   Check that in the browser tab there is a reasonable title
> Add a title tag to community champions

- src/utils/setup/map-publication-state-to-array.js
This PR adds a fallback for pulling publication state so it defaults to `live`. This was the behavior on the fork and may persist on the autobuilder (the `env` var may not have been supplied since the default was `live` if omitted)
No staging link really necessary
> DEVHUB-686: Add fallback for strapi publication state

- gatsby-config.js
- gatsby-config.prod-new.js
- gatsby-config.prod.js
- src/components/dev-hub/survey-banner.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-518)
-   This PR removes a field that changed with the new Sitemap plugin update. `output` expects to be the path to a directory since a sitemap-index is now the default. [Docs](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/)
-   I also resolved a warning about a missing label for `IconButton` since these now are emphasized on build output
-   /sitemap/sitemap-index.xml should work on a staging link
> DEVHUB-518: Remove legacy field from sitemap construction

- gatsby-node.esm.js
- src/queries/community-champions.js
- src/templates/community-champion-profile.js
- src/utils/setup/create-community-champion-profile-pages.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-784)
-   [Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/sophia.li/DEVHUB-784/community-champions/chris-dellaway/)
-   This PR sets up the creation of Community Champion profile pages!
-   Verify that there are pages at /community-champions/firstname-lastname for the champions shown at the bottom [here](https://docs-mongodbcom-staging.corp.mongodb.com/CI/devhub/sophia.li/DEVHUB-784/community-champions/). Profile pages currently only have breadcrumbs shown at the top.
> Community Champions - set up profile page template

- src/pages/404.js
- src/pages/academia/educators.js
- src/pages/code-for-good.js
- src/pages/community/events.js
- src/pages/community/index.js
- src/pages/learn.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-518)
-   [Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-518-warnings/)
-   This ticket addresses some Gatsby v3 development warnings where we had some pages not using named exports. Named exports are the following pattern:
```
const Page = () => {};
export default Page;
```
whereas we did
```
export default () => {}
```
This let's Gatsby preserve page state a bit better on a hot reload (and addresses some verbose warnings!)
-   These pages should still work
> DEVHUB-518: Resolve Named Export Warnings

- src/components/dev-hub/codeblock.js
- src/utils/determine-correct-leafygreen-language.js
- tests/utils/determine-correct-leafygreen-language.test.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-789)
-   [Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-789/)
-   This PR improves the Codeblock logic to be more resilient if passed a language highlight option which is not supported. The idea is that we check from leafygreen (LG) if a language is supported and, if not, using `none` and throwing a warning.
-   I added automated testing for the updated logic
-   Codeblocks in the staging link should still be highlighted
> DEVHUB-789: Gracefully Handle Unsupported Lanagues in Codeblocks

- cypress/integration/strapi-article.js
- gatsby-config.js
- gatsby-config.prod-new.js
- gatsby-config.prod.js
- gatsby-node.esm.js
- src/classes/strapi-article-series.ts
- src/queries/article-series.js
- src/utils/setup/get-strapi-article-series-from-graphql.js
- src/utils/transform-article-strapi-data.js
-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=610bea37382fd7618e25ba75)
-   [Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/cf33d36/devhub/docsworker-xlarge/strapi-series/)
-   This PR swaps the series logic to pull from Strapi and not Snooty
-   Tests should still pass
> Swap Article Series Source to Strapi (#913)

- src/constants.js
- tests/utils/make-link-internal-if-applicable.test.js
-   No JIRA Ticket
-   [Staging Link article fixed](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/fix-old-community-url/article/introduction-to-modern-databases-mongodb-academia/?tck=feathome)
-   [Same article on prod with issue](https://www.mongodb.com/developer/article/introduction-to-modern-databases-mongodb-academia/?tck=feathome)
-   This PR fixes a bug related to the subdomain swap in which we incorrectly parsed old links to the forums and made links internal. We should have not changed these links and leave the href as it was. The bug was that the `OLD_SUBDOMAIN_FORUMS_URL` pointed to `https://www.mongodb.com/developer/community/forums` and not `https://developer.mongodb.com/community/forums`
-   I updated our unit test to be a bit stronger and …
> Don't make community forum links internal

- src/classes/strapi-article-series.ts
- src/utils/setup/is-strapi-article.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-801)
-   [Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-801/)
-   This PR fixes an issue where DAs could add draft articles to a series (which is fine) but this would break on prod builds (which is not fine). This broke prod builds since the article coming back when pulling in the article was `null` if it is still in draft. The raw data looks like this:
```
"seriesEntry": [
// Published article
{
"__component": "article-info.strapi-article",
"_id": "61005e9fd1dcc8c72258c14e",
"__v": 0,
"article": {
"type": "Article",
"awaiting_editorial_review": false,
"awaiting_technical_review": false,
"editorial_review_LGTM": false,
"technical_review_LGTM": false,
"authors": [],
"_id": …
```
> DEVHUB-801: Filter Draft Series Articles from Prod Platform Builds

- src/components/pages/community-champions/meet-the-champions.js
- src/pages/community-champions.js
-   ~~JIRA Ticket~~
-   [Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/CI/devhub/sophia.li/fix-safari-community-champions-row-gap/community-champions)
-   Safari versions < 14.1 don't support flexbox gaps, so the row gaps in the "Meet the Champions" section don't show up. This PR replaces use of row gaps with vertical margins, and updates the title's bottom margin and container's bottom padding to make the spacing look the same as it was before. 
- I also moved this component into a separate file!
- Go to the staging link on Safari and verify that there is spacing between the rows 
- Verify that nothing looks different on Chrome, you can use prod site to check!
-   [ ] Release Note Update (only for …
> Fix row gap in "Meet the Champions" section

- .github/workflows/devhub-ci-test.yaml
- cypress/integration/search.js
- gatsby-config.js
-   [Staging Link without GTM](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/remove-gtm-testing/)
-   This PR adds an opt-in way of disabling GTM for testing, etc. as a result of GTM issues causing CI failures
-   Tests should pass
> Remove GTM from cypress CI builds

- src/components/Literal.js
- src/templates/article.js
- tests/unit/__snapshots__/DefinitionList.test.js.snap
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-798)
-   [Staging Link](https://docs-mongodborg-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-798/)
-   This PR removes the `hyphens: auto` css from articles. It also removes some related logic in the `literal` (inline code) component which was added to disable hyphens there, as we no longer need this change
-   Articles should still render properly
-   Articles should still be mobile-responsive
> DEVHUB-798: Remove hyphens auto

- src/components/Literal.js
- src/templates/article.js
- tests/unit/__snapshots__/DefinitionList.test.js.snap
-   [Staging Job](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6130e24a7dcf012930fc8421)
-   [Staging Link](http://docs-devhub-staging.s3-website-us-east-1.amazonaws.com/7386a2d/devhub/docsworker-xlarge/sep-2-21)
```
5cc53d62 DEVHUB-798: Remove hyphens auto (#960)
```
-   Articles should no longer have hyphenation when wrapping
> Deploy DEVHUB-798: Remove hyphens auto (#960)

- src/components/Break.js
- src/components/ComponentFactory.js
- src/components/Delete.js
- src/utils/determine-correct-leafygreen-language.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-583)
-   [Staging Link Strikethrough Example](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-583/how-to/adding-realm-as-dependency-ios-framework/#the-problem)
-   [Staging Link Break Example](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-583/project/hostels-kenya/#why-mongodb-)
-   [Staging Link golang example](https://docs-mongodbcom-staging.corp.mongodb.com/master/devhub/jordanstapinski/DEVHUB-583/how-to/get-hyped-using-docker-go-mongodb/)
-   This PR resolves three warnings that would show at build-time:
1. Resolves a warning for `undefined (break) not implemented`. This occurred one time in the `/projects/hostels-kenya` page where someone wanted to …
> DEVHUB-583: Fix Directive Warnings (Break, Delete, Golang)

- Makefile
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-837)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/consistent-nav-trial/)
-   This PR updates a repo-specific local Makefile for pushing builds to a staging link. With the Docs changes let's use the DevRel account and push to our developer-hub-staging bucket. A sample staging link is supplied. I also will give AWS keys to you directly to put in .env.production
-   Try to make a staging link
> DEVHUB-837: Use devrel s3 bucket for staging local builds

- src/components/dev-hub/consistent-nav.js
- src/pages/learn.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-848)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-848/learn/#main)
-   When people search with the new nav, because it is sticky we need to move the element with `id="main"` so that the options are not being cut off by the sticky nav.
-   Staging link should go to the right place
> DEVHUB-848: Use grid sizing to prevent jumpy anchor link

- cypress/integration/community-champions/entry.js
- package-lock.json
- package.json
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-850)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-850/community-champions)
-   This PR fixes a bug where leafygreen components did not have proper peer dependencies. This was likely introduced as a result of updating dependencies around the consistent nav (hard to see all changes to package-lock). [I raised this to design systems to fix as well](https://jira.mongodb.org/browse/PD-1581). Our solution is to ensure our dependencies match. Fortunately, with the new nav, this is the only place we use the radio button.
-   UI tests pass
-   Modal at the staging link should open when the button is pressed
-   [ ] …
> DEVHUB-850: Fix Dep Error on Champions Modal

- src/pages/learn.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-849)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-849/learn/?content=articles)
-   This PR fixes a bug with the new nav in which the `content` query param would not be applied because it was `articles` vs `Articles`. This is resolved by leveraging the object we use as an enum to use the key.
-   http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-849/learn/?content=articles should just show articles
> DEVHUB-849: Accept lowercase content filters

- gatsby-node.esm.js
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/await-images/)
This PR fixes a race condition where snooty images may not always be uploaded to S3 on a deploy
> Properly Await Snooty Image Upload

- gatsby-config.js
- gatsby-config.prod.js
-   [JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-838)
-   [Staging Link](http://developer-hub-staging.s3-website-us-east-1.amazonaws.com/master/devhub/jordanstapinski/DEVHUB-838/)
-   This PR removes the default 100 limit from API requests to the CMS. This default is due to the [plugin](https://www.gatsbyjs.com/plugins/gatsby-source-strapi/). The change is based on [this response to an issue](https://github.com/strapi/gatsby-source-strapi/pull/32/files) on GitHub for this same problem.
-   All CMS content should still be included, tests pass.
> DEVHUB-838: Remove 100 query limit from CMS

- cypress/integration/learn.js
- src/classes/strapi-article.ts
- src/queries/articles.js
When articles are imported from either Rst or medium or any other frame work we want it to carry original date of the post as its published date, instead of the date it is published from strapi. This PR addresses that issue and original Publish date takes precedence over strapi's pubhished at.
> DEVHUB-925 Adds a new field original publish date to strapi articles

- cypress/integration/article.js
- cypress/integration/learn.js
- src/classes/strapi-article.ts
- src/components/dev-hub/active-card-list-filter.js
- src/components/dev-hub/card-list.js
- src/interfaces/article.ts
Previously we used to sort cards by update date. With the migration of RST articles into CMS a lot of old articles are being surfaced in the front pages due to their latest update dates. This PR adds the logic to use Published Date instead of Update date while sorting the articles migrated from RST.
> DEVHUB-939 Fixing ordering for snooty original articles
